export interface NameDetail {
  number: number
  arabic: string
  transliteration: string
  meaning: string
  rootWord: string
  explanation: string
  quranRef: string
  quranText: string
  benefit: string
  category: 'mercy' | 'knowledge' | 'power' | 'creation' | 'sovereignty' | 'beauty' | 'justice' | 'uniqueness'
}

export const NAMES_DETAIL: NameDetail[] = [
  {
    number: 1,
    arabic: 'الرَّحْمَنُ',
    transliteration: 'Ar-Rahman',
    meaning: 'The Most Gracious',
    rootWord: 'ر-ح-م (ra-ha-ma) — mercy, compassion',
    explanation: 'Ar-Rahman refers to the vast, all-encompassing mercy of Allah that extends to every creature in this world — believer and disbeliever alike. This mercy is manifested in the sustenance, guidance, and countless blessings that pervade all of creation. It is an intensive form indicating the immense breadth of divine mercy.',
    quranRef: 'Al-Fatihah 1:3',
    quranText: 'The Most Gracious, the Most Merciful.',
    benefit: 'When overwhelmed by hardship, remember that Ar-Rahman\'s mercy encompasses all things. Call upon Him by this name knowing that His compassion reaches you no matter your situation, and let this awareness fill your heart with hope and gratitude.',
    category: 'mercy',
  },
  {
    number: 2,
    arabic: 'الرَّحِيمُ',
    transliteration: 'Ar-Raheem',
    meaning: 'The Most Merciful',
    rootWord: 'ر-ح-م (ra-ha-ma) — mercy, compassion',
    explanation: 'Ar-Raheem denotes the special, focused mercy that Allah reserves for the believers in the Hereafter. While Ar-Rahman gives mercy to all in this world, Ar-Raheem bestows a particular mercy upon those who believe — granting them Paradise, forgiveness, and eternal bliss. This name gives the believer confidence in Allah\'s reward.',
    quranRef: 'Al-Fatihah 1:3',
    quranText: 'The Most Gracious, the Most Merciful.',
    benefit: 'Strive to be among those who receive the special mercy of Ar-Raheem by strengthening your faith and doing good deeds. When you sin, turn back to Him immediately, knowing that His mercy for the repentant believer is boundless.',
    category: 'mercy',
  },
  {
    number: 3,
    arabic: 'الْمَلِكُ',
    transliteration: 'Al-Malik',
    meaning: 'The King',
    rootWord: 'م-ل-ك (ma-la-ka) — to possess, to own, sovereignty',
    explanation: 'Al-Malik is the absolute sovereign and ruler of all that exists. His dominion is complete and unchallenged — He owns all creation and disposes of all affairs as He wills. Unlike earthly kings whose rule is limited and temporary, Allah\'s kingship is eternal, perfect, and self-sufficient.',
    quranRef: 'Al-Fatihah 1:4',
    quranText: 'Master of the Day of Judgment.',
    benefit: 'Recognising Allah as Al-Malik frees you from fear of any worldly authority. Place your ultimate trust in the King of all kings, and do not let the power of any created being cause you to compromise your faith or principles.',
    category: 'sovereignty',
  },
  {
    number: 4,
    arabic: 'الْقُدُّوسُ',
    transliteration: 'Al-Quddus',
    meaning: 'The Most Holy',
    rootWord: 'ق-د-س (qa-da-sa) — purity, sanctity, holiness',
    explanation: 'Al-Quddus means that Allah is completely pure and free from any deficiency, imperfection, or resemblance to creation. He is exalted above all that does not befit His majesty. Every attribute of Allah is in its utmost perfection, untouched by any flaw.',
    quranRef: 'Al-Hashr 59:23',
    quranText: 'He is Allah, other than whom there is no deity, the Sovereign, the Pure, the Perfection, the Grantor of Security, the Overseer, the Exalted in Might, the Compeller, the Superior.',
    benefit: 'Reflecting on Al-Quddus inspires you to purify your own heart and actions. Strive to keep your intentions sincere and your worship free from showing off, knowing that the Most Pure appreciates purity of heart.',
    category: 'beauty',
  },
  {
    number: 5,
    arabic: 'السَّلَامُ',
    transliteration: 'As-Salam',
    meaning: 'The Source of Peace',
    rootWord: 'س-ل-م (sa-la-ma) — peace, safety, soundness',
    explanation: 'As-Salam is the ultimate source of all peace, safety, and security. He is free from every imperfection and grants peace to His creation. The Islamic greeting "As-salamu alaykum" derives from this divine name, spreading peace as an act of worship. Paradise itself is called Dar as-Salam — the abode of peace.',
    quranRef: 'Al-Hashr 59:23',
    quranText: 'He is Allah, other than whom there is no deity, the Sovereign, the Pure, the Perfection, the Grantor of Security.',
    benefit: 'When anxiety or fear grips you, call upon As-Salam to grant you inner peace and tranquillity. Spread peace through your words and actions, knowing that true peace comes only from the One who is Peace itself.',
    category: 'beauty',
  },
  {
    number: 6,
    arabic: 'الْمُؤْمِنُ',
    transliteration: "Al-Mu'min",
    meaning: 'The Guardian of Faith',
    rootWord: 'أ-م-ن (a-ma-na) — security, trust, faith',
    explanation: "Al-Mu'min is the One who grants security and protection to His servants. He affirms the truthfulness of His messengers through miracles and confirms His own oneness through clear signs. Believers are called Mu'minoon because they take their security and faith from Allah, the ultimate source of trust.",
    quranRef: 'Al-Hashr 59:23',
    quranText: 'He is Allah, other than whom there is no deity, the Sovereign, the Pure, the Perfection, the Grantor of Security.',
    benefit: "In times of insecurity and doubt, remember that Al-Mu'min is the granter of true safety. Place your trust entirely in Him, and He will grant you the security of faith that no worldly circumstance can shake.",
    category: 'mercy',
  },
  {
    number: 7,
    arabic: 'الْمُهَيْمِنُ',
    transliteration: 'Al-Muhaymin',
    meaning: 'The Protector',
    rootWord: 'ه-ي-م-ن (ha-ya-ma-na) — to watch over, to oversee',
    explanation: 'Al-Muhaymin is the One who watches over all affairs with meticulous care, guarding and preserving everything in creation. Nothing escapes His vigilant oversight. He ensures that every matter runs according to His perfect plan, protecting what He wills and overseeing all that occurs.',
    quranRef: 'Al-Hashr 59:23',
    quranText: 'He is Allah, other than whom there is no deity, the Sovereign, the Pure, the Perfection, the Grantor of Security, the Overseer.',
    benefit: 'Knowing that Al-Muhaymin watches over every detail of your life brings comfort in uncertainty. Trust that nothing in your life happens without His oversight, and let this awareness make you mindful of your actions.',
    category: 'sovereignty',
  },
  {
    number: 8,
    arabic: 'الْعَزِيزُ',
    transliteration: 'Al-Aziz',
    meaning: 'The Almighty',
    rootWord: 'ع-ز-ز (a-za-za) — might, power, honour',
    explanation: 'Al-Aziz is mighty in a way that cannot be overcome or resisted. His power is absolute, His honour is supreme, and none can challenge His authority. All true honour and might belong to Allah alone, and those whom He honours are truly honoured.',
    quranRef: 'Al-Hashr 59:23',
    quranText: 'The Exalted in Might, the Compeller, the Superior. Exalted is Allah above whatever they associate with Him.',
    benefit: 'Seek honour only from Al-Aziz, for true dignity comes from obedience to Him. Do not humiliate yourself before creation seeking status — instead, hold fast to your faith, and Allah will grant you honour in ways you never expected.',
    category: 'power',
  },
  {
    number: 9,
    arabic: 'الْجَبَّارُ',
    transliteration: 'Al-Jabbar',
    meaning: 'The Compeller',
    rootWord: 'ج-ب-ر (ja-ba-ra) — to compel, to restore, to mend',
    explanation: 'Al-Jabbar carries a dual meaning: He compels all creation to His will, and He mends what is broken. He restores the hearts of the broken-hearted, heals the wounded, and sets right what has gone wrong. His compelling power is paired with His mercy to restore and repair.',
    quranRef: 'Al-Hashr 59:23',
    quranText: 'The Exalted in Might, the Compeller, the Superior.',
    benefit: 'When your heart is shattered by loss or grief, turn to Al-Jabbar — the mender of broken hearts. Ask Him to restore what is broken within you, and trust that He has the power to heal every wound and right every wrong.',
    category: 'power',
  },
  {
    number: 10,
    arabic: 'الْمُتَكَبِّرُ',
    transliteration: 'Al-Mutakabbir',
    meaning: 'The Greatest',
    rootWord: 'ك-ب-ر (ka-ba-ra) — greatness, grandeur, supremacy',
    explanation: 'Al-Mutakabbir is supremely great, possessing a grandeur that belongs only to Him. While arrogance is a blameworthy trait in creation, supreme greatness is a divine attribute that only Allah deserves. He is above all imperfection and above any comparison with His creation.',
    quranRef: 'Al-Hashr 59:23',
    quranText: 'The Exalted in Might, the Compeller, the Superior. Exalted is Allah above whatever they associate with Him.',
    benefit: 'Reflecting on Al-Mutakabbir should humble you before Allah while freeing you from the arrogance that afflicts the human ego. True greatness belongs to Allah alone — embrace humility, and you will find yourself elevated in His sight.',
    category: 'sovereignty',
  },
  {
    number: 11,
    arabic: 'الْخَالِقُ',
    transliteration: 'Al-Khaliq',
    meaning: 'The Creator',
    rootWord: 'خ-ل-ق (kha-la-qa) — to create, to bring into being',
    explanation: 'Al-Khaliq creates everything from nothing, determining and planning all of existence before bringing it into being. He is the originator of all creation, from the vast galaxies to the smallest atoms. Every created thing testifies to His creative power and wisdom.',
    quranRef: 'Al-Hashr 59:24',
    quranText: 'He is Allah, the Creator, the Inventor, the Fashioner; to Him belong the best names.',
    benefit: 'When you see the wonders of creation around you, let them remind you of Al-Khaliq. Know that the One who created the heavens and earth from nothing can certainly create solutions to your problems and open doors you never imagined.',
    category: 'creation',
  },
  {
    number: 12,
    arabic: 'الْبَارِئُ',
    transliteration: "Al-Bari'",
    meaning: 'The Maker of Order',
    rootWord: 'ب-ر-أ (ba-ra-a) — to shape, to form distinctly, to evolve',
    explanation: "Al-Bari' is the One who distinguishes and separates creation into unique forms, giving each thing its distinct characteristics. He brings things into existence with precise differentiation — no two snowflakes, no two fingerprints are the same. This name highlights the individuality within Allah's creation.",
    quranRef: 'Al-Hashr 59:24',
    quranText: 'He is Allah, the Creator, the Inventor, the Fashioner; to Him belong the best names.',
    benefit: "Appreciate your unique qualities, for Al-Bari' fashioned you with deliberate distinction. You are not an accident — every aspect of your being was carefully differentiated by the Maker of Order for a purpose only He fully knows.",
    category: 'creation',
  },
  {
    number: 13,
    arabic: 'الْمُصَوِّرُ',
    transliteration: 'Al-Musawwir',
    meaning: 'The Shaper of Beauty',
    rootWord: 'ص-و-ر (sa-wa-ra) — to form, to shape, to fashion',
    explanation: 'Al-Musawwir fashions each creation with a unique and beautiful form. He gives everything its distinctive appearance and shape, from the human face to the pattern on a leaf. He forms things in the womb, shaping each person with a unique countenance that reflects His creative artistry.',
    quranRef: 'Al-Hashr 59:24',
    quranText: 'He is Allah, the Creator, the Inventor, the Fashioner; to Him belong the best names. Whatever is in the heavens and earth is exalting Him.',
    benefit: 'Be content with the form Allah has given you, for Al-Musawwir shaped you with purpose and beauty. Instead of comparing yourself to others, appreciate the unique form that the Divine Fashioner chose specifically for you.',
    category: 'creation',
  },
  {
    number: 14,
    arabic: 'الْغَفَّارُ',
    transliteration: 'Al-Ghaffar',
    meaning: 'The Forgiving',
    rootWord: 'غ-ف-ر (gha-fa-ra) — to cover, to conceal, to forgive',
    explanation: 'Al-Ghaffar forgives sins repeatedly and abundantly, covering them and concealing them from others. The root meaning of "covering" indicates that He not only forgives but also hides the sins of His servants, protecting their honour. This is an intensive form, meaning He forgives again and again without limit.',
    quranRef: 'Nuh 71:10',
    quranText: 'And said, "Ask forgiveness of your Lord. Indeed, He is ever a Perpetual Forgiver."',
    benefit: 'No matter how many times you fall into sin, never despair of Al-Ghaffar\'s forgiveness. He covers your sins from others and forgives them when you sincerely repent. Return to Him every time you stumble — His door of forgiveness never closes.',
    category: 'mercy',
  },
  {
    number: 15,
    arabic: 'الْقَهَّارُ',
    transliteration: 'Al-Qahhar',
    meaning: 'The Subduer',
    rootWord: 'ق-ه-ر (qa-ha-ra) — to overpower, to subdue, to dominate',
    explanation: 'Al-Qahhar overpowers all of creation, and none can resist His will. He subdues all things — the arrogant, the oppressors, and even death itself on the Day of Judgment. His irresistible power ensures that ultimately, justice prevails and every soul is held accountable.',
    quranRef: 'Ar-Ra\'d 13:16',
    quranText: 'Say, "Allah is the Creator of all things, and He is the One, the Prevailing."',
    benefit: 'When you see injustice in the world, take comfort in knowing that Al-Qahhar will ultimately subdue every oppressor. No tyrant can escape His power. Trust in His timing and maintain patience, for His justice is certain.',
    category: 'power',
  },
  {
    number: 16,
    arabic: 'الْوَهَّابُ',
    transliteration: 'Al-Wahhab',
    meaning: 'The Bestower',
    rootWord: 'و-ه-ب (wa-ha-ba) — to give freely, to bestow',
    explanation: 'Al-Wahhab gives freely, generously, and without any expectation of return. His gifts are limitless and given purely from His grace — not because of any obligation. He bestows blessings upon whom He wills: children, wealth, wisdom, guidance, and every good thing comes from His unlimited treasury.',
    quranRef: 'Ali Imran 3:8',
    quranText: 'Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower.',
    benefit: 'When in need, call upon Al-Wahhab and ask freely, for He gives without limit and without expecting anything in return. Do not hesitate to ask Him for anything — no request is too great or too small for the One who bestows freely.',
    category: 'mercy',
  },
  {
    number: 17,
    arabic: 'الرَّزَّاقُ',
    transliteration: 'Ar-Razzaq',
    meaning: 'The Provider',
    rootWord: 'ر-ز-ق (ra-za-qa) — to provide, to sustain, sustenance',
    explanation: 'Ar-Razzaq provides all provision — both physical and spiritual. He sustains every living creature with food, water, air, knowledge, faith, and everything they need to exist. No creature is forgotten in His provision, and what He has decreed for you will reach you no matter what.',
    quranRef: 'Az-Zariyat 51:58',
    quranText: 'Indeed, it is Allah who is the Continual Provider, the Firm Possessor of Strength.',
    benefit: 'When worried about livelihood, remember that Ar-Razzaq has guaranteed the provision of every creature. Focus on obeying Him and excelling in your efforts, and trust that your sustenance will come to you — for what is written for you will never miss you.',
    category: 'mercy',
  },
  {
    number: 18,
    arabic: 'الْفَتَّاحُ',
    transliteration: 'Al-Fattah',
    meaning: 'The Opener',
    rootWord: 'ف-ت-ح (fa-ta-ha) — to open, to grant victory, to judge',
    explanation: 'Al-Fattah opens all doors that are closed — doors of mercy, provision, guidance, knowledge, and victory. When situations seem impossible and every path appears blocked, He is the One who creates openings where none existed. He also opens between disputing parties with His just judgement.',
    quranRef: 'Saba 34:26',
    quranText: 'Say, "Our Lord will bring us together; then He will judge between us in truth. And He is the Knowing Judge."',
    benefit: 'When facing a closed door in life, call upon Al-Fattah to open it for you. No obstacle is permanent before His power. Be patient and persistent in dua, trusting that the Opener will create a way out when you least expect it.',
    category: 'power',
  },
  {
    number: 19,
    arabic: 'اَلْعَلِيْمُ',
    transliteration: 'Al-Aleem',
    meaning: 'The All-Knowing',
    rootWord: 'ع-ل-م (a-li-ma) — to know, knowledge',
    explanation: 'Al-Aleem possesses complete and perfect knowledge of all things — past, present, and future, the seen and the unseen, the manifest and the hidden. Not even the weight of an atom escapes His knowledge. His knowledge encompasses the thoughts in every heart and the secrets of every soul.',
    quranRef: 'Al-Baqarah 2:29',
    quranText: 'It is He who created for you all of that which is on the earth. Then He directed Himself to the heaven and made them seven heavens, and He is Knowing of all things.',
    benefit: 'Knowing that Al-Aleem sees all your struggles — even those you cannot express — brings deep comfort. Pour your heart out in dua, for He already knows what you need. Let His awareness also make you watchful over your inner thoughts and intentions.',
    category: 'knowledge',
  },
  {
    number: 20,
    arabic: 'الْقَابِضُ',
    transliteration: 'Al-Qabid',
    meaning: 'The Constrictor',
    rootWord: 'ق-ب-ض (qa-ba-da) — to seize, to withhold, to constrict',
    explanation: 'Al-Qabid withholds and constricts by His wisdom, not out of stinginess or cruelty. He may constrict provision, health, or ease as a test, a purification, or a redirection toward what is better. This name is always paired with Al-Basit — the One who expands — showing the balance of divine wisdom.',
    quranRef: 'Al-Baqarah 2:245',
    quranText: 'Allah constricts and expands provision, and to Him you will be returned.',
    benefit: 'When experiencing constriction in any area of life, remember it is Al-Qabid\'s wisdom at work. Be patient in times of tightness, for every constriction is followed by expansion. This difficulty is not punishment — it may be the very thing that draws you closer to Him.',
    category: 'sovereignty',
  },
  {
    number: 21,
    arabic: 'الْبَاسِطُ',
    transliteration: 'Al-Basit',
    meaning: 'The Expander',
    rootWord: 'ب-س-ط (ba-sa-ta) — to spread, to expand, to extend',
    explanation: 'Al-Basit is the One who expands provision, opens the heart, and extends blessings to His servants by His mercy. He widens what was constricted and brings relief after difficulty. After every period of tightness, He brings ease — and His expansion is always greater than the constriction that preceded it.',
    quranRef: 'Al-Baqarah 2:245',
    quranText: 'Allah constricts and expands provision, and to Him you will be returned.',
    benefit: 'In times of abundance and expansion, thank Al-Basit and remember those who are still in constriction. Be generous when He expands your provision, for sharing blessings invites even more expansion from the One who expands without limit.',
    category: 'mercy',
  },
  {
    number: 22,
    arabic: 'الْخَافِضُ',
    transliteration: 'Al-Khafid',
    meaning: 'The Abaser',
    rootWord: 'خ-ف-ض (kha-fa-da) — to lower, to bring down, to humble',
    explanation: 'Al-Khafid lowers the arrogant and those who oppose the truth. He brings down tyrants, humbles the proud, and reduces the status of those who transgress His limits. This name is paired with Ar-Rafi\' — reminding us that all elevation and reduction is in Allah\'s hands alone.',
    quranRef: 'Al-Waqi\'ah 56:3',
    quranText: 'It will bring down some and raise up others.',
    benefit: 'Fear Al-Khafid by avoiding arrogance and pride in all their forms. Stay humble before Allah and His creation, for He lowers those who see themselves as too great. True safety lies in recognising your dependence on Him.',
    category: 'justice',
  },
  {
    number: 23,
    arabic: 'الرَّافِعُ',
    transliteration: "Ar-Rafi'",
    meaning: 'The Exalter',
    rootWord: 'ر-ف-ع (ra-fa-a) — to raise, to elevate, to exalt',
    explanation: "Ar-Rafi' raises in rank those whom He wills — the humble, the believers, the scholars, and the righteous. He elevates through knowledge, piety, and good deeds. True honour is not in worldly status but in the elevation that comes from sincerity and closeness to Allah.",
    quranRef: 'Al-Mujadila 58:11',
    quranText: 'Allah will raise those who have believed among you and those who were given knowledge, by degrees.',
    benefit: "Seek elevation from Ar-Rafi' through knowledge, humility, and sincere worship — not through worldly competition. He raises whom He wills, and the surest path upward is the one that goes through humility before Him.",
    category: 'sovereignty',
  },
  {
    number: 24,
    arabic: 'الْمُعِزُّ',
    transliteration: "Al-Mu'izz",
    meaning: 'The Honourer',
    rootWord: 'ع-ز-ز (a-za-za) — to honour, to strengthen, to make mighty',
    explanation: "Al-Mu'izz bestows honour and dignity upon whom He wills. He can take a person from the lowest state and grant them the highest honour. True izzah (honour) comes only from Him — not from wealth, lineage, or social status. Those who seek honour from other than Allah will find only humiliation.",
    quranRef: 'Ali Imran 3:26',
    quranText: 'Say, "O Allah, Owner of Sovereignty, You give sovereignty to whom You will and You take sovereignty away from whom You will. You honour whom You will and You humble whom You will."',
    benefit: "Never seek honour from people at the expense of your faith. Ask Al-Mu'izz for true dignity — the kind that comes from obedience to Him. When people honour or dishonour you, remember that all honour ultimately flows from His decree.",
    category: 'sovereignty',
  },
  {
    number: 25,
    arabic: 'المُذِلُّ',
    transliteration: 'Al-Mudhill',
    meaning: 'The Dishonourer',
    rootWord: 'ذ-ل-ل (dha-la-la) — to abase, to humiliate, to make lowly',
    explanation: 'Al-Mudhill humiliates and disgraces the arrogant, those who reject truth, and those who oppress. He strips away false honour from those who rebel against Him. This name is paired with Al-Mu\'izz — a reminder that all honour and disgrace are in Allah\'s hands alone.',
    quranRef: 'Ali Imran 3:26',
    quranText: 'You honour whom You will and You humble whom You will. In Your hand is all good. Indeed, You are over all things competent.',
    benefit: 'Fear Al-Mudhill by never letting arrogance enter your heart. Treat everyone with respect regardless of their status, knowing that the One who humbles can reverse any situation in an instant. Seek refuge in Allah from disgrace caused by your own sins.',
    category: 'justice',
  },
  {
    number: 26,
    arabic: 'السَّمِيعُ',
    transliteration: "As-Sami'",
    meaning: 'The All-Hearing',
    rootWord: 'س-م-ع (sa-mi-a) — to hear, to listen, to respond',
    explanation: "As-Sami' hears everything — the whisper of a leaf in the wind, the silent plea of a broken heart, and the secret conversation of those who plot in darkness. His hearing is not like that of creation; He hears all sounds simultaneously without any one drowning out another.",
    quranRef: 'Al-Baqarah 2:127',
    quranText: 'And when Ibrahim was raising the foundations of the House and Ismail, saying, "Our Lord, accept from us. Indeed You are the Hearing, the Knowing."',
    benefit: "When you make dua in the quiet of the night, know that As-Sami' hears every word, every whisper, even the thoughts you cannot put into words. No prayer goes unheard — let this give you confidence to call upon Him always.",
    category: 'knowledge',
  },
  {
    number: 27,
    arabic: 'الْبَصِيرُ',
    transliteration: 'Al-Basir',
    meaning: 'The All-Seeing',
    rootWord: 'ب-ص-ر (ba-sa-ra) — to see, to perceive, to discern',
    explanation: 'Al-Basir sees everything — what is visible and what is concealed, the movements of a black ant on a dark rock on a moonless night. Nothing is hidden from His sight. He sees the tears you shed in secret, the good deeds done without recognition, and the injustice committed behind closed doors.',
    quranRef: 'Al-Isra 17:1',
    quranText: 'Exalted is He who took His Servant by night from al-Masjid al-Haram to al-Masjid al-Aqsa. Indeed, He is the Hearing, the Seeing.',
    benefit: 'Let the awareness that Al-Basir sees everything be both a comfort and a guard. Be comforted that your unseen struggles and secret good deeds are witnessed by Him. Be guarded in your actions, knowing that nothing you do escapes His sight.',
    category: 'knowledge',
  },
  {
    number: 28,
    arabic: 'الْحَكَمُ',
    transliteration: 'Al-Hakam',
    meaning: 'The Judge',
    rootWord: 'ح-ك-م (ha-ka-ma) — to judge, to rule, to decide',
    explanation: 'Al-Hakam is the ultimate judge whose rulings are always perfectly correct and just. He judges between His servants in this life through His revealed law and will judge all of humanity on the Day of Judgment with absolute fairness. No appeal can overturn His decree, for His knowledge and justice are complete.',
    quranRef: 'Al-An\'am 6:114',
    quranText: 'Then is it other than Allah I should seek as judge while it is He who has revealed to you the Book explained in detail?',
    benefit: 'When wronged and finding no justice among people, take your case to Al-Hakam. He will judge with perfect justice — if not in this world, then certainly in the next. Be just in your own dealings, imitating the quality of the Supreme Judge.',
    category: 'justice',
  },
  {
    number: 29,
    arabic: 'الْعَدْلُ',
    transliteration: 'Al-Adl',
    meaning: 'The Just',
    rootWord: 'ع-د-ل (a-da-la) — justice, equity, balance',
    explanation: 'Al-Adl is perfectly just in all His decrees and actions. There is no injustice with Him, not even the weight of a mustard seed. He places everything in its rightful place, rewards good and punishes evil with perfect equity. His justice encompasses the seen and unseen, this life and the next.',
    quranRef: 'An-Nisa 4:40',
    quranText: 'Indeed, Allah does not do injustice, even as much as an atom\'s weight; while if there is a good deed, He multiplies it and gives from Himself a great reward.',
    benefit: 'Trust in Al-Adl\'s justice even when the world seems deeply unfair. Every act of oppression is recorded, and every tear is counted. Strive to be just in all your dealings as a reflection of this divine attribute, even when it is difficult.',
    category: 'justice',
  },
  {
    number: 30,
    arabic: 'اللَّطِيفُ',
    transliteration: 'Al-Latif',
    meaning: 'The Subtle One',
    rootWord: 'ل-ط-ف (la-tu-fa) — subtlety, gentleness, kindness',
    explanation: 'Al-Latif is subtle and gentle in His actions, reaching the finest and most hidden details of existence. He arranges affairs in ways so delicate and intricate that we often cannot perceive His hand until long after the fact. His kindness reaches us through paths we never anticipated.',
    quranRef: 'Al-Mulk 67:14',
    quranText: 'Does He who created not know, while He is the Subtle, the Acquainted?',
    benefit: 'When you look back at your life and see how things fell perfectly into place despite apparent chaos, you are witnessing Al-Latif at work. Trust His subtle arrangements even when you cannot see the wisdom, for He is working for you in ways too gentle and intricate to perceive.',
    category: 'beauty',
  },
  {
    number: 31,
    arabic: 'الْخَبِيرُ',
    transliteration: 'Al-Khabir',
    meaning: 'The All-Aware',
    rootWord: 'خ-ب-ر (kha-ba-ra) — to know by experience, to be aware of inner realities',
    explanation: 'Al-Khabir is aware of all inner states, hidden affairs, and the deepest secrets of every soul. His awareness penetrates beyond the surface to the very essence of things. He knows your true intentions behind every action, the sincerity behind every word, and the condition of every heart.',
    quranRef: 'Al-Hujurat 49:13',
    quranText: 'Indeed, the most noble of you in the sight of Allah is the most righteous of you. Indeed, Allah is Knowing and Acquainted.',
    benefit: 'Since Al-Khabir knows your innermost state, focus on purifying your intentions rather than perfecting appearances. He values sincerity over showmanship. Let this awareness encourage you to be genuine, knowing that the One who truly matters sees your real self.',
    category: 'knowledge',
  },
  {
    number: 32,
    arabic: 'الْحَلِيمُ',
    transliteration: 'Al-Halim',
    meaning: 'The Forbearing',
    rootWord: 'ح-ل-م (ha-la-ma) — forbearance, mildness, patience',
    explanation: 'Al-Halim shows forbearance despite having full power to punish. He gives time and respite to sinners, not rushing to punishment but allowing space for repentance. His forbearance is not weakness — He could punish instantly — but rather it is a deliberate mercy that gives His servants the chance to return to Him.',
    quranRef: 'Al-Baqarah 2:225',
    quranText: 'Allah does not impose blame upon you for what is unintentional in your oaths, but He imposes blame upon you for what your hearts have earned. And Allah is Forgiving and Forbearing.',
    benefit: 'Be grateful for Al-Halim\'s forbearance every day, for He does not immediately punish you for your sins. Use the time He gives you to repent sincerely. And practise forbearance yourself with others, following the example of your Lord.',
    category: 'mercy',
  },
  {
    number: 33,
    arabic: 'الْعَظِيمُ',
    transliteration: 'Al-Azeem',
    meaning: 'The Magnificent',
    rootWord: 'ع-ظ-م (a-dhu-ma) — greatness, magnificence, grandeur',
    explanation: 'Al-Azeem possesses magnificence and greatness beyond human comprehension. His greatness is not simply larger than creation — it is of an entirely different nature. No mind can fully grasp His majesty, and all of creation combined is as nothing compared to His magnificence.',
    quranRef: 'Al-Baqarah 2:255',
    quranText: 'And He is the Most High, the Most Great.',
    benefit: 'Recite Ayat al-Kursi regularly, which mentions Al-Ali and Al-Azeem together. Let the magnificence of Allah put all worldly concerns in perspective — the problems that seem overwhelming to you are insignificant before the One whose greatness is beyond comprehension.',
    category: 'beauty',
  },
  {
    number: 34,
    arabic: 'الْغَفُورُ',
    transliteration: 'Al-Ghafur',
    meaning: 'The All-Forgiving',
    rootWord: 'غ-ف-ر (gha-fa-ra) — to forgive, to cover, to conceal',
    explanation: 'Al-Ghafur forgives completely, erasing the sin as if it never existed. While Al-Ghaffar emphasises the frequency of forgiveness, Al-Ghafur emphasises its completeness and totality. When He forgives, the slate is wiped truly clean — the sin is removed from the record entirely.',
    quranRef: 'Az-Zumar 39:53',
    quranText: 'Say, "O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins. Indeed, it is He who is the Forgiving, the Merciful."',
    benefit: 'Never despair of Allah\'s forgiveness, no matter how great your sins. Al-Ghafur erases sins completely when you repent sincerely. The verse mentioning this name is one of the most hopeful in the entire Quran — carry it in your heart always.',
    category: 'mercy',
  },
  {
    number: 35,
    arabic: 'الشَّكُورُ',
    transliteration: 'Ash-Shakur',
    meaning: 'The Appreciative',
    rootWord: 'ش-ك-ر (sha-ka-ra) — to thank, to appreciate, to reward generously',
    explanation: 'Ash-Shakur appreciates and greatly rewards even the smallest good deed. He multiplies the reward of a single good action many times over and acknowledges every sincere effort, no matter how small it may seem. A moment of gratitude from a servant is met with an eternity of reward from Ash-Shakur.',
    quranRef: 'Fatir 35:30',
    quranText: 'That He may give them their rewards in full and increase them of His bounty. Indeed, He is Forgiving and Appreciative.',
    benefit: 'Never belittle any good deed, for Ash-Shakur multiplies rewards beyond imagination. A sincere smile, a kind word, even removing a harmful object from the road — He appreciates and rewards it all. Let this motivate you to do good consistently, knowing nothing is wasted.',
    category: 'beauty',
  },
  {
    number: 36,
    arabic: 'الْعَلِيُّ',
    transliteration: 'Al-Ali',
    meaning: 'The Most High',
    rootWord: 'ع-ل-و (a-la-wa) — to be high, to be exalted, to transcend',
    explanation: 'Al-Ali is the Most High in every sense — in His essence, His attributes, and His power. He is above all creation, above all deficiency, and above any comparison. Nothing in creation can reach His level, and all things are beneath His majesty and dominion.',
    quranRef: 'Al-Baqarah 2:255',
    quranText: 'And He is the Most High, the Most Great.',
    benefit: 'When you raise your hands in dua toward the heavens, you are acknowledging Al-Ali\'s transcendence. Let the awareness of His supreme highness make every other concern seem manageable, for the Most High is on your side when you sincerely turn to Him.',
    category: 'sovereignty',
  },
  {
    number: 37,
    arabic: 'الْكَبِيرُ',
    transliteration: 'Al-Kabir',
    meaning: 'The Most Great',
    rootWord: 'ك-ب-ر (ka-bu-ra) — to be great, greatness, grandeur',
    explanation: 'Al-Kabir possesses greatness that encompasses all things. He is greater than anything creation can conceive. This greatness is expressed every time a Muslim says "Allahu Akbar" — Allah is the Greatest. No thought, no imagination, no description can capture the fullness of His greatness.',
    quranRef: 'Al-Hajj 22:62',
    quranText: 'That is because Allah is the Truth, and that what they call upon other than Him is falsehood, and because Allah is the Most High, the Grand.',
    benefit: 'Every time you say "Allahu Akbar" in prayer, renew your awareness that Allah is greater than any worry, any enemy, any obstacle. Al-Kabir\'s greatness dwarfs every problem — let this declaration be a source of courage and perspective.',
    category: 'sovereignty',
  },
  {
    number: 38,
    arabic: 'الْحَفِيظُ',
    transliteration: 'Al-Hafiz',
    meaning: 'The Preserver',
    rootWord: 'ح-ف-ظ (ha-fi-dha) — to preserve, to protect, to guard',
    explanation: 'Al-Hafiz preserves and protects all of creation. He preserves the Quran from corruption, the universe from collapse, and the record of every deed for accountability. He guards His believing servants from harm and protects what is entrusted to His care with perfect vigilance.',
    quranRef: 'Hud 11:57',
    quranText: 'Indeed, my Lord is over all things Guardian.',
    benefit: 'Entrust your affairs to Al-Hafiz — your family, your health, your faith. He is the best of protectors. Recite the morning and evening adhkar as a means of seeking His protection, and trust that what He preserves, nothing can harm.',
    category: 'power',
  },
  {
    number: 39,
    arabic: 'المُقِيتُ',
    transliteration: 'Al-Muqit',
    meaning: 'The Nourisher',
    rootWord: 'ق-و-ت (qa-wa-ta) — to sustain, to nourish, to maintain',
    explanation: 'Al-Muqit nourishes and provides for every created thing with precision. He knows the exact sustenance each creature needs — physical, emotional, and spiritual — and delivers it in the right measure at the right time. He sustains not just bodies but hearts and souls as well.',
    quranRef: 'An-Nisa 4:85',
    quranText: 'And ever is Allah, over all things, a Keeper.',
    benefit: 'Trust that Al-Muqit provides exactly what you need, when you need it. If something is delayed, it is because the timing is not yet right. Nourish your body with halal food and your soul with Quran and dhikr, seeking sustenance from the One who nourishes all.',
    category: 'mercy',
  },
  {
    number: 40,
    arabic: 'الْحسِيبُ',
    transliteration: 'Al-Hasib',
    meaning: 'The Reckoner',
    rootWord: 'ح-س-ب (ha-sa-ba) — to reckon, to account, to suffice',
    explanation: 'Al-Hasib takes account of all things with precision and is sufficient as a reckoner. He records every deed — large and small — and will bring forth a complete accounting on the Day of Judgment. He is also Al-Hasib in the sense of being sufficient for those who rely on Him.',
    quranRef: 'An-Nisa 4:6',
    quranText: 'And sufficient is Allah as Accountant.',
    benefit: 'Be mindful that Al-Hasib records everything. Take yourself to account before you are taken to account — review your actions daily, seek forgiveness for shortcomings, and be grateful for blessings. Let this awareness refine your daily conduct.',
    category: 'justice',
  },
  {
    number: 41,
    arabic: 'الْجَلِيلُ',
    transliteration: 'Al-Jalil',
    meaning: 'The Majestic',
    rootWord: 'ج-ل-ل (ja-la-la) — majesty, grandeur, awe-inspiring greatness',
    explanation: 'Al-Jalil possesses all attributes of greatness and majesty combined. He is majestic in His essence, His attributes, and His actions. His majesty inspires awe and reverence in the hearts of those who truly know Him, combining power, beauty, and perfection in absolute harmony.',
    quranRef: 'Ar-Rahman 55:27',
    quranText: 'And there will remain the Face of your Lord, Owner of Majesty and Honour.',
    benefit: 'Let the majesty of Al-Jalil fill your heart with reverence during worship. When you stand in prayer, remember you are standing before the most majestic being in existence. Let this transform your salah from routine to a deeply awe-inspiring experience.',
    category: 'beauty',
  },
  {
    number: 42,
    arabic: 'الْكَرِيمُ',
    transliteration: 'Al-Karim',
    meaning: 'The Generous',
    rootWord: 'ك-ر-م (ka-ra-ma) — generosity, nobility, honour',
    explanation: 'Al-Karim is generous in a way that gives without being asked and without expecting anything in return. His generosity has no limits and no conditions. He gives even to those who disobey Him, and when He forgives, He does so with honour, not humiliating the one who sinned.',
    quranRef: 'Al-Infitar 82:6',
    quranText: 'O mankind, what has deceived you concerning your Lord, the Generous?',
    benefit: 'Be generous as a reflection of Al-Karim\'s generosity. Give freely of your time, wealth, and kindness. Remember that the more you give for His sake, the more Al-Karim gives you in return — His generosity always exceeds yours.',
    category: 'beauty',
  },
  {
    number: 43,
    arabic: 'الرَّقِيبُ',
    transliteration: 'Ar-Raqib',
    meaning: 'The Watchful',
    rootWord: 'ر-ق-ب (ra-qa-ba) — to watch, to observe, to guard',
    explanation: 'Ar-Raqib watches every action, thought, and intention with constant vigilance. Not a single moment passes without His observation. He watches not to trap His servants but to protect them, guide them, and record their deeds with perfect accuracy for the Day of Accountability.',
    quranRef: 'Al-Ahzab 33:52',
    quranText: 'And ever is Allah, over all things, an Observer.',
    benefit: 'Develop taqwa — God-consciousness — by remembering that Ar-Raqib is always watching. Before any action, ask yourself: would I do this if I knew Allah was watching? He is. Let this awareness elevate your character in private and in public.',
    category: 'knowledge',
  },
  {
    number: 44,
    arabic: 'الْمُجِيبُ',
    transliteration: 'Al-Mujib',
    meaning: 'The Responsive',
    rootWord: 'ج-و-ب (ja-wa-ba) — to answer, to respond, to comply',
    explanation: 'Al-Mujib responds to every sincere supplication. He is close to those who call upon Him and answers their prayers in the best way — sometimes giving exactly what was asked, sometimes something better, and sometimes averting a harm they were unaware of. No dua made with sincerity is ever wasted.',
    quranRef: 'Hud 11:61',
    quranText: 'Indeed, my Lord is near and responsive.',
    benefit: 'Never stop making dua, for Al-Mujib promises to respond. If your prayer seems unanswered, know that He is responding in a way you cannot yet see — either giving you what you asked, something better, or protecting you from harm. Trust His response.',
    category: 'mercy',
  },
  {
    number: 45,
    arabic: 'الْوَاسِعُ',
    transliteration: "Al-Wasi'",
    meaning: 'The All-Encompassing',
    rootWord: 'و-س-ع (wa-si-a) — to encompass, to be vast, to contain',
    explanation: "Al-Wasi' is all-encompassing in His mercy, knowledge, and provision. His treasures never diminish, His knowledge has no limit, and His mercy extends to all creation. No matter how much He gives, His resources are never depleted. He encompasses all things with His attributes.",
    quranRef: 'Al-Baqarah 2:115',
    quranText: 'And to Allah belongs the east and the west. So wherever you turn, there is the Face of Allah. Indeed, Allah is All-Encompassing and Knowing.',
    benefit: "When your problems seem vast and overwhelming, remember that Al-Wasi' is vaster still. His solutions, His mercy, and His provision are wider than any challenge. Do not limit Allah's ability to help you by the smallness of your imagination.",
    category: 'beauty',
  },
  {
    number: 46,
    arabic: 'الْحَكِيمُ',
    transliteration: 'Al-Hakim',
    meaning: 'The Wise',
    rootWord: 'ح-ك-م (ha-ka-ma) — wisdom, judgement, placing things rightly',
    explanation: 'Al-Hakim is perfectly wise in all His decrees, laws, and actions. Everything He does has a purpose and wisdom, even when we cannot perceive it. He places everything in its perfect place and time, and there is no randomness or meaninglessness in anything He ordains.',
    quranRef: 'Al-Baqarah 2:32',
    quranText: 'They said, "Exalted are You; we have no knowledge except what You have taught us. Indeed, it is You who is the Knowing, the Wise."',
    benefit: 'When something happens that you cannot understand, trust in Al-Hakim\'s wisdom. He sees the full picture while you see only a fragment. Patience in the face of what seems senseless is an act of trust in the One whose wisdom is perfect.',
    category: 'knowledge',
  },
  {
    number: 47,
    arabic: 'الْوَدُودُ',
    transliteration: 'Al-Wadud',
    meaning: 'The Most Loving',
    rootWord: 'و-د-د (wa-da-da) — love, affection, wish',
    explanation: 'Al-Wadud loves His servants with an infinite and active love. He is not just loving — He is the Most Loving. He loves the righteous, those who repent, those who purify themselves, and those who do good. His love is expressed through His blessings, His guidance, and His mercy toward His creation.',
    quranRef: 'Al-Buruj 85:14',
    quranText: 'And He is the Forgiving, the Affectionate.',
    benefit: 'Seek the love of Al-Wadud by following what He loves — sincerity, kindness, repentance, and good deeds. Know that His love is not distant or abstract; it is active and present. When you feel alone, remember that the Most Loving One is always with you.',
    category: 'beauty',
  },
  {
    number: 48,
    arabic: 'الْمَجِيدُ',
    transliteration: 'Al-Majid',
    meaning: 'The Most Glorious',
    rootWord: 'م-ج-د (ma-ja-da) — glory, honour, nobility',
    explanation: 'Al-Majid is glorious in His essence and attributes beyond any limit. His glory is not dependent on creation\'s recognition — He is glorious in Himself. This name combines the meanings of greatness, generosity, and noble majesty, representing a glory that is both internal and manifest.',
    quranRef: 'Hud 11:73',
    quranText: 'The mercy of Allah and His blessings be upon you, O people of the house. Indeed, He is Praiseworthy and Honourable.',
    benefit: 'Glorify Al-Majid in your words, actions, and worship. The more you recognise and acknowledge His glory, the more you connect your heart to the source of all honour. Seek to live a life that reflects the glory of the One you worship.',
    category: 'beauty',
  },
  {
    number: 49,
    arabic: 'الْبَاعِثُ',
    transliteration: "Al-Ba'ith",
    meaning: 'The Resurrector',
    rootWord: 'ب-ع-ث (ba-a-tha) — to resurrect, to send forth, to awaken',
    explanation: "Al-Ba'ith is the One who will resurrect all of creation from their graves on the Day of Judgment. He sent forth prophets to awaken humanity from heedlessness, and He will raise the dead from their sleep of death. He establishes accountability by ensuring no deed goes without consequence.",
    quranRef: 'Al-Hajj 22:7',
    quranText: 'And that the Hour is coming — no doubt about it — and that Allah will resurrect those in the graves.',
    benefit: "Live with the awareness that Al-Ba'ith will raise you to account for every deed. Let this motivate you to prepare for that day — not with fear alone, but with hopeful preparation, knowing that your good deeds are being preserved for an eternal reward.",
    category: 'power',
  },
  {
    number: 50,
    arabic: 'الشَّهِيدُ',
    transliteration: 'Ash-Shahid',
    meaning: 'The Witness',
    rootWord: 'ش-ه-د (sha-hi-da) — to witness, to be present, to testify',
    explanation: 'Ash-Shahid is a witness to all things at all times and in all places. Nothing in creation occurs without His witnessing it. On the Day of Judgment, He will testify about the deeds of every soul. His testimony is absolute and requires no supporting evidence.',
    quranRef: 'Al-Ma\'idah 5:117',
    quranText: 'And You are, over all things, Witness.',
    benefit: 'When you feel that your good deeds go unnoticed by people, take comfort that Ash-Shahid witnesses everything. And when you are wronged in secret, know that He has already witnessed it and will bring it to account. No act — good or bad — is ever truly hidden.',
    category: 'knowledge',
  },
  {
    number: 51,
    arabic: 'الْحَقُّ',
    transliteration: 'Al-Haqq',
    meaning: 'The Truth',
    rootWord: 'ح-ق-ق (ha-qa-qa) — truth, reality, right',
    explanation: 'Al-Haqq is the absolute truth — His existence is necessary and eternal, unlike all else that is contingent and temporary. He is the ultimate reality upon which all other realities depend. Everything besides Him could potentially not exist, but His existence is the one certainty that anchors all of creation.',
    quranRef: 'Ta-Ha 20:114',
    quranText: 'So exalted is Allah, the Sovereign, the Truth. And do not hasten with the Quran before its revelation is completed to you, and say, "My Lord, increase me in knowledge."',
    benefit: 'In an age of confusion and falsehood, anchor yourself to Al-Haqq. Seek truth in all your affairs — truth in speech, truth in belief, truth in action. When falsehood surrounds you, hold firmly to the Quran and Sunnah, which come from the One who is Truth itself.',
    category: 'uniqueness',
  },
  {
    number: 52,
    arabic: 'الْوَكِيلُ',
    transliteration: 'Al-Wakil',
    meaning: 'The Trustee',
    rootWord: 'و-ك-ل (wa-ka-la) — to entrust, to rely upon, to delegate',
    explanation: 'Al-Wakil is the perfect trustee upon whom all affairs can be entrusted with complete confidence. He manages the affairs of those who rely on Him better than they could manage for themselves. Tawakkul (reliance on Allah) is derived from this name — it means taking the means while entrusting the outcome to Him.',
    quranRef: 'Az-Zumar 39:62',
    quranText: 'Allah is the Creator of all things, and He is, over all things, Disposer of Affairs.',
    benefit: 'Practise tawakkul by doing your best effort and then entrusting the results to Al-Wakil. This is not passivity — it is taking action while leaving the outcome to the best of planners. Say "hasbiyAllahu wa ni\'mal-Wakil" — Allah is sufficient for me and the best Disposer of Affairs.',
    category: 'sovereignty',
  },
  {
    number: 53,
    arabic: 'الْقَوِيُّ',
    transliteration: 'Al-Qawiyy',
    meaning: 'The Most Strong',
    rootWord: 'ق-و-ي (qa-wi-ya) — strength, might, power',
    explanation: 'Al-Qawiyy possesses strength that never diminishes, never tires, and can never be overcome. Unlike created strength which fluctuates and fades, His strength is eternal and perfect. He has the power to do all things, and no force in creation can resist or challenge His might.',
    quranRef: 'Al-Hajj 22:74',
    quranText: 'Indeed, Allah is the Powerful, the Exalted in Might.',
    benefit: 'When you feel weak and powerless, call upon Al-Qawiyy for strength. His strength can flow through you in ways you never imagined — giving you patience in hardship, courage in fear, and resilience in adversity. Turn to Him, and He will strengthen you.',
    category: 'power',
  },
  {
    number: 54,
    arabic: 'الْمَتِينُ',
    transliteration: 'Al-Matin',
    meaning: 'The Firm One',
    rootWord: 'م-ت-ن (ma-ta-na) — firmness, solidity, steadfastness',
    explanation: 'Al-Matin possesses an immovable and steadfast strength that never weakens or wavers. He is firm in His power, unwavering in His decree, and unshakable in His authority. This firmness means that all His actions are carried out with absolute certainty and completion.',
    quranRef: 'Az-Zariyat 51:58',
    quranText: 'Indeed, it is Allah who is the Continual Provider, the Firm Possessor of Strength.',
    benefit: 'When life shakes you and your resolve wavers, seek firmness from Al-Matin. Ask Him to make you firm in your faith, steadfast in your worship, and unwavering in your principles. The firmest foundation you can stand on is reliance on the Firm One.',
    category: 'power',
  },
  {
    number: 55,
    arabic: 'الْوَلِيُّ',
    transliteration: 'Al-Waliyy',
    meaning: 'The Protecting Friend',
    rootWord: 'و-ل-ي (wa-la-ya) — closeness, friendship, protection, guardianship',
    explanation: 'Al-Waliyy is the protecting friend and guardian who takes care of the affairs of His believing servants. He is their helper, their supporter, and their closest ally. His wilayah (friendship) is the most valuable relationship a person can have — it brings protection, guidance, and love from the Lord of all creation.',
    quranRef: 'Al-Baqarah 2:257',
    quranText: 'Allah is the Ally of those who believe. He brings them out from darknesses into the light.',
    benefit: 'Nurture your relationship with Al-Waliyy through obedience, remembrance, and voluntary good deeds. He takes special care of those who are close to Him. When you feel lonely or unsupported, remember that the greatest friend and protector you could ever have is already by your side.',
    category: 'mercy',
  },
  {
    number: 56,
    arabic: 'الْحَمِيدُ',
    transliteration: 'Al-Hamid',
    meaning: 'The Praiseworthy',
    rootWord: 'ح-م-د (ha-mi-da) — to praise, to commend, to be praiseworthy',
    explanation: 'Al-Hamid is praiseworthy in all His attributes, actions, and decrees, even if no one praised Him. His praiseworthiness is inherent and does not depend on recognition from creation. Every good thing that exists is a reason to praise Him, and the entire universe declares His praise in ways seen and unseen.',
    quranRef: 'Ibrahim 14:8',
    quranText: 'And Musa said, "If you should disbelieve, you and whoever is on the earth entirely — indeed, Allah is Free of need and Praiseworthy."',
    benefit: 'Make praising Allah a constant habit — say "Alhamdulillah" with presence and sincerity. Praise Him for what you recognise as blessings and for what you cannot yet see the wisdom in. Gratitude to Al-Hamid opens doors to more blessings.',
    category: 'beauty',
  },
  {
    number: 57,
    arabic: 'الْمُحْصِي',
    transliteration: 'Al-Muhsi',
    meaning: 'The Accounter',
    rootWord: 'ح-ص-ي (ha-sa-ya) — to count, to enumerate, to record precisely',
    explanation: 'Al-Muhsi counts and records everything with perfect precision. Not a single atom moves without being counted, not a single deed goes unrecorded. He has enumerated all of creation and knows the exact number of every star, every leaf, every grain of sand, and every breath taken by every creature.',
    quranRef: 'Maryam 19:94',
    quranText: 'He has enumerated them and counted them a full counting.',
    benefit: 'Since Al-Muhsi records every deed with precision, let no good deed seem too small to perform and no sin seem too small to avoid. Every act matters in His count. Use this awareness to motivate consistency in small daily acts of worship.',
    category: 'knowledge',
  },
  {
    number: 58,
    arabic: 'الْمُبْدِئُ',
    transliteration: "Al-Mubdi'",
    meaning: 'The Originator',
    rootWord: 'ب-د-أ (ba-da-a) — to begin, to originate, to initiate',
    explanation: "Al-Mubdi' originates existence from absolute nothing — creating without any prior model, material, or template. He initiated creation for the first time, bringing all things into being from non-existence. This demonstrates His absolute power, for only He can bring something from nothing.",
    quranRef: 'Al-Buruj 85:13',
    quranText: 'Indeed, it is He who originates creation and repeats it.',
    benefit: "When starting something new — a project, a journey, a chapter of life — invoke Al-Mubdi' and ask Him to bless your beginning. The One who originated all of creation from nothing can certainly help you begin something meaningful.",
    category: 'creation',
  },
  {
    number: 59,
    arabic: 'الْمُعِيدُ',
    transliteration: "Al-Mu'id",
    meaning: 'The Restorer',
    rootWord: 'ع-و-د (a-wa-da) — to return, to restore, to repeat',
    explanation: "Al-Mu'id restores and returns all of creation after its death and annihilation. He will resurrect every soul for the Day of Judgment. The One who created the first time can easily restore — indeed, restoration is even easier for Him, though nothing is difficult for Allah.",
    quranRef: 'Al-Buruj 85:13',
    quranText: 'Indeed, it is He who originates creation and repeats it.',
    benefit: "When you lose something precious — health, wealth, a loved one, or even your spiritual motivation — turn to Al-Mu'id to restore what was lost. He has the power to bring back what is gone and to renew what has faded.",
    category: 'creation',
  },
  {
    number: 60,
    arabic: 'الْمُحْيِي',
    transliteration: 'Al-Muhyi',
    meaning: 'The Giver of Life',
    rootWord: 'ح-ي-ي (ha-ya-ya) — to live, to give life, to revive',
    explanation: 'Al-Muhyi gives life to the dead and brings dead hearts back to spiritual life through faith and guidance. He sends rain to revive dead earth, brings babies to life in the womb, and will resurrect all of creation on the Last Day. Both physical and spiritual life come solely from Him.',
    quranRef: 'Ya-Sin 36:78-79',
    quranText: 'Say, "He will give them life who produced them the first time; and He is, of all creation, Knowing."',
    benefit: 'When your heart feels spiritually dead, call upon Al-Muhyi to revive it. Just as He sends rain to bring a barren land back to life, He can send guidance and light to a heart that has grown hard. Never give up on spiritual renewal.',
    category: 'creation',
  },
  {
    number: 61,
    arabic: 'اَلْمُمِيتُ',
    transliteration: 'Al-Mumit',
    meaning: 'The Taker of Life',
    rootWord: 'م-و-ت (ma-wa-ta) — death, to die, to cause to die',
    explanation: 'Al-Mumit causes death, which is not an annihilation but a transition from one state of existence to another. Death is part of His divine plan — a mercy in that it ends worldly suffering and moves the soul to the next stage of its journey. All living things will taste death by His decree.',
    quranRef: 'Al-A\'raf 7:158',
    quranText: 'There is no deity except Him; He gives life and causes death.',
    benefit: 'Remember death regularly — not to be morbid, but to live with purpose. Knowing that Al-Mumit has appointed a time for every soul motivates you to make every moment count. Prepare for the inevitable meeting with your Lord by doing good today.',
    category: 'power',
  },
  {
    number: 62,
    arabic: 'الْحَيُّ',
    transliteration: 'Al-Hayy',
    meaning: 'The Ever Living',
    rootWord: 'ح-ي-ي (ha-ya-ya) — to live, life, eternal existence',
    explanation: 'Al-Hayy is eternally alive with a life that had no beginning and will have no end. His life is perfect and self-sustaining, unlike the life of creation which depends on Him. Everything in creation will perish, but Al-Hayy remains forever — the source of all life and the last reality standing.',
    quranRef: 'Al-Baqarah 2:255',
    quranText: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence.',
    benefit: 'When you lose someone dear, remember that Al-Hayy never dies and never leaves you. Attach your heart to the Ever-Living rather than to mortal creation. Call upon "Ya Hayyu Ya Qayyum" in your dua — it is among the greatest names of Allah.',
    category: 'uniqueness',
  },
  {
    number: 63,
    arabic: 'الْقَيُّومُ',
    transliteration: 'Al-Qayyum',
    meaning: 'The Self-Existing',
    rootWord: 'ق-و-م (qa-wa-ma) — to stand, to sustain, to maintain',
    explanation: 'Al-Qayyum is self-subsisting and sustains all of existence. He does not depend on anything, while everything depends entirely on Him. Without Al-Qayyum sustaining the universe at every moment, nothing could continue to exist. He maintains the heavens, the earth, and everything in between.',
    quranRef: 'Al-Baqarah 2:255',
    quranText: 'Allah — there is no deity except Him, the Ever-Living, the Sustainer of existence. Neither drowsiness overtakes Him nor sleep.',
    benefit: 'Trust that Al-Qayyum is sustaining your life and your affairs at every moment, even when you sleep. You cannot sustain yourself — but the One who sustains the entire universe is taking care of you. Let this relieve the burden of trying to control everything.',
    category: 'uniqueness',
  },
  {
    number: 64,
    arabic: 'الْوَاجِدُ',
    transliteration: 'Al-Wajid',
    meaning: 'The Finder',
    rootWord: 'و-ج-د (wa-ja-da) — to find, to possess, to have wealth',
    explanation: 'Al-Wajid finds whatever He wills, and nothing escapes Him. He possesses infinite wealth and resources, lacking nothing whatsoever. Nothing He seeks is ever lost to Him, and He is self-sufficient in all things. His finding is not like creation\'s searching — He knows and possesses all things effortlessly.',
    quranRef: 'Ad-Duha 93:6-8',
    quranText: 'Did He not find you an orphan and give you refuge? And He found you lost and guided you. And He found you poor and made you self-sufficient.',
    benefit: 'When you feel lost, remember that Al-Wajid found the Prophet (peace be upon him) as an orphan and gave him refuge. He can find you in your darkness and guide you to light. Nothing is lost to Him — including you.',
    category: 'sovereignty',
  },
  {
    number: 65,
    arabic: 'الْمَاجِدُ',
    transliteration: 'Al-Majid',
    meaning: 'The Glorious',
    rootWord: 'م-ج-د (ma-ja-da) — glory, nobility, generosity',
    explanation: 'Al-Majid is noble and generous, combining both glory and boundless generosity. His glory manifests in the perfection of His attributes, and His generosity flows without limit to all of creation. He is glorious in what He is and generous in what He gives.',
    quranRef: 'Al-Buruj 85:15',
    quranText: 'Owner of the Throne, the Glorious.',
    benefit: 'Reflect on the glory and generosity of Al-Majid to cultivate a spirit of giving in your own life. True nobility comes from being generous with what Allah has given you — your time, your knowledge, your wealth, and your kindness.',
    category: 'beauty',
  },
  {
    number: 66,
    arabic: 'الْوَاحِدُ',
    transliteration: 'Al-Wahid',
    meaning: 'The One',
    rootWord: 'و-ح-د (wa-ha-da) — to be one, uniqueness, singularity',
    explanation: 'Al-Wahid is one in His essence — without partner, without division, without equal. His oneness means there is no other deity deserving of worship, no other creator, and no other sustainer. Tawheed (monotheism) — the core of Islam — is built upon the reality of this divine name.',
    quranRef: 'As-Saffat 37:4',
    quranText: 'Indeed, your God is One.',
    benefit: 'Purify your tawheed by directing all worship, reliance, hope, and fear to Al-Wahid alone. Do not give any created thing the devotion that belongs solely to Him. The simplicity and purity of worshipping One God frees your heart from the confusion of competing loyalties.',
    category: 'uniqueness',
  },
  {
    number: 67,
    arabic: 'اَلاَحَدُ',
    transliteration: 'Al-Ahad',
    meaning: 'The Unique',
    rootWord: 'أ-ح-د (a-ha-da) — unique, absolute oneness',
    explanation: 'Al-Ahad is uniquely one — with no equal, no comparison, and no resemblance to anything in creation. While Al-Wahid affirms His numerical oneness, Al-Ahad affirms His absolute uniqueness — there is nothing whatsoever like Him. He is in a category entirely His own.',
    quranRef: 'Al-Ikhlas 112:1',
    quranText: 'Say, "He is Allah, the One."',
    benefit: 'Recite Surah Al-Ikhlas frequently, which begins with Al-Ahad. It equals one-third of the Quran in meaning. Let the uniqueness of Allah liberate you from comparing Him to anything in creation — His reality is beyond all human categories and analogies.',
    category: 'uniqueness',
  },
  {
    number: 68,
    arabic: 'الصَّمَدُ',
    transliteration: 'As-Samad',
    meaning: 'The Eternal',
    rootWord: 'ص-م-د (sa-ma-da) — to be eternal, self-sufficient, refuge for all',
    explanation: 'As-Samad is the eternal refuge whom all creation turns to in need, while He Himself needs nothing and no one. He is the One all beings depend upon — for sustenance, protection, guidance, and relief. He is perfect and complete, with no need or deficiency. All needs are directed to Him.',
    quranRef: 'Al-Ikhlas 112:2',
    quranText: 'Allah, the Eternal Refuge.',
    benefit: 'When in any need — great or small — turn to As-Samad, the eternal refuge. He is never too busy, never tired, and never unable to help. Unlike creation, He is always available and always capable. Make Him your first resort, not your last.',
    category: 'uniqueness',
  },
  {
    number: 69,
    arabic: 'الْقَادِرُ',
    transliteration: 'Al-Qadir',
    meaning: 'The Able',
    rootWord: 'ق-د-ر (qa-da-ra) — to be able, power, capability',
    explanation: 'Al-Qadir has absolute power over everything — nothing is impossible for Him. He simply says "Be" and it is. His power is not like created power that requires effort or resources; it is absolute, effortless, and complete. He can do whatever He wills without limitation.',
    quranRef: 'Al-Kahf 18:45',
    quranText: 'And Allah is ever, over all things, Perfect in Ability.',
    benefit: 'When you face the impossible, remember that nothing is impossible for Al-Qadir. He can change your situation in an instant. Make dua with conviction, knowing that the One you are calling upon has power over all things without exception.',
    category: 'power',
  },
  {
    number: 70,
    arabic: 'الْمُقْتَدِرُ',
    transliteration: 'Al-Muqtadir',
    meaning: 'The Powerful',
    rootWord: 'ق-د-ر (qa-da-ra) — all-encompassing power, absolute ability',
    explanation: 'Al-Muqtadir possesses all-encompassing power that cannot be challenged, resisted, or escaped. While Al-Qadir emphasises the ability to do all things, Al-Muqtadir emphasises the irresistible and overwhelming nature of that power. No force in all of creation can stand against His decree.',
    quranRef: 'Al-Qamar 54:42',
    quranText: 'They denied all Our signs, so We seized them with a seizure of one Exalted in Might and Perfect in Ability.',
    benefit: 'Take comfort that Al-Muqtadir\'s power stands behind every promise He has made. When He promises reward for the righteous and justice for the oppressed, His power guarantees fulfilment. Trust in His promises with absolute certainty.',
    category: 'power',
  },
  {
    number: 71,
    arabic: 'الْمُقَدِّمُ',
    transliteration: 'Al-Muqaddim',
    meaning: 'The Expediter',
    rootWord: 'ق-د-م (qa-da-ma) — to bring forward, to advance, to precede',
    explanation: 'Al-Muqaddim brings forward whom He wills in rank, time, or favour. He advances certain people over others in knowledge, piety, provision, or status according to His perfect wisdom. What He brings forward cannot be held back by any force.',
    quranRef: 'Qaf 50:28',
    quranText: 'He will say, "Do not dispute before Me, while I had already presented to you the warning."',
    benefit: 'When your progress seems delayed while others advance, trust Al-Muqaddim\'s timing. He brings forward at the right moment, not too early and not too late. Focus on doing your best, and leave the timing of your advancement to His perfect wisdom.',
    category: 'sovereignty',
  },
  {
    number: 72,
    arabic: 'الْمُؤَخِّرُ',
    transliteration: "Al-Mu'akhkhir",
    meaning: 'The Delayer',
    rootWord: 'أ-خ-ر (a-kha-ra) — to delay, to postpone, to put behind',
    explanation: "Al-Mu'akhkhir delays what He wills by divine wisdom. He postpones punishment to give time for repentance, delays rewards to test patience, and holds back what is not yet right in its timing. Every delay has a purpose known to the All-Wise.",
    quranRef: 'Nuh 71:4',
    quranText: 'He will forgive you of your sins and delay you for a specified term.',
    benefit: "When something you desperately want is delayed, remember Al-Mu'akhkhir delays for your benefit. The delay may be protecting you from something harmful, or preparing something better. Be patient and trust that His timing is always perfect.",
    category: 'sovereignty',
  },
  {
    number: 73,
    arabic: 'الأوَّلُ',
    transliteration: 'Al-Awwal',
    meaning: 'The First',
    rootWord: 'أ-و-ل (a-wa-la) — first, beginning, primacy',
    explanation: 'Al-Awwal is the First — He existed before all of creation, before time itself, before anything was. There was nothing before Him. His existence has no beginning, and He is the origin from which all of existence sprang. Everything starts with Him.',
    quranRef: 'Al-Hadid 57:3',
    quranText: 'He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing.',
    benefit: 'Reflecting on Al-Awwal puts everything in perspective — before the universe, before time, before anything, there was Allah. When you begin any undertaking, start with His name and seek His guidance, for all good beginnings trace back to the First.',
    category: 'uniqueness',
  },
  {
    number: 74,
    arabic: 'الآخِرُ',
    transliteration: 'Al-Akhir',
    meaning: 'The Last',
    rootWord: 'أ-خ-ر (a-kha-ra) — last, final, remaining',
    explanation: 'Al-Akhir is the Last — He will remain after all of creation ceases to exist. When every star has burned out, every soul has passed, and every world has ended, He alone will remain. His existence has no end, just as it has no beginning.',
    quranRef: 'Al-Hadid 57:3',
    quranText: 'He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing.',
    benefit: 'Since everything in this world is temporary but Al-Akhir is eternal, invest in what lasts — your relationship with Allah and your good deeds. The things you send forth for the Hereafter are the only things that will remain when everything else fades.',
    category: 'uniqueness',
  },
  {
    number: 75,
    arabic: 'الظَّاهِرُ',
    transliteration: 'Az-Zahir',
    meaning: 'The Manifest',
    rootWord: 'ظ-ه-ر (dha-ha-ra) — to appear, to be manifest, to be evident',
    explanation: 'Az-Zahir is the Manifest — His existence is evident and clear through the signs of His creation. The heavens, the earth, the order of the universe, and the miracle of life all point clearly to Him. Though His essence cannot be seen in this world, His presence is more evident than anything else.',
    quranRef: 'Al-Hadid 57:3',
    quranText: 'He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing.',
    benefit: 'Train your eyes to see Az-Zahir\'s signs everywhere — in the sunrise, in the rain, in the growth of a seed, in the beating of your heart. The more you look, the more you see Him manifest in everything around you.',
    category: 'uniqueness',
  },
  {
    number: 76,
    arabic: 'الْبَاطِنُ',
    transliteration: 'Al-Batin',
    meaning: 'The Hidden',
    rootWord: 'ب-ط-ن (ba-ta-na) — to be hidden, inner, concealed',
    explanation: 'Al-Batin is the Hidden — His essence cannot be perceived by human senses in this world. While His signs are manifest, His true nature is beyond our comprehension. This name teaches humility before the divine mystery — we know He exists with certainty, but we cannot fully grasp what He is.',
    quranRef: 'Al-Hadid 57:3',
    quranText: 'He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing.',
    benefit: 'Accept that Al-Batin\'s essence is beyond your perception and do not try to imagine or define Him. Faith in the unseen is one of the first qualities of the believers mentioned in the Quran. Embrace the mystery and let it deepen your awe.',
    category: 'uniqueness',
  },
  {
    number: 77,
    arabic: 'الْوَالِي',
    transliteration: 'Al-Wali',
    meaning: 'The Governor',
    rootWord: 'و-ل-ي (wa-la-ya) — to govern, to manage, to take charge of',
    explanation: 'Al-Wali is the governing patron who manages all affairs of creation. He is in charge of everything — the movements of the planets, the rising and setting of the sun, the growth of crops, and the fate of nations. Nothing in the universe operates independently of His governance.',
    quranRef: "Ar-Ra'd 13:11",
    quranText: 'Indeed, Allah will not change the condition of a people until they change what is in themselves.',
    benefit: 'While Al-Wali governs all affairs, He also gives you the ability to change your own condition through your choices. Take responsibility for your actions while trusting that the ultimate governance of all things rests with Him.',
    category: 'sovereignty',
  },
  {
    number: 78,
    arabic: 'الْمُتَعَالِي',
    transliteration: "Al-Muta'ali",
    meaning: 'The Most Exalted',
    rootWord: 'ع-ل-و (a-la-wa) — to be exalted, to transcend, to be supreme',
    explanation: "Al-Muta'ali is transcendently above all — above every attribute, description, and limitation that creation might try to place on Him. He is beyond space, beyond time, and beyond every concept of human imagination. His exaltation means that no thought can reach the reality of His majesty.",
    quranRef: "Ar-Ra'd 13:9",
    quranText: 'The Knower of the unseen and the witnessed, the Grand, the Exalted.',
    benefit: "When people try to limit Allah by their limited understanding, remember Al-Muta'ali transcends all human categories. Do not confine your understanding of Allah to your own limited perspective. He is greater than anything you can imagine.",
    category: 'sovereignty',
  },
  {
    number: 79,
    arabic: 'الْبَرُّ',
    transliteration: 'Al-Barr',
    meaning: 'The Source of Goodness',
    rootWord: 'ب-ر-ر (ba-ra-ra) — goodness, righteousness, kindness',
    explanation: 'Al-Barr is the source of all goodness and righteousness. He is kind and benevolent to His creation, showering them with blessings and dealing with them gently. All good things in existence flow from His goodness, and He inspires and rewards righteousness in His servants.',
    quranRef: 'At-Tur 52:28',
    quranText: 'Indeed, we used to supplicate Him before. Indeed, it is He who is the Beneficent, the Merciful.',
    benefit: 'Seek goodness from Al-Barr — the source of all that is good. Treat your parents with birr (goodness), for it is named after this divine attribute. When you practise righteousness, you are reflecting a quality that originates with Him.',
    category: 'mercy',
  },
  {
    number: 80,
    arabic: 'التَّوَّابُ',
    transliteration: 'At-Tawwab',
    meaning: 'The Acceptor of Repentance',
    rootWord: 'ت-و-ب (ta-wa-ba) — to repent, to turn back, to accept repentance',
    explanation: 'At-Tawwab accepts repentance repeatedly, always, and at any time. He not only accepts repentance but actively turns the hearts of His servants toward repentance in the first place. He loves the act of repentance and is overjoyed when a servant returns to Him, no matter how many times they have strayed.',
    quranRef: 'At-Tawbah 9:104',
    quranText: 'Do they not know that it is Allah who accepts repentance from His servants and receives charities and that it is Allah who is the Accepting of repentance, the Merciful?',
    benefit: 'No matter how many times you fall, return to At-Tawwab immediately. He never tires of forgiving, so never tire of repenting. The door of tawbah is open day and night — walk through it as often as you need to, for He is waiting with open arms.',
    category: 'mercy',
  },
  {
    number: 81,
    arabic: 'الْمُنْتَقِمُ',
    transliteration: 'Al-Muntaqim',
    meaning: 'The Avenger',
    rootWord: 'ن-ق-م (na-qa-ma) — to take retribution, to avenge, to punish justly',
    explanation: 'Al-Muntaqim takes just retribution from persistent oppressors and those who wilfully reject truth after it has been made clear to them. His retribution is not like human vengeance — it is measured, just, and comes only after extensive warning and opportunity to repent.',
    quranRef: 'As-Sajdah 32:22',
    quranText: 'And who is more unjust than one who is reminded of the verses of his Lord; then he turns away from them? Indeed We, from the criminals, will take retribution.',
    benefit: 'Fear Al-Muntaqim by avoiding oppression and injustice in all its forms. If you have wronged someone, make amends before His retribution arrives. And if you have been wronged, leave the matter with Him — the Avenger will take your right in full.',
    category: 'justice',
  },
  {
    number: 82,
    arabic: 'العَفُوُّ',
    transliteration: 'Al-Afuww',
    meaning: 'The Pardoner',
    rootWord: 'ع-ف-و (a-fa-wa) — to pardon, to erase, to wipe away completely',
    explanation: 'Al-Afuww pardons completely — not just forgiving the sin but erasing it as if it never happened. While Al-Ghafur forgives and covers sins, Al-Afuww goes further by wiping them away entirely. This is the name the Prophet (peace be upon him) taught Aisha to call upon in Laylatul Qadr.',
    quranRef: 'An-Nisa 4:99',
    quranText: 'For those it is expected that Allah will pardon them, and Allah is ever Pardoning and Forgiving.',
    benefit: 'Make the dua "Allahumma innaka afuwwun tuhibbul afwa fa\'fu anni" — O Allah, You are the Pardoner, You love pardoning, so pardon me. Especially in the last ten nights of Ramadan, call upon Al-Afuww to completely erase your sins.',
    category: 'mercy',
  },
  {
    number: 83,
    arabic: 'الرَّؤُوفُ',
    transliteration: "Ar-Ra'uf",
    meaning: 'The Most Kind',
    rootWord: 'ر-أ-ف (ra-a-fa) — tenderness, compassion, gentle kindness',
    explanation: "Ar-Ra'uf is extremely compassionate and tender with His servants. His kindness is gentler and more tender than even rahma (mercy). He lightens burdens, eases difficulties, and deals with His creation with extraordinary tenderness — especially with the believers who strive to obey Him.",
    quranRef: 'Al-Baqarah 2:143',
    quranText: 'Indeed Allah is, to the people, Kind and Merciful.',
    benefit: "When the weight of life feels heavy, remember that Ar-Ra'uf is tender and compassionate toward you. He does not burden a soul beyond what it can bear. His kindness surrounds you even in your hardest moments — look for it, and you will find it.",
    category: 'mercy',
  },
  {
    number: 84,
    arabic: 'مَالِكُ الْمُلْكِ',
    transliteration: 'Malik-ul-Mulk',
    meaning: 'Owner of Sovereignty',
    rootWord: 'م-ل-ك (ma-la-ka) — sovereignty, dominion, ownership',
    explanation: 'Malik-ul-Mulk is the possessor of all dominion and sovereignty. He gives and takes kingdoms as He wills. All authority, power, and rulership in the universe belong to Him, and He delegates temporarily to whomever He chooses. No kingdom lasts forever except His.',
    quranRef: 'Ali Imran 3:26',
    quranText: 'Say, "O Allah, Owner of Sovereignty, You give sovereignty to whom You will and You take sovereignty away from whom You will."',
    benefit: 'Do not be awed by worldly power, for all sovereignty belongs to Malik-ul-Mulk. Rulers rise and fall by His decree. Seek His favour rather than the favour of those in power, for their authority is borrowed and temporary.',
    category: 'sovereignty',
  },
  {
    number: 85,
    arabic: 'ذُوالْجَلَالِ وَالإكْرَامِ',
    transliteration: 'Dhul-Jalali Wal-Ikram',
    meaning: 'Lord of Majesty & Bounty',
    rootWord: 'ج-ل-ل / ك-ر-م (jalal — majesty; ikram — honour, generosity)',
    explanation: 'Dhul-Jalali Wal-Ikram is the possessor of both majesty and honour, combining awe-inspiring greatness with overwhelming generosity. His majesty inspires reverence, and His generosity inspires hope. These two qualities together — jalal and ikram — encompass the full relationship between servant and Lord.',
    quranRef: 'Ar-Rahman 55:27',
    quranText: 'And there will remain the Face of your Lord, Owner of Majesty and Honour.',
    benefit: 'The Prophet (peace be upon him) encouraged making much dua using "Ya Dhal-Jalali wal-Ikram." Combine reverent awe of His majesty with confident hope in His generosity. This balance — between fear and hope — is the heart of a healthy relationship with Allah.',
    category: 'beauty',
  },
  {
    number: 86,
    arabic: 'الْمُقْسِطُ',
    transliteration: 'Al-Muqsit',
    meaning: 'The Equitable',
    rootWord: 'ق-س-ط (qa-sa-ta) — equity, fairness, balance',
    explanation: 'Al-Muqsit establishes equity and balance in all affairs. He ensures that every soul receives exactly what it is due — in reward and in consequence. His equity is perfect, considering every circumstance, intention, and factor. He loves those who are just and fair in their dealings.',
    quranRef: 'Al-Mumtahana 60:8',
    quranText: 'Indeed, Allah loves those who act justly.',
    benefit: 'Strive to be just and equitable in all your dealings, reflecting the attribute of Al-Muqsit. Be fair with family, friends, colleagues, and even those you disagree with. Justice is beloved to Allah, and those who practise it will be on pulpits of light on the Day of Judgment.',
    category: 'justice',
  },
  {
    number: 87,
    arabic: 'الْجَامِعُ',
    transliteration: "Al-Jami'",
    meaning: 'The Gatherer',
    rootWord: 'ج-م-ع (ja-ma-a) — to gather, to collect, to bring together',
    explanation: "Al-Jami' gathers all of creation together on the Day of Judgment — a gathering from which no soul can escape. He also gathers what is scattered, unites what is divided, and brings together opposing things in perfect harmony. He gathers the hearts of the believers in brotherhood and faith.",
    quranRef: 'Ali Imran 3:9',
    quranText: 'Our Lord, surely You will gather the people for a Day about which there is no doubt. Indeed, Allah does not fail in His promise.',
    benefit: "When separated from loved ones — by distance, by conflict, or by death — ask Al-Jami' to reunite you. And prepare for the great gathering on the Day of Judgment, when every soul will stand before its Lord. Make sure your deeds will speak well for you on that day.",
    category: 'power',
  },
  {
    number: 88,
    arabic: 'الْغَنِيُّ',
    transliteration: 'Al-Ghani',
    meaning: 'The Self-Sufficient',
    rootWord: 'غ-ن-ي (gha-ni-ya) — to be rich, self-sufficient, independent',
    explanation: 'Al-Ghani is completely independent and self-sufficient, needing absolutely nothing from His creation. He does not need our worship, our gratitude, or our obedience — rather, it is we who need Him in every moment. His self-sufficiency is absolute, and all of creation\'s worship adds nothing to His sovereignty.',
    quranRef: 'Al-Ankabut 29:6',
    quranText: 'Indeed, Allah is free from need of the worlds.',
    benefit: 'Your worship of Al-Ghani benefits you, not Him. This awareness should fill your worship with humility and gratitude — He commands you to pray, fast, and give not because He needs it, but because you need it. Seek richness of soul through closeness to the Self-Sufficient.',
    category: 'uniqueness',
  },
  {
    number: 89,
    arabic: 'الْمُغْنِي',
    transliteration: 'Al-Mughni',
    meaning: 'The Enricher',
    rootWord: 'غ-ن-ي (gha-na-ya) — to enrich, to make self-sufficient',
    explanation: 'Al-Mughni enriches from His own infinite treasure, making rich those whom He wills. He enriches not only with material wealth but with contentment, faith, knowledge, and inner peace. True richness — ghina — is richness of the soul, and only Al-Mughni can grant it.',
    quranRef: 'At-Tawbah 9:28',
    quranText: 'And if you fear poverty, Allah will enrich you from His bounty if He wills.',
    benefit: 'Ask Al-Mughni for true richness — contentment of the heart. The Prophet (peace be upon him) said, "Richness is not in having many possessions, but richness is the richness of the soul." Seek spiritual wealth alongside material provision.',
    category: 'mercy',
  },
  {
    number: 90,
    arabic: 'اَلْمَانِعُ',
    transliteration: "Al-Mani'",
    meaning: 'The Preventer',
    rootWord: 'م-ن-ع (ma-na-a) — to prevent, to withhold, to protect',
    explanation: "Al-Mani' withholds by wisdom, preventing what would be harmful and protecting believers from danger. What He withholds is not taken in cruelty but in protection. Sometimes the best thing that can happen to you is the door that stays closed — Al-Mani' closes it to protect you from what lies behind it.",
    quranRef: 'Al-Fatihah 1:5',
    quranText: 'It is You we worship and You we ask for help.',
    benefit: "When something you want is withheld from you, consider that Al-Mani' may be protecting you from harm you cannot see. Not getting what you want is sometimes the greatest blessing. Trust His withholding as much as you trust His giving.",
    category: 'sovereignty',
  },
  {
    number: 91,
    arabic: 'الضَّارَّ',
    transliteration: 'Ad-Darr',
    meaning: 'The Distresser',
    rootWord: 'ض-ر-ر (da-ra-ra) — to harm, to afflict, to cause distress',
    explanation: 'Ad-Darr is the One by whose permission harm and distress can afflict a person. No harm comes to anyone except by His decree. This name is always paired with An-Nafi\' — together they teach that both harm and benefit come from Allah alone, and no one else has the power to afflict or benefit independently.',
    quranRef: 'Al-An\'am 6:17',
    quranText: 'And if Allah should touch you with adversity, there is no remover of it except Him.',
    benefit: 'Do not fear any person\'s ability to harm you independently of Allah\'s will. Ad-Darr reminds you that nothing can touch you except by His permission. This frees you from fear of creation and directs you to seek protection only from Him.',
    category: 'power',
  },
  {
    number: 92,
    arabic: 'النَّافِعُ',
    transliteration: "An-Nafi'",
    meaning: 'The Benefiter',
    rootWord: 'ن-ف-ع (na-fa-a) — benefit, profit, advantage',
    explanation: "An-Nafi' is the One from whom all benefit ultimately comes. No person, medicine, or strategy can truly benefit you except by His permission. He is the source of every good outcome, every healing, and every success. All beneficial things in creation are channels through which His benefit flows.",
    quranRef: 'Al-An\'am 6:17',
    quranText: 'And if He intends for you good, there is no repeller of His bounty.',
    benefit: "Seek benefit from An-Nafi' while taking the means He has provided. Use medicine while asking Him for healing. Make efforts while asking Him for success. The means are important, but the true benefit comes only from Him.",
    category: 'mercy',
  },
  {
    number: 93,
    arabic: 'النُّورُ',
    transliteration: 'An-Nur',
    meaning: 'The Light',
    rootWord: 'ن-و-ر (na-wa-ra) — light, illumination, radiance',
    explanation: 'An-Nur is the Light of the heavens and the earth. He illuminates the universe with physical light and illuminates hearts with the light of faith and guidance. Without His light, there would be nothing but darkness — both literal and spiritual. The famous "Light Verse" (Ayat an-Nur) describes His light with a beautiful parable.',
    quranRef: 'An-Nur 24:35',
    quranText: 'Allah is the Light of the heavens and the earth. The example of His light is like a niche within which is a lamp, the lamp is within glass, the glass as if it were a pearly white star.',
    benefit: 'Ask An-Nur to illuminate your heart with faith, your mind with knowledge, and your path with guidance. When confusion and darkness surround you, seek His light through the Quran, sincere dua, and the company of the righteous.',
    category: 'beauty',
  },
  {
    number: 94,
    arabic: 'الْهَادِي',
    transliteration: 'Al-Hadi',
    meaning: 'The Guide',
    rootWord: 'ه-د-ي (ha-da-ya) — to guide, guidance, to show the way',
    explanation: 'Al-Hadi guides whom He wills to the truth, to the straight path, and to what benefits them in this life and the next. He guides in many ways — through revelation, through prophets, through signs in creation, and through the light He places in the heart of the believer.',
    quranRef: 'Al-Furqan 25:31',
    quranText: 'And sufficient is your Lord as a Guide and a Helper.',
    benefit: 'Ask Al-Hadi for guidance in every decision — large and small. Pray salat al-istikhara when facing choices, and recite "Ihdinas-siratal-mustaqeem" in Al-Fatihah with full attention, for you are asking the Guide to guide you at least 17 times every day.',
    category: 'mercy',
  },
  {
    number: 95,
    arabic: 'الْبَدِيعُ',
    transliteration: "Al-Badi'",
    meaning: 'The Originator',
    rootWord: 'ب-د-ع (ba-da-a) — to originate without precedent, to innovate',
    explanation: "Al-Badi' is the originator who creates with no prior model, no precedent, and no template. He innovates in ways no mind can conceive, bringing into existence things that never existed before — not even as concepts. The diversity and beauty of creation testifies to His limitless creative originality.",
    quranRef: 'Al-Baqarah 2:117',
    quranText: 'Originator of the heavens and the earth. When He decrees a matter, He only says to it, "Be," and it is.',
    benefit: "Look at the creative diversity in nature — from the depths of the ocean to the farthest stars — and appreciate Al-Badi's boundless originality. Let this inspire you to be creative and innovative in beneficial ways, while always acknowledging that true creativity belongs to Him.",
    category: 'creation',
  },
  {
    number: 96,
    arabic: 'اَلْبَاقِي',
    transliteration: 'Al-Baqi',
    meaning: 'The Everlasting',
    rootWord: 'ب-ق-ي (ba-qi-ya) — to remain, to endure, to be everlasting',
    explanation: 'Al-Baqi is everlasting — everything perishes except His face. While all of creation is temporary and subject to decay, He alone endures forever. This name reminds us of the transience of this world and the permanence of the Hereafter. Only what is done for His sake truly lasts.',
    quranRef: 'Al-Qasas 28:88',
    quranText: 'Everything will be destroyed except His Face. His is the judgement, and to Him you will be returned.',
    benefit: 'Do not attach your heart to what is temporary, for only Al-Baqi is permanent. Invest in your relationship with the Everlasting and in deeds that endure — good works, knowledge, and ongoing charity. These are the things that outlast your worldly life.',
    category: 'uniqueness',
  },
  {
    number: 97,
    arabic: 'الْوَارِثُ',
    transliteration: 'Al-Warith',
    meaning: 'The Inheritor',
    rootWord: 'و-ر-ث (wa-ri-tha) — to inherit, to be the heir',
    explanation: 'Al-Warith is the true inheritor of all things — everything returns to Him after all of creation perishes. Every possession, every kingdom, every life ultimately reverts to its original Owner. He inherits the heavens and the earth and all that is between them.',
    quranRef: 'Al-Hijr 15:23',
    quranText: 'And indeed, it is We who give life and cause death, and We are the Inheritor.',
    benefit: 'Since Al-Warith inherits everything, use what you have been given wisely before it returns to Him. Your wealth, your time, your health — they are all temporary trusts. Invest them in pleasing Him, for the true Owner will reclaim them all.',
    category: 'sovereignty',
  },
  {
    number: 98,
    arabic: 'الرَّشِيدُ',
    transliteration: 'Ar-Rashid',
    meaning: 'The Guide to the Right Path',
    rootWord: 'ر-ش-د (ra-sha-da) — right guidance, wisdom, correct direction',
    explanation: 'Ar-Rashid guides to the right and wise course of action. He directs affairs with perfect wisdom toward their best outcomes. His guidance leads to what is truly beneficial, not just what seems good on the surface. He is the ultimate source of sound direction and wise counsel.',
    quranRef: 'Al-Kahf 18:10',
    quranText: 'Our Lord, grant us from Yourself mercy and prepare for us from our affair right guidance.',
    benefit: 'When facing a decision and unsure of the right path, ask Ar-Rashid for rushd — right guidance. The young people of the cave asked for this, and Allah guided them miraculously. Trust that He can guide you through even the most confusing circumstances.',
    category: 'knowledge',
  },
  {
    number: 99,
    arabic: 'الصَّبُورُ',
    transliteration: 'As-Sabur',
    meaning: 'The Patient',
    rootWord: 'ص-ب-ر (sa-ba-ra) — patience, endurance, perseverance',
    explanation: 'As-Sabur is the most patient — He delays punishment out of mercy, not out of inability. He gives His servants time to repent, chances to change, and opportunities to return to Him. His patience with sinful humanity is beyond comprehension, for He sees every disobedience yet continues to provide and bless.',
    quranRef: 'Al-Baqarah 2:153',
    quranText: 'O you who have believed, seek help through patience and prayer. Indeed, Allah is with the patient.',
    benefit: 'Learn patience from As-Sabur. When provoked, remember that Allah is patient with your own sins and shortcomings. When tested, know that patience is the path to His companionship — for "indeed, Allah is with the patient." Cultivate sabr as one of the highest virtues.',
    category: 'beauty',
  },
]
