// ─── Fiqh Data ─────────────────────────────────────────────────────────────
// Source: Al Fiqh-ul Muyassar (Maulana Shafeequr Rahman An-Nadvi)
// Madhab: Hanafi (predominant in Guyana)
// ────────────────────────────────────────────────────────────────────────────

export interface FiqhHadith {
  arabic: string
  transliteration?: string
  translation: string
  source: string
}

export interface FiqhExample {
  scenario: string
  ruling: string
}

export interface FiqhTopic {
  id: string
  chapter: string
  title: string
  rulingType?: 'fard' | 'wajib' | 'sunnah' | 'haram' | 'makruh' | 'info' | 'halal'
  madhab?: string
  sistersRelevant?: boolean
  overview?: string
  points: string[]
  examples?: FiqhExample[]
  hadith?: FiqhHadith[]
  note?: string
  definitions?: Record<string, string>
  table?: { col1: string; col2: string; rows: [string, string][] }
}

// ─── Chapter labels (in display order) ──────────────────────────────────────

export const CHAPTER_ORDER = [
  'Tahara', 'Salah', 'Sawm', 'Zakah', 'Hajj', 'Nikah', 'Divorce',
  'Inheritance', 'Muamalaat', 'Halal & Haram', "Women's Fiqh",
  'Udhiyyah', 'Funeral', 'Q&A',
]

// ─── Badge styles ───────────────────────────────────────────────────────────

export const BADGE: Record<string, string> = {
  fard:   'bg-red-500/15 text-red-400 border border-red-500/20',
  wajib:  'bg-orange-500/15 text-orange-400 border border-orange-500/20',
  sunnah: 'bg-blue-500/15 text-blue-400 border border-blue-500/20',
  haram:  'bg-rose-700/15 text-rose-400 border border-rose-700/20',
  makruh: 'bg-amber-500/15 text-amber-400 border border-amber-500/20',
  info:   'bg-gray-700/30 text-gray-400 border border-gray-700/20',
  halal:  'bg-emerald-500/15 text-emerald-400 border border-emerald-500/20',
}

// ─── Topics ─────────────────────────────────────────────────────────────────

export const FIQH_TOPICS: FiqhTopic[] = [
  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Tahara (Purification)
  // Source: Al Fiqh-ul Muyassar pp.12–44
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'water-types',
    chapter: 'Tahara',
    title: 'Types of Water & Their Rulings',
    rulingType: 'info',
    sistersRelevant: true,
    overview: 'Water is divided into five categories in the Hanafi school, each with specific rulings for purification.',
    points: [
      '1. Pure and purifying (Taahir Mutahhir): rainwater, well water, spring water, river water, sea water, snow and ice-melt. Valid for wudu, ghusl, and removing impurity.',
      '2. Pure and purifying but makruh: water left in the sun in a metal vessel, or water a cat has drunk from. Valid for purification but its use is disliked.',
      '3. Pure but not purifying (Taahir ghayr Mutahhir): used water (maa musta\'mal) — water that has already been used for wudu or ghusl. Cannot be used for purification again.',
      '4. Impure (Naajis): water in which impurity has fallen and changed its colour, taste or smell (small quantity); or large quantity water contaminated beyond the threshold. Invalid for any use.',
      '5. If a pure substance (saffron, soap, leaves) mixes with water changing a property, it remains pure but loses its purifying ability.',
      'Leftover water of humans, horses, and halal-meat animals: pure and purifying.',
      'Leftover water of cats and free-roaming fowl: pure but makruh to use for purification.',
      'Leftover water of dogs, pigs, and beasts of prey: impure (naajis) — cannot be used.',
      'Well water: if an impurity falls in but does not change a property, it remains pure. If something dies in the well, specific amounts of water must be drawn out depending on the animal size.',
    ],
    definitions: {
      'Taahir Mutahhir': 'Pure and purifying — valid for wudu and ghusl',
      'Maa Musta\'mal': 'Used water — already used for wudu/ghusl, cannot purify again',
      'Naajis': 'Impure water — changed by filth in colour, taste, or smell',
      'Su\'r': 'Leftover water — water remaining after a person or animal drinks',
    },
  },
  {
    id: 'etiquettes-relieving',
    chapter: 'Tahara',
    title: 'Etiquettes of Relieving Oneself (22 Adab)',
    rulingType: 'sunnah',
    sistersRelevant: true,
    overview: 'The Prophet ﷺ taught 22 specific etiquettes for using the toilet — covering entering, exiting, positioning, and cleanliness.',
    hadith: [
      {
        arabic: 'أَعُوذُ بِاللَّهِ مِنَ الْخُبُثِ وَالْخَبَائِثِ',
        transliteration: 'A\'udhu billahi minal khubuthi wal khabaa\'ith',
        translation: 'I seek refuge in Allah from the male and female evil jinn.',
        source: 'Bukhari & Muslim (EQ 25706)',
      },
      {
        arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَذْهَبَ عَنِّي الْأَذَى وَعَافَانِي',
        transliteration: 'Alhamdulillahil-ladhi adh-haba \'annil adha wa \'aafaani',
        translation: 'All praise is due to Allah who has removed from me the harm and given me well-being.',
        source: 'Ibn Majah (EQ 30224)',
      },
    ],
    points: [
      '1. Enter the toilet with the LEFT foot first',
      '2. Exit with the RIGHT foot first',
      '3. Recite the dua of entering before stepping in',
      '4. Recite the dua of exiting after stepping out',
      '5. Do not face the Qibla nor turn your back towards it while relieving yourself (outdoors without barrier)',
      '6. Do not relieve yourself facing the sun or the moon',
      '7. Do not relieve yourself facing the wind direction',
      '8. Conceal yourself from the view of others',
      '9. Do not urinate while standing (unless there is a valid excuse)',
      '10. Do not urinate into stagnant water',
      '11. Do not urinate into a hole in the ground',
      '12. Do not urinate on a hard surface (to prevent splashing)',
      '13. Do not take anything into the toilet that has the name of Allah or Quranic verses on it',
      '14. Do not speak or make dhikr while relieving yourself',
      '15. Do not look at the private parts',
      '16. Do not look at what exits the body',
      '17. Cleanse using the LEFT hand only',
      '18. Do not use the right hand for cleansing (istinja)',
      '19. Wash hands after cleansing thoroughly',
      '20. Cleanse with water (preferred) or at least 3 stones — odd number required',
      '21. Do not cleanse with bones, dung, food items, or anything respectable',
      '22. Sprinkle a little water on underclothes after cleansing to remove doubt about later discharge',
    ],
    note: 'These are combined from the PDF chapters on etiquettes of relieving oneself and cleansing rulings.',
  },
  {
    id: 'istinja-cleansing',
    chapter: 'Tahara',
    title: 'Cleansing (Istinja) & Types of Filth',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Filth is classified as de jure (hadath — ablutionary) and de facto (najasah — physical). Each has thresholds for excusing in Salah.',
    points: [
      'De jure filth (Hadath): Major hadath — from intercourse/ejaculation/hayd/nifas, requires ghusl. Minor hadath — from wudu breakers, requires wudu.',
      'De facto filth (Najasah) — Severe (Ghaleeza): human urine, stool, flowing blood, wine, pig, dog. Excused only up to the size of a dirham (~3g solid, or the depression of the palm for liquid).',
      'De facto filth — Mild (Khafeefa): urine of halal-meat animals, droppings of non-excusable birds. Excused if it covers less than one quarter of the garment or one quarter of the affected limb.',
      'Removal of severe filth: wash until the trace is gone. If the colour/smell remains after 3 washes but the substance is removed, it is excused.',
      'Removal of filth from leather: wiping is sufficient. From glass/metal: wiping is sufficient. From cloth: requires washing.',
      'Istinja (cleansing after toilet): water alone is sufficient and best. Stones (3 minimum, odd number) are acceptable. Combining water and stones is most complete.',
    ],
    definitions: {
      'Hadath': 'De jure filth — invisible impurity removed by wudu or ghusl',
      'Najasah': 'De facto filth — physical impurity (blood, urine, etc.) removed by washing',
      'Ghaleeza': 'Severe filth — excused up to dirham size (~3g solid / palm-depression liquid)',
      'Khafeefa': 'Mild filth — excused up to quarter of garment',
      'Dirham': 'Approximately 3 grams (solid) or the size of the inner depression of the palm (liquid)',
    },
    examples: [
      { scenario: 'A drop of blood smaller than a dirham falls on your shirt', ruling: 'Excused — Salah is valid without washing' },
      { scenario: 'Urine of a halal goat splashes on less than 1/4 of your thobe', ruling: 'Excused (mild filth) — Salah is valid' },
      { scenario: 'A baby urinates on your clothes (more than dirham size)', ruling: 'Must wash before Salah — human urine is severe filth' },
    ],
  },
  {
    id: 'wudu-detailed',
    chapter: 'Tahara',
    title: 'Wudu — Fard, Sunnah, Etiquettes & Invalidators',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Wudu has 4 fard (obligatory) acts, 18 sunnah acts, 13 etiquettes, and 6 avoidable acts. Anything omitted from the fard invalidates the wudu entirely.',
    points: [
      '── 4 FARD OF WUDU ──',
      '1. Washing the face once — from the hairline to below the chin, ear to ear (including thin beard)',
      '2. Washing both arms once — from fingertips to and including the elbows',
      '3. Wiping one quarter of the head once (masah)',
      '4. Washing both feet once — to and including the ankles',
      '── 18 SUNNAH ACTS ──',
      '1. Intention (niyyah) 2. Saying Bismillah 3. Washing hands to wrists (3x) 4. Using miswak/toothstick 5. Rinsing mouth (madmadah, 3x) 6. Sniffing water into nose (istinshaq, 3x) 7. Clearing nose with left hand 8. Wiping the entire head 9. Wiping inside and outside of ears 10. Rinsing thick beard with wet fingers 11. Interlacing fingers and toes 12. Washing each limb 3 times 13. Starting with the right 14. Rubbing the limbs 15. Performing in proper order (tartib) 16. Continuity without breaks 17. Wiping the neck 18. Performing wudu at the beginning of Salah time',
      '── INVALIDATORS (9 THINGS) ──',
      '1. Any discharge from front or back passage (urine, stool, wind)',
      '2. Blood, pus, or fluid flowing from a wound',
      '3. Vomiting a mouthful',
      '4. Bleeding from the mouth (saliva is majority blood)',
      '5. Sleeping while lying down or leaning (body unsupported)',
      '6. Loss of consciousness, fainting, intoxication, insanity',
      '7. Laughing aloud in any Salah that has ruku and sujud (Hanafi only — breaks both wudu and Salah)',
      '8. Touching one\'s spouse with desire (Shafi\'i/Hanbali: breaks wudu; Hanafi: does NOT)',
      '9. Touching one\'s own private parts with the inner palm (Shafi\'i: breaks wudu; Hanafi: does NOT)',
      '── 10 THINGS THAT DO NOT BREAK WUDU ──',
      '1. Touching a woman without desire (Hanafi) 2. Touching private parts (Hanafi) 3. Laughter outside Salah 4. Bleeding that does not flow 5. Vomiting less than a mouthful 6. Eating or drinking 7. Sleeping sitting upright 8. Being naked 9. Cutting hair or nails 10. Crying',
    ],
  },
  {
    id: 'ghusl-detailed',
    chapter: 'Tahara',
    title: 'Ghusl — Obligatory Bathing: Types, Method & 18 Occasions',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Ghusl has 3 mandatory acts, 9 traditions, and 3 kinds: mandatory, traditional, and desirable. There are 4 sunnah occasions and 18 desirable occasions for ghusl.',
    points: [
      '── 3 MANDATORY ACTS OF GHUSL ──',
      '1. Rinsing the mouth thoroughly (madmadah) — water must reach all parts inside the mouth',
      '2. Sniffing water into the nose (istinshaq) — up to the soft part of the nose',
      '3. Washing the entire body — no spot the size of a hair may remain dry',
      '── 9 TRADITIONS OF GHUSL ──',
      '1. Intention (niyyah) 2. Saying Bismillah 3. Washing both hands to wrists first 4. Washing away any filth from the body 5. Performing full wudu before pouring water 6. Pouring water over the head 3 times 7. Then washing the right side of body 8. Then the left side 9. Rubbing the body',
      '── 3 KINDS OF GHUSL ──',
      'A. MANDATORY (Fard): After ejaculation with desire, intercourse (even without ejaculation), end of menstruation, end of post-natal bleeding, at death (ghusl of deceased)',
      'B. TRADITIONAL (Sunnah — 4 occasions): Friday prayer, Eid al-Fitr, Eid al-Adha, Day of Arafah (for the Hajj pilgrim)',
      'C. DESIRABLE (Mustahabb — 18 occasions): Before entering Ihram, upon entering Makkah, for Tawaf, for standing at Arafah, at Muzdalifah, for the 3 pebble-throwing days at Mina, for the eclipse prayer, for the rain prayer, after bathing a deceased, after recovering from insanity, after recovering from fainting, upon reaching puberty, for Laylatul Qadr, for Laylatul Bara\'ah, for Laylatul Arafah, for the Night of Isra, for the Day of Ashura, on the day of the supplication gathering',
    ],
    note: 'For women: ensure water reaches the roots of all hair. Unbraiding thick plaits is NOT required per Hanafi if water reaches the roots.',
  },
  {
    id: 'tayammum-detailed',
    chapter: 'Tahara',
    title: 'Tayammum — Dry Ablution: Prerequisites, Method & Rulings',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Allah commands in Quran 5:6 — "If you are ill, or on a journey, or one of you comes from relieving himself, or you have touched women and find no water, then do tayammum with clean earth."',
    hadith: [
      {
        arabic: 'جُعِلَتْ لِيَ الْأَرْضُ مَسْجِدًا وَطَهُورًا',
        transliteration: 'Ju\'ilat liyal ardu masjidan wa tahoora',
        translation: 'The earth has been made for me a place of prayer and a means of purification.',
        source: 'Bukhari & Muslim',
      },
    ],
    points: [
      '── 8 PREREQUISITES FOR TAYAMMUM ──',
      '1. Unavailability of water, or water being at a distance of approximately one mile (1.6 km)',
      '2. Illness — using water would aggravate sickness or delay cure',
      '3. Fear of severe cold with no means of heating water',
      '4. Water is needed for drinking (life-saving priority)',
      '5. Fear that Salah time will expire before obtaining water',
      '6. Fear of enemy or wild animal at the water source',
      '7. The rope/bucket has broken at the well and cannot retrieve water',
      '8. Fear that if he leaves to fetch water, his belongings or companions will be harmed',
      '9. Being imprisoned with no access to water',
      '── 2 ESSENTIALS ──',
      '1. First strike: Wipe the entire face',
      '2. Second strike: Wipe both arms to and including the elbows',
      '── 6 TRADITIONS ──',
      '1. Saying Bismillah 2. Intention (niyyah) 3. Striking the earth with open fingers 4. Blowing excess dust from palms 5. Starting with the face 6. Performing in proper order',
      '── INVALIDATORS ──',
      'Everything that invalidates wudu also invalidates tayammum. Additionally: sighting of water, or the reason for tayammum ceasing to exist.',
    ],
    definitions: {
      'Tayammum': 'Dry ablution using clean earth, dust, sand, or stone when water is unavailable',
      'Sa\'eed Tayyib': 'Clean earth — includes soil, sand, stone, clay, limestone, wall plaster (Hanafi)',
    },
    examples: [
      { scenario: 'You are travelling and find no water within 1 mile', ruling: 'Tayammum is valid — perform and pray on time' },
      { scenario: 'Water is available but you have a skin wound that worsens with water', ruling: 'Tayammum is valid for the wudu — wash the unaffected limbs normally' },
      { scenario: 'You perform tayammum, then water becomes available before Salah', ruling: 'Tayammum is invalidated — you must make wudu' },
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Salah (Prayer)
  // Source: Al Fiqh-ul Muyassar pp.45–112
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'salah-times',
    chapter: 'Salah',
    title: 'The Five Daily Prayer Times',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Each of the five daily prayers has a specific time window. Praying before the time enters or after it exits is invalid.',
    points: [
      'FAJR: From true dawn (Subh Sadiq — white horizontal light) until just before sunrise. Delaying to when there is good light is preferred.',
      'DHUHR: From the sun\'s decline from the zenith until the shadow of an object becomes double its length (plus its shadow at zenith). In extreme heat, delaying Dhuhr is preferred.',
      'ASR: From when Dhuhr time ends until just before sunset. Hanafi: shadow = double + noon shadow. Shafi\'i: shadow = single + noon shadow. Delaying to just before sunset is makruh tahreemi.',
      'MAGHRIB: From sunset until the redness (or whiteness per Abu Hanifah) disappears from the western horizon. Best to pray immediately without delay.',
      'ISHA: From when Maghrib time ends until before true dawn. Delaying to the first third of the night is preferred. After midnight is makruh.',
      '── 3 FORBIDDEN TIMES FOR ALL SALAH ──',
      '1. When the sun is rising 2. When the sun is at its absolute zenith 3. When the sun is setting (yellowish-red disc). No Salah at all — not even Qada or Janazah — except Asr of that day (if not yet prayed) which is valid but sinful to delay.',
    ],
  },
  {
    id: 'salah-prerequisites',
    chapter: 'Salah',
    title: 'Prerequisites for Valid Salah (6 Conditions)',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Six conditions must be met before Salah can be valid. Missing any one invalidates the entire prayer.',
    points: [
      '1. RITUAL PURITY — Valid wudu, or ghusl where required, or tayammum if water is unavailable.',
      '2. PURITY OF BODY, CLOTHES, AND PRAYER PLACE — Free from najasah beyond the excused threshold (dirham size for severe filth, 1/4 for mild filth).',
      '3. COVERING THE AWRAH:',
      '   • Men: from navel to knees inclusive (both navel and knees must be covered)',
      '   • Free women: entire body except face, palms of hands, and feet below the ankles',
      '   • If more than 1/4 of an awrah limb is uncovered for the duration of 3 tasbihs, Salah is invalidated',
      '4. FACING THE QIBLA — Must face the direction of the Ka\'bah. If uncertain, make your best effort (ijtihad). If in the wilderness, follow credible information or ask someone reliable.',
      '5. CORRECT TIME — Salah is only valid within its prescribed time window. Before the time enters: invalid entirely.',
      '6. INTENTION (NIYYAH) — Must know which Salah you are praying. Niyyah is in the heart; verbal declaration is sunnah.',
    ],
    note: 'Awrah for a slave woman in Hanafi fiqh was navel to knees plus abdomen and back. This ruling is historical.',
  },
  {
    id: 'salah-essentials',
    chapter: 'Salah',
    title: 'The 5 Essentials (Arkan) of Salah',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'These are the pillars without which Salah is completely invalid. Omitting any one cannot be compensated by Sujud al-Sahw.',
    points: [
      '1. QIYAM (Standing): Standing upright for the fard and wajib Salahs if physically able. If a person can stand even by leaning on a stick, he must stand.',
      '2. QIRA\'AH (Recitation): Reciting the Quran during Salah. Minimum: one verse (Hanafi). The Fatihah and an additional surah in the first two rakat of fard are wajib.',
      '3. RUKU (Bowing): Bowing until the hands reach the knees and the back is approximately level. Must have a brief stillness (tuma\'neenah).',
      '4. SUJUD (Prostration): Prostrating on 7 bones — forehead (with nose), both palms, both knees, toes of both feet. The forehead must touch the ground. If the ground is elevated, it must be within half a cubit of the feet level.',
      '5. QA\'DAH AKHIRAH (Last Sitting): Sitting at the end of the final rakat for the duration of reciting the Tashahhud. This is the essential — Salah is incomplete without it.',
    ],
    note: 'Omitting any essential completely invalidates Salah — Sujud al-Sahw cannot fix it.',
  },
  {
    id: 'salah-wajib-15',
    chapter: 'Salah',
    title: 'The 15 Compulsory (Wajib) Acts of Salah',
    rulingType: 'wajib',
    sistersRelevant: true,
    overview: 'Wajib acts sit between Fard and Sunnah. Deliberately omitting a wajib invalidates Salah. Accidentally omitting requires Sujud al-Sahw.',
    points: [
      '1. Reciting Surah al-Fatihah in every rakat',
      '2. Adding a surah or 3 short verses (or 1 long verse) after Fatihah in the first 2 rakat of fard and every rakat of witr, sunnah, and nafl',
      '3. Recitation of Fatihah before the additional surah (correct order)',
      '4. Fixing the Fatihah and surah in the first two rakat of fard only (not in 3rd/4th)',
      '5. Not reciting anything after Fatihah in the 3rd and 4th rakat of fard',
      '6. Performing two prostrations in each rakat (not one)',
      '7. Sitting after the 2nd rakat of 3- or 4-rakat Salah (Qa\'dah Ula — first sitting)',
      '8. Reciting the full Tashahhud (At-Tahiyyat) in both sittings',
      '9. The Imam reciting Fatihah and surah audibly in Fajr, Maghrib (1st two), Isha (1st two), Jumu\'ah, Tarawih, Witr of Ramadan, and Eid Salahs',
      '10. The Imam reciting silently in Dhuhr and Asr',
      '11. Completing each posture with stillness and tranquility (tuma\'neenah)',
      '12. Performing Sujud al-Sahw when required',
      '13. Ending Salah with Tasleem (saying Assalamu Alaikum to right and left)',
      '14. Saying the Takbirs of Eid in the Eid Salah',
      '15. Reciting Dua Qunoot in Witr',
    ],
  },
  {
    id: 'salah-sunnah-43',
    chapter: 'Salah',
    title: 'The 43 Traditions (Sunnah Acts) of Salah',
    rulingType: 'sunnah',
    sistersRelevant: true,
    overview: 'The Prophet ﷺ consistently performed these acts. Omitting them is not sinful but loses great reward. They perfect the Salah.',
    points: [
      '1. Raising hands to earlobes at Takbir al-Ihram (women: to shoulders)',
      '2. Fingers spread and facing Qibla during the raising',
      '3. The Imam not raising his voice with the opening Takbir beyond what the followers need to hear',
      '4. Placing right hand over left below the navel (Hanafi; women: on chest)',
      '5. Reciting Thana (Subhanakallahummma wa bihamdika...)',
      '6. Saying Ta\'awwudh (A\'udhu billahi min ash-shaytan ir-rajeem)',
      '7. Saying Bismillah before Fatihah',
      '8. Saying Ameen silently (Hanafi; Shafi\'i: audibly)',
      '9. Reciting Thana, Ta\'awwudh, Bismillah, and Ameen quietly',
      '10. Reciting only Bismillah (not Thana/Ta\'awwudh) at the start of the 2nd rakat',
      '11-17. Various positions of feet, gaze at prostration point, and hand positions during Qiyam',
      '18. Saying the Takbir when going into ruku',
      '19. Saying "Subhana Rabbiyal Azeem" 3 times in ruku',
      '20. Grasping the knees with fingers spread in ruku, back level',
      '21. Imam saying "Sami\'Allahu liman hamidah" when rising from ruku',
      '22. Followers responding "Rabbana lakal hamd"',
      '23. Saying the Takbir when going into sujud',
      '24. Saying "Subhana Rabbiyal A\'la" 3 times in sujud',
      '25. Placing knees on the ground before hands when going into sujud',
      '26. In sujud: men keep arms away from sides, stomach from thighs (women: keep compact — arms close, stomach on thighs)',
      '27. Toes pointing towards Qibla in sujud',
      '28-33. Various postures for sitting between sajdahs (men: left foot flat, sitting on it; women: sitting to the right)',
      '34. The finger-pointing during Tashahhud (raise index finger at "Ash-hadu an la ilaha")',
      '35. Reciting Durood Ibrahim after Tashahhud in the final sitting',
      '36. Reciting a dua after Durood Ibrahim (before Tasleem)',
      '37. Turning face right then left for Tasleem',
      '38. The Imam intending the followers, angels, and righteous jinn in his Salaam',
      '39. The follower intending the Imam, angels, and congregation in his Salaam',
      '40. Saying the second Salaam lower than the first',
      '41. Beginning Salah immediately after the Iqamah',
      '42. A person praying alone recites all adhkaar and duas quietly',
      '43. Keeping the gaze at the point of prostration throughout',
    ],
    note: 'Women\'s differences (footnotes in the PDF): hands to shoulders not ears; hands on chest not navel; compact posture in ruku/sujud; sit to the right in jalsa.',
  },
  {
    id: 'salah-invalidators-31',
    chapter: 'Salah',
    title: 'What Invalidates Salah (31 Things)',
    rulingType: 'haram',
    sistersRelevant: true,
    overview: 'The PDF lists 31 acts that invalidate Salah. Some are by consensus, others are Hanafi-specific.',
    points: [
      '1. Speaking intentionally — even one word, even greeting someone',
      '2. Speaking forgetfully if the speech is extensive',
      '3. Saying "Yarhamukallah" (to someone who sneezes) or responding to a greeting',
      '4. Groaning, saying "Ooh" or "Aah" from pain',
      '5. Clearing the throat without need (if it produces audible letters)',
      '6. Blowing on something audibly (produces letters)',
      '7. Reciting Quran by looking at the Mushaf (Hanafi: invalidates; holding and turning pages = excessive action)',
      '8. Eating or drinking — even a tiny amount intentionally',
      '9. Excessive continuous movement (3 or more actions in a row without Salah-related purpose)',
      '10. Turning the chest away from the Qibla',
      '11. Wudu breaking during Salah',
      '12. The sun rising during Fajr Salah',
      '13. The time of a Salah entering while still praying the previous one (Dhuhr entering while praying Fajr)',
      '14. Laughing aloud — even one syllable (Hanafi: breaks wudu AND Salah)',
      '15. Uncovering 1/4 of an awrah limb for the duration of 3 tasbihs',
      '16. A grown male standing directly alongside a female in the same Salah row (Hanafi: invalidates the male\'s Salah)',
      '17-31. Various additional acts including: prompting a non-Imam with Quran, leaning heavily on something, prostrating on unclean surface, making sujud al-tilaawah at the wrong time, preceding the Imam significantly in a posture, etc.',
    ],
  },
  {
    id: 'salah-congregation',
    chapter: 'Salah',
    title: 'Congregational Salah — Virtues, Excuses & Imam Requirements',
    rulingType: 'sunnah',
    overview: 'Congregational Salah is emphasized sunnah (almost wajib) for men. The PDF lists 17 valid excuses for missing it and 8 prerequisites for the Imam.',
    points: [
      '── 17 EXCUSES FOR MISSING CONGREGATION ──',
      '1. Rain 2. Mud/slippery ground 3. Extreme cold 4. Extreme heat 5. Darkness 6. Fear of an oppressor 7. Genuine illness 8. Blindness (with no guide) 9. Being crippled/paralyzed 10. Loss of a limb (hands/feet) 11. Very old age 12. Being a caretaker for a sick person 13. Fear for one\'s life or property 14. Fear of missing a travelling companion 15. Needing food when food is served 16. Needing to relieve oneself urgently 17. Strong opposing wind',
      '── 8 PREREQUISITES FOR A VALID IMAM ──',
      '1. Muslim 2. Adult (or at minimum a discerning child for sunnah/nafl) 3. Sane 4. Male (for leading men — a woman may lead other women only) 5. Proper reciter of Quran (does not make errors that change meaning) 6. Free from chronic excuse (Hanafi detail) 7. Able to perform the pillars of Salah 8. Not a known open sinner (fasiq) leading by force',
      '── WHO SHOULD BE PREFERRED AS IMAM? ──',
      'Most knowledgeable in fiqh of Salah, then best reciter, then most pious, then eldest. The permanent Imam of the mosque is preferred over a visitor unless the visitor is clearly more qualified and the Imam delegates.',
    ],
  },
  {
    id: 'witr-detailed',
    chapter: 'Salah',
    title: 'Witr Prayer — Ruling, Method & Dua Qunoot',
    rulingType: 'wajib',
    sistersRelevant: true,
    overview: 'Witr is Wajib in the Hanafi madhab. It is 3 rakat prayed after Isha, and includes the wajib Dua Qunoot in the 3rd rakat.',
    hadith: [
      {
        arabic: 'الْوِتْرُ حَقٌّ عَلَى كُلِّ مُسْلِمٍ',
        transliteration: 'Al-witru haqqun \'ala kulli muslim',
        translation: 'Witr is a duty upon every Muslim.',
        source: 'Abu Dawud (EQ 16108)',
      },
    ],
    points: [
      'Witr is 3 rakat — prayed with one Tasleem (Hanafi). Shafi\'i: 1 rakat is sufficient.',
      'Method: Pray 2 rakat normally (Fatihah + Surah in each). Sit for Tashahhud. Rise for the 3rd rakat. Recite Fatihah + Surah. Then raise hands to ears saying Allahu Akbar, then fold hands and recite Dua Qunoot. Complete normally (ruku, sujud, Tashahhud, Durood, Tasleem).',
      '── DUA QUNOOT (narrated from Abdullah ibn Mas\'ud) ──',
      'Allahumma inna nasta\'inuka wa nastaghfiruka, wa nu\'minu bika wa natawakkalu \'alayka, wa nuthni \'alaykal khayr. Wa nashkuruka wa laa nakfuruka, wa nakhla\'u wa natruku man yafjuruk. Allahumma iyyaka na\'budu, wa laka nusalli wa nasjudu, wa ilayka nas\'a wa nahfidu. Narju rahmataka wa nakhsha \'adhabaka, inna \'adhabaka bil kuffari mulhiq.',
      'Translation: O Allah, we seek Your help and ask Your forgiveness. We believe in You and rely on You. We praise You in the best way. We thank You and are not ungrateful to You. We abandon and leave those who disobey You. O Allah, You alone we worship, to You we pray and prostrate. Towards You we hasten and to You we flee. We hope for Your mercy and fear Your punishment. Indeed, Your punishment overtakes the disbelievers.',
      'If Qunoot is forgotten: perform Sujud al-Sahw at the end (before or after Tasleem per different Hanafi narrations).',
      'Witr time: After Isha until before Fajr. Best prayed as the last prayer of the night.',
    ],
    note: 'Never call Witr "optional." In Hanafi fiqh it is Wajib — between Fard and Sunnah in obligation level.',
  },
  {
    id: 'salah-sunnah-types',
    chapter: 'Salah',
    title: 'Sunnah & Nafl Prayers — Emphasised and Non-Emphasised',
    rulingType: 'sunnah',
    sistersRelevant: true,
    overview: 'The Prophet ﷺ regularly prayed additional prayers alongside the fard. Some are "emphasised" (Sunnah Mu\'akkadah) and some are non-emphasised.',
    points: [
      '── 7 EMPHASIZED SUNNAH (Sunnah Mu\'akkadah) ──',
      '1. 2 rakat before Fajr (the most emphasised — the Prophet ﷺ never left them even while travelling)',
      '2. 4 rakat before Dhuhr (with one Tasleem)',
      '3. 2 rakat after Dhuhr',
      '4. 2 rakat after Maghrib',
      '5. 2 rakat after Isha',
      '6. Witr (3 rakat — Wajib per Hanafi, covered separately)',
      '7. Tarawih in Ramadan (20 rakat per Hanafi; 8 per some scholars)',
      '── 4 NON-EMPHASIZED SUNNAH ──',
      '1. 4 rakat before Asr',
      '2. 4 rakat before Isha',
      '3. 2 rakat after Isha (before Witr)',
      '4. 6 rakat after Maghrib (Salat al-Awwabin)',
      'Leaving an emphasised sunnah repeatedly without excuse is sinful and one who habitually abandons it is considered a wrongdoer.',
    ],
  },
  {
    id: 'salah-women',
    chapter: 'Salah',
    title: 'Differences in Women\'s Salah',
    rulingType: 'info',
    sistersRelevant: true,
    overview: 'The PDF footnotes throughout the Salah chapters note specific differences in how women perform Salah per the Hanafi school.',
    points: [
      'TAKBIR: Hands raised to shoulder level (not to earlobes like men)',
      'QIYAM: Hands folded on the chest (men: below navel)',
      'RUKU: Slight bow only — hands on knees, fingers together, arms close to body (men: fully flat back, fingers spread, arms away)',
      'SUJUD: Body kept compact — stomach close to thighs, forearms flat on the ground (not raised), elbows touching the ground (men: arms raised away, stomach off thighs)',
      'JALSA (sitting between sajdahs): Sit on the left buttock with both legs out to the right (men: sit on left foot, right foot upright)',
      'QA\'DAH (Tashahhud sitting): Same as jalsa — legs to the right',
      'VOICE: Recite everything quietly — women do not recite audibly when men can hear',
      'ADHAN/IQAMAH: Neither adhan nor iqamah for women (men: both are sunnah mu\'akkadah)',
      'LEADING PRAYER: A woman may lead other women. She stands in the middle of the first row (not in front).',
      'JUMU\'AH: Not obligatory for women. If they attend, they pray with the congregation.',
      'Awrah in Salah: Entire body including hair, wrists, and ankles — only face and inner palms are exposed. Feet must be covered during Salah (Hanafi).',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Sawm (Fasting)
  // Source: Al Fiqh-ul Muyassar pp.125–139
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'fasting-conditions',
    chapter: 'Sawm',
    title: 'Fasting — Conditions, Kinds & Intention',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'The Ramadan fast is individually obligatory on every adult, sane, healthy Muslim. There are 6 kinds of fasting from obligatory to forbidden.',
    points: [
      '── PREREQUISITES FOR FASTING TO BE OBLIGATORY ──',
      '1. Islam 2. Adulthood (puberty) 3. Sanity 4. Physical ability — chronic illness or old age excuses',
      '── 6 KINDS OF FASTING ──',
      '1. Fard: Ramadan fasting (on time or as Qada)',
      '2. Wajib: Vow fasting, and fasting as kaffarah (expiation)',
      '3. Sunnah Mu\'akkadah: Fasting on 9th and 10th Muharram (Ashura)',
      '4. Mustahabb (Recommended): Fasting on 13th, 14th, 15th of each lunar month; Mondays and Thursdays; 6 days of Shawwal',
      '5. Makruh: Fasting only on Saturdays, fasting every day without break (continuous)',
      '6. Haram: Fasting on the 2 Eid days and the 3 days of Tashriq (11th-13th Dhul Hijjah)',
      '── INTENTION (NIYYAH) ──',
      'For Ramadan fard: intention must be made before Fajr (subh sadiq). An intention from the night before is sufficient.',
      'For voluntary fasts: intention before midday (Dhuhr time) is valid, provided nothing was eaten/drunk since Fajr.',
      'For vow and kaffarah fasts: intention must be made before Fajr — same as Ramadan.',
    ],
    definitions: {
      'Sawm': 'Fasting — abstaining from food, drink, and intercourse from true dawn to sunset with intention',
      'Suhoor': 'Pre-dawn meal — Sunnah to eat, and to delay it close to Fajr',
      'Iftar': 'Fast-breaking meal — Sunnah to break fast immediately at sunset',
      'Fidya': 'Compensation for missed fasts by those who cannot fast at all — feed one poor person per missed day',
    },
  },
  {
    id: 'fasting-does-not-break',
    chapter: 'Sawm',
    title: 'What Does NOT Break the Fast (20 Things)',
    rulingType: 'halal',
    sistersRelevant: true,
    overview: 'The PDF lists 20 specific acts that do not break the fast — knowing these removes unnecessary anxiety.',
    points: [
      '1. Eating, drinking, or having intercourse forgetfully (fast remains valid — stop immediately upon remembering)',
      '2. An involuntary wet dream during the day',
      '3. Applying oil to the body or hair',
      '4. Applying surma/kohl (eyeliner) — even if the taste reaches the throat',
      '5. Cupping (hijamah) or blood extraction',
      '6. Vomiting involuntarily — even if it is a mouthful',
      '7. Water entering the ear unintentionally',
      '8. Dust, smoke, or a fly entering the throat unintentionally',
      '9. Swallowing one\'s own saliva (no matter how often)',
      '10. Injection that is non-nutritional (insulin, vaccines, etc.)',
      '11. Tasting food with the tip of the tongue without swallowing',
      '12. Chewing food for a baby and spitting it out completely',
      '13. Rinsing the mouth for wudu (without deliberately swallowing)',
      '14. Sniffing water into the nose for wudu (without deliberately inhaling deeply)',
      '15. Brushing teeth or using miswak',
      '16. Swallowing something stuck between the teeth smaller than a chickpea',
      '17. Applying medicine to a wound (even if it reaches the stomach)',
      '18. Entering water into the ear',
      '19. Cooling the body by pouring water or wrapping in a wet cloth',
      '20. Applying oil to the moustache and beard',
    ],
  },
  {
    id: 'fasting-kaffarah',
    chapter: 'Sawm',
    title: 'When Kaffarah (Expiation) + Qada is Required',
    rulingType: 'haram',
    sistersRelevant: true,
    overview: 'Kaffarah is required when a Ramadan fast is deliberately broken in the most serious ways. The expiation is severe as a deterrent.',
    points: [
      '── 11 PREREQUISITES FOR KAFFARAH ──',
      'Kaffarah + Qada is required when ALL of these conditions are met:',
      '1. The fast is a Ramadan fast (not a vow, nafl, or qada fast)',
      '2. The person is an adult',
      '3. The person is sane',
      '4. The person is a resident (not a traveller)',
      '5. The person intended to fast from the night before',
      '6. No valid excuse arose that day (like sudden illness)',
      '7. No error occurred (like thinking Fajr had not entered)',
      '8. The act was completely voluntary — no coercion',
      '9. The person knew it was Ramadan',
      '10. The person knew that the act breaks the fast',
      '11. The act was one that requires kaffarah specifically (eating, drinking, intercourse — deliberately)',
      '── DESCRIPTION OF KAFFARAH (in order of priority) ──',
      '1. Free a slave (not applicable today)',
      '2. Fast 60 consecutive days — if even one day is missed, restart from day 1',
      '3. Feed 60 poor people (each gets 2 full meals or 1.632 kg of wheat)',
      'Only one kaffarah per Ramadan — if multiple days are broken, only one kaffarah covers them all.',
    ],
    examples: [
      { scenario: 'You deliberately eat during Ramadan knowing it is Ramadan', ruling: 'Kaffarah + Qada required — fast 60 consecutive days or feed 60 poor' },
      { scenario: 'You break a voluntary fast deliberately', ruling: 'Only Qada required — no kaffarah' },
      { scenario: 'You eat thinking Fajr had not entered, but it had', ruling: 'Only Qada required — no kaffarah (it was an error)' },
    ],
  },
  {
    id: 'fasting-qada-only',
    chapter: 'Sawm',
    title: 'When Only Qada (Makeup) is Required (20 Cases)',
    rulingType: 'info',
    sistersRelevant: true,
    overview: 'These acts break the fast but only require making up the day — no kaffarah.',
    points: [
      '1. Eating or drinking by mistake (thinking Fajr had not entered or Maghrib had arrived)',
      '2. Intentionally vomiting a mouthful',
      '3. Swallowing a pebble, piece of wood, iron, or other non-food item',
      '4. Swallowing raw rice or raw grain (not normally eaten as-is)',
      '5. Swallowing a large amount of sesame seeds (a mouthful or more)',
      '6. Eating soil or clay deliberately',
      '7. Swallowing cotton with or without medicine on it',
      '8. Oil or water entering the throat via the nose (beyond normal wudu sniffing)',
      '9. Water entering the throat due to exaggerating mouth-rinse or nose-sniffing during wudu while knowing you are fasting',
      '10. Enema or suppository (Hanafi: breaks the fast)',
      '11. Using nose drops that reach the throat',
      '12. Eating after making the intention to break the fast (even if one had not actually eaten yet)',
      '13. Eating after dawn thinking it was still night',
      '14. Breaking the fast before Maghrib thinking the sun had set',
      '15. Swallowing food that was stuck between the teeth if larger than a chickpea',
      '16. Smoke or incense deliberately inhaled (non-food)',
      '17. Intercourse in any invalidating orifice other than the normal one',
      '18. Swallowing another person\'s saliva (e.g., via kissing)',
      '19. Water from bathing entering the throat accidentally',
      '20. Eating, then discovering it was already Ramadan (did not know the crescent was sighted)',
    ],
  },
  {
    id: 'fasting-exemptions',
    chapter: 'Sawm',
    title: 'Who is Exempt from Fasting (9 Categories)',
    rulingType: 'info',
    sistersRelevant: true,
    overview: 'Islam is in harmony with human nature. Those who face genuine hardship are permitted to break and make up later, or pay fidya.',
    points: [
      '1. The sick — if fasting harms them, worsens the illness, or delays cure. Must make up later.',
      '2. The traveller — on a journey long enough to warrant shortening Salah (~89 km). Must make up later.',
      '3. A person suffering severe hunger or thirst — when death seems likely if he continues. Must make up later.',
      '4. A pregnant woman — if fasting harms her or the fetus. Must make up later.',
      '5. A nursing mother — if fasting harms her or the baby. Must make up later.',
      '6. A menstruating woman — fasting is COMPULSORY to leave. Her fast is invalid during hayd. Must make up later.',
      '7. A woman in post-natal bleeding (nifas) — same as menstruation. Must make up later.',
      '8. The very elderly — who cannot fast at all without severe hardship. No Qada required — pay Fidya instead (1.632 kg of wheat or its price per day).',
      '9. A person fighting the enemy — may break fast. Must make up later.',
      'Late-observance may be done continuously or with breaks throughout the year.',
      'If a person delays Qada until the next Ramadan arrives, he should prioritize the current Ramadan over Qada. There is no penalty for the delay.',
    ],
    note: 'Fidya 2026 (Guyana): GYD $60,000 per missed fast. Source: D.E.H.C. / Darul Uloom East Street.',
  },
  {
    id: 'itikaf',
    chapter: 'Sawm',
    title: 'I\'tikaf — Retreat in the Mosque',
    rulingType: 'sunnah',
    sistersRelevant: true,
    overview: 'I\'tikaf is staying in a mosque with the intention of worship. It has 3 kinds: obligatory (vow), sunnah (last 10 of Ramadan), and desirable (any time).',
    points: [
      '── 3 KINDS OF I\'TIKAF ──',
      '1. Compulsory (Wajib): I\'tikaf of a vow — duration is whatever was vowed. Fasting on the day is a prerequisite.',
      '2. Emphasised Sunnah (Sunnah Mu\'akkadah Kifayah): Last 10 days of Ramadan — if some in the community perform it, the obligation is lifted from all.',
      '3. Desirable (Mustahabb): Any time — minimum duration is one moment. No fasting prerequisite.',
      '── WHERE IS I\'TIKAF VALID? ──',
      'Only in a mosque where congregational Salahs are regularly held (with an Imam and Mu\'adhin appointed).',
      'A woman should perform I\'tikaf in the Salah-area of her own home.',
      '── INVALIDATORS OF I\'TIKAF ──',
      '1. Going out of the mosque without an excusable reason',
      '2. Onset of menstruation or post-natal bleeding',
      '3. Sexual intercourse or foreplay (kissing, lustful fondling)',
      '── PERMITTED EXITS (3 excuses) ──',
      '1. Physical needs: toilet, mandatory ghusl — but must return immediately',
      '2. Religious needs: Friday Salah (if not held in same mosque)',
      '3. Emergency: fear for life/property, mosque collapse',
    ],
  },
  {
    id: 'sadaqat-fitr',
    chapter: 'Sawm',
    title: 'Sadaqat al-Fitr (Charity of Fast-Breaking)',
    rulingType: 'wajib',
    sistersRelevant: true,
    overview: 'A wajib charity paid at the end of Ramadan to purify the fasting person and feed the poor on Eid day.',
    hadith: [
      {
        arabic: 'فَرَضَ رَسُولُ اللَّهِ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ زَكَاةَ الْفِطْرِ طُهْرَةً لِلصَّائِمِ مِنَ اللَّغْوِ وَالرَّفَثِ وَطُعْمَةً لِلْمَسَاكِينِ',
        translation: 'Allah\'s Prophet ﷺ prescribed the alms relating to the breaking of the fast as a purification of the fasting from empty and obscene talk and as food for the poor.',
        source: 'Abu Dawud (EQ 16298)',
      },
    ],
    points: [
      '── PREREQUISITES (3 conditions) ──',
      '1. Muslim 2. Free 3. Owns the Zakah-cutoff (nisab) in addition to debts and basic needs',
      'Being adult or sane is NOT a prerequisite — it must be paid from the wealth of a child or insane person if they own nisab.',
      'Compulsory at the break of dawn on Eid al-Fitr. If one dies or becomes poor before that, not required.',
      '── WHO TO PAY FOR ──',
      '1. Himself 2. His non-adult poor children (if child is rich, pay from child\'s wealth)',
      'Not compulsory to pay for one\'s wife — but permissible if he volunteers.',
      '── AMOUNT ──',
      '1.632 kg of wheat (or flour), OR 3.264 kg of barley/dates/raisins, OR the cash equivalent',
      'Paying in cash is preferable as it is more beneficial to the poor.',
      'Best time: before going to the Eid prayer. Paying in Ramadan is permissible and recommended.',
      'Delaying past the Eid Salah is makruh unless for an excuse.',
    ],
    note: 'Rate 2026 (Guyana): GYD $2,000 per person — pay on behalf of yourself and all dependants. Source: Darul Uloom East Street.',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Zakah
  // Source: Al Fiqh-ul Muyassar pp.140–148
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'zakah-prerequisites',
    chapter: 'Zakah',
    title: 'Zakah — 9 Prerequisites for Obligation',
    rulingType: 'fard',
    overview: 'Zakah is the 3rd pillar of Islam. It purifies wealth and builds brotherhood between the rich and poor.',
    hadith: [
      {
        arabic: 'مَنْ آتَاهُ اللَّهُ مَالًا فَلَمْ يُؤَدِّ زَكَاتَهُ مُثِّلَ لَهُ مَالُهُ يَوْمَ الْقِيَامَةِ شُجَاعًا أَقْرَعَ',
        translation: 'Whoever is made wealthy by Allah and does not pay the Zakah of his wealth, then on the Day of Resurrection his wealth will be made like a bald-headed poisonous male snake with two black spots over the eyes. The snake will encircle his neck and bite his cheeks and say, "I am your wealth, I am your treasure."',
        source: 'Bukhari (EQ 1330)',
      },
    ],
    points: [
      '── 9 PREREQUISITES ──',
      '1. Islam — not obligatory for a disbeliever',
      '2. Freedom — not obligatory for a slave',
      '3. Adulthood — not obligatory for a child (boy: adult at ~15 years; girl: adult at first menstruation or ~15 years)',
      '4. Sanity — not obligatory for an insane person',
      '5. Total ownership — the wealth must be in his ownership AND custody (e.g., a woman\'s unpaid mahr is not zakatable until she receives it)',
      '6. Wealth equal to or above the Nisab (Zakah-cutoff)',
      '7. Wealth must be surplus to basic needs — personal home, car, clothes, household items, tools of trade are NOT zakatable',
      '8. Wealth must be free of debt — if debt reduces wealth below nisab, no Zakah',
      '9. Wealth must be growing (de facto or de jure) — gold/silver are de jure growing. Gems (pearl, ruby) are NOT zakatable unless held for sale.',
      '── NISAB THRESHOLDS ──',
      'Silver: 595 grams (200 dirhams) — rate: 2.5% (1/40)',
      'Gold: 85 grams (20 dinars) — rate: 2.5% (1/40)',
      'A complete lunar year (approximately 354 days) must pass with wealth at or above nisab at both the beginning and end of the year.',
      'Nisab 2026 (Guyana): GYD $547,298 (gold nisab equivalent) — source: Darul Uloom East Street.',
    ],
    definitions: {
      'Nisab': 'Zakah-cutoff — minimum wealth threshold. Silver: 595g, Gold: 85g',
      'Hawl': 'Complete lunar year (≈354 days) of owning nisab',
      'Zakatable': 'Subject to Zakah — wealth that is growing, surplus to needs, free of debt, at nisab for one hawl',
    },
  },
  {
    id: 'zakah-categories',
    chapter: 'Zakah',
    title: 'Zakah on Different Types of Wealth',
    rulingType: 'fard',
    overview: 'Zakah applies differently to gold/silver, trade goods, loans, and inaccessible wealth.',
    points: [
      '── GOLD & SILVER ──',
      'Silver nisab: 200 dirhams = 595g → pay 5 dirhams (2.5%)',
      'Gold nisab: 20 dinars = 85g → pay 0.5 dinar (2.5%)',
      'Applies to all forms: coins, bars, jewelry, utensils. Adulterated metal counts as pure if the precious metal is more than the impurities.',
      '── TRADE COMMODITIES ──',
      'Everything owned for the purpose of sale (inventory) is zakatable at market value.',
      'Rate: 2.5% of total market value at end of Zakah-year.',
      'Infrastructure and devices used in business (not for sale) are NOT included.',
      '── LOANS (3 categories) ──',
      '1. Strong loan: money lent or owed from a sale of business goods — debtor acknowledges debt. Zakah is owed for all previous years but only payable when any amount is received back.',
      '2. Moderate loan: money owed from sale of personal items (not business). Same rules as strong loan per Imams Abu Yusuf and Muhammad.',
      '3. Weak loan: money expected from non-wealth sources (e.g., woman\'s mahr, blood money). Zakah only when nisab amount is received. No Zakah on previous years.',
      '── INACCESSIBLE WEALTH ──',
      'Lost, stolen, confiscated, or buried-and-forgotten wealth: no Zakah for previous years. Zakah-year starts when recovered.',
    ],
    table: {
      col1: 'Wealth Type',
      col2: 'Nisab & Rate',
      rows: [
        ['Silver', '595g (200 dirhams) — 2.5%'],
        ['Gold', '85g (20 dinars) — 2.5%'],
        ['Trade goods', 'Market value at nisab — 2.5%'],
        ['Cash/savings', 'At silver or gold nisab — 2.5%'],
        ['Agricultural produce', '10% (rain-irrigated) or 5% (irrigated by effort)'],
      ],
    },
  },
  {
    id: 'zakah-recipients',
    chapter: 'Zakah',
    title: 'The 8 Categories of Zakah Recipients & 7 Who Cannot Receive',
    rulingType: 'fard',
    overview: 'Quran 9:60 specifies exactly 8 categories. Hanafi position: 7 remain active (those whose hearts are to be won is suspended by consensus of the Companions).',
    points: [
      '── 8 QUR\'ANIC CATEGORIES ──',
      '1. The Poor (Fuqara): owns less than nisab. May receive even if healthy and able to earn.',
      '2. The Destitute (Masakeen): owns nothing at all.',
      '3. Zakah Collectors (\'Amileen): those appointed to collect and distribute Zakah.',
      '4. Those whose hearts are to be won (Mu\'allafatul Quloob): suspended by consensus of the Sahabah since the time of Umar RA — Islam became strong enough.',
      '5. Slaves (Riqab): the mukatab slaves seeking freedom. Not applicable today.',
      '6. The Indebted (Gharimeen): those who after paying debts no longer own nisab. Paying Zakah to them is preferable to paying the poor.',
      '7. In the Way of Allah (Fi Sabilillah): a needy person engaged in Jihad, or a Hajj pilgrim who ran out of money on the way.',
      '8. The Traveller (Ibn al-Sabil): has wealth at home but is stranded without funds during travel.',
      '── 7 WHO CANNOT RECEIVE ZAKAH ──',
      '1. Disbelievers',
      '2. Rich adults (owning nisab or more)',
      '3. Rich children',
      '4. Banu Hashim (descendants of the Prophet ﷺ) and their freed slaves',
      '5. One\'s own parents and ancestors (father, grandfather, etc.)',
      '6. One\'s own children and descendants (son, grandson, etc.)',
      '7. One\'s spouse',
      'Also: Zakah CANNOT be used for mosque construction, road repair, shroud of deceased, or loan repayment of a deceased person. Transfer of ownership to an eligible person is required.',
      'Best recipients: first relatives, then neighbours.',
      'Detestable: paying one person nisab or more (unless for debt repayment). Detestable: transferring Zakah to another city without need.',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Hajj & Umrah
  // Source: Al Fiqh-ul Muyassar pp.149–161
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'hajj-obligation',
    chapter: 'Hajj',
    title: 'Hajj — Obligation, Prerequisites & 3 Types',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Hajj is the 5th pillar of Islam. It is fard once in a lifetime for every Muslim who meets the conditions.',
    hadith: [
      {
        arabic: 'مَنْ حَجَّ لِلَّهِ فَلَمْ يَرْفُثْ وَلَمْ يَفْسُقْ رَجَعَ كَيَوْمِ وَلَدَتْهُ أُمُّهُ',
        translation: 'Whoever performs Hajj for Allah\'s pleasure and does not have sexual relations with his wife, and does not do evil or sins, then he will return free from all sins as if he were born anew.',
        source: 'Bukhari (EQ 1441)',
      },
    ],
    points: [
      '── 5 PREREQUISITES FOR HAJJ TO BECOME OBLIGATORY ──',
      '1. Muslim 2. Adult 3. Sane 4. Free 5. Financial capability (sufficient for travel expenses + provision for dependants during absence)',
      '── 5 PREREQUISITES FOR PERFORMANCE TO BECOME OBLIGATORY ──',
      '1. Physical health (not handicapped/paralyzed/senile)',
      '2. No obstruction to travel (not imprisoned, no tyrannical ruler blocking)',
      '3. Route is safe',
      '4. For women: presence of husband or mahram (male relative whom she cannot marry)',
      '5. For women: not in iddah (mourning/waiting period)',
      '── 3 TYPES OF HAJJ ──',
      '1. Ifrad (Hajj only): Pilgrim enters Ihram for Hajj only at the Miqat.',
      '2. Qiran (Fully combined): Pilgrim enters Ihram for both Umrah and Hajj together at the Miqat. Preferred per Hanafi.',
      '3. Tamattu\' (Partially combined): Pilgrim enters Ihram for Umrah only, completes it, exits Ihram, then enters Ihram again for Hajj on 8th Dhul Hijjah.',
      'Hanafi preference: Qiran > Tamattu\' > Ifrad.',
    ],
    definitions: {
      'Ihram': 'State of consecration — entering with intention and Talbiyah at the Miqat',
      'Miqat': 'Designated boundary points where Ihram must be entered before proceeding to Makkah',
      'Talbiyah': 'Labbaik Allahumma labbaik... — the chant of the pilgrim recited frequently',
      'Mahram': 'Close male relative whom a woman cannot marry (father, brother, son, uncle, etc.)',
    },
  },
  {
    id: 'hajj-essentials-wajib',
    chapter: 'Hajj',
    title: 'Essentials, Compulsory Acts & Traditions of Hajj',
    rulingType: 'fard',
    overview: 'Hajj has only 2 essentials (arkaan), 10 compulsory acts (wajibaat), and 12 traditions (sunnahs).',
    points: [
      '── 2 ESSENTIALS (Missing either invalidates Hajj) ──',
      '1. Wuquf at Arafah: Being present at the ground of Arafah between the sun\'s decline on 9th Dhul Hijjah and dawn of the 10th. Even a moment suffices.',
      '2. Tawaf al-Ziyarah (Visit Circumambulation): 7 circuits of the Ka\'bah after the Arafah stay. Must be done on the 10th, 11th, or 12th.',
      '── 10 COMPULSORY ACTS (wajib — penalty for missing) ──',
      '1. Starting Ihram at or before the Miqat',
      '2. Stay at Muzdalifah (even a moment) — between Fajr and sunrise on 10th Dhul Hijjah',
      '3. Performing Tawaf al-Ziyarah on one of the days of sacrifice (10-12 Dhul Hijjah)',
      '4. Sa\'i between Safa and Marwah (7 walks — starting at Safa, ending at Marwah)',
      '5. Farewell Tawaf (Tawaf al-Wada\') for non-residents of Makkah',
      '6. Two rakat Salah after every Tawaf',
      '7. Throwing pebbles at the three pillars on the days of sacrifice',
      '8. Shaving or shortening head-hair in Haram during the days of sacrifice',
      '9. Purity from major and minor hadath during Tawaf and Sa\'i',
      '10. Keeping away from all forbidden acts of Ihram',
      '── 12 TRADITIONS (sunnah) ──',
      '1. Ghusl/wudu for Ihram 2. White seamless garments 3. 2 rakat after Ihram intention 4. Frequent Talbiyah 5. Tawaf al-Qudum (arrival) 6. Frequent Tawaf during stay 7. Specific cloak wearing (right armpit exposed) 8. Strutting in first 3 circuits of Tawaf 9. Swift walk between green pillars during Sa\'i 10. Touching/kissing the Black Stone 11. Staying nights at Mina during days of sacrifice 12. Sacrifice by the Ifrad (Hajj-only) pilgrim',
    ],
    note: 'Missing Wuquf at Arafah invalidates the Hajj entirely — it is the very core of Hajj.',
  },
  {
    id: 'hajj-prohibited',
    chapter: 'Hajj',
    title: 'Prohibited Acts in Ihram (12 Forbidden Acts)',
    rulingType: 'haram',
    sistersRelevant: true,
    overview: 'A person in the state of Ihram must abstain from specific acts. Violations carry penalties ranging from sacrifice to charity.',
    points: [
      '1. Sexual intercourse — before Arafah: invalidates Hajj entirely (sacrifice + repeat next year). After Arafah/before shaving: sacrifice of large animal required.',
      '2. Foreplay (kissing, sensual touching) — sacrifice of small animal required',
      '3. Committing a prohibited act (sin)',
      '4. Quarrelling or cursing',
      '5. Applying fragrance or perfume to body or clothing',
      '6. Clipping nails — all nails of one hand/foot: sacrifice; individual nails: ½ sa\' of wheat per nail',
      '7. Men: wearing stitched garments (shirt, trousers, socks, etc.)',
      '8. Men: covering the head with any usual covering cloth',
      '9. Women: covering the face with cloth touching it, or wearing gloves',
      '10. Plucking or shaving hair from head, beard, armpit, or pubic area',
      '11. Applying oil to hair or body',
      '12. Killing or hunting wild land animals, or cutting plants/trees of the Haram',
      '── PENALTY CATEGORIES ──',
      'Category 1 (worst): Sexual intercourse before Arafah — Hajj invalid, sacrifice a goat, repeat Hajj next year',
      'Category 2: Intercourse after Arafah / Tawaf in major impurity — sacrifice a camel or cow',
      'Category 3: Foreplay, wearing stitched garment, shaving head, etc. — sacrifice small animal (goat)',
      'Category 4: Less than 1/4 of hair/beard, clipping 1-2 nails — ½ sa\' (1.632 kg) of wheat per violation',
      'Category 5: Killing lice/locusts — charity of any amount',
      'Category 6: Killing wild animal — price of the animal in charity, decided by 2 trustworthy assessors',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Udhiyyah (Sacrifice / Qurbani)
  // Source: Al Fiqh-ul Muyassar pp.162–166
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'qurbani-obligation',
    chapter: 'Udhiyyah',
    title: 'Udhiyyah — Ruling, Conditions & Time',
    rulingType: 'wajib',
    overview: 'Sacrifice (Udhiyyah/Qurbani) is Compulsory per Imam Abu Hanifah. It is performed on 10–12 Dhul Hijjah.',
    hadith: [
      {
        arabic: 'مَنْ وَجَدَ سَعَةً فَلَمْ يُضَحِّ فَلَا يَقْرَبَنَّ مُصَلَّانَا',
        translation: 'Whoever has the means but does not offer a sacrifice should not come near our Eidgah (Eid prayer ground).',
        source: 'Ahmad (EQ 54023)',
      },
    ],
    points: [
      '── 4 CONDITIONS FOR OBLIGATION ──',
      '1. Muslim 2. Free 3. Resident (not a traveller) 4. Wealthy (owns nisab — 595g silver value — in addition to basic needs on the days of Eid)',
      'Owning nisab for a complete year is NOT required — it is enough to own it on the days of sacrifice.',
      '── TIME OF SACRIFICE ──',
      'Starts: after dawn of 10th Dhul Hijjah (in towns: after the Eid Salah is completed)',
      'Ends: just before sunset on 12th Dhul Hijjah (3 days total)',
      'Best day: the 1st day (10th). Slaughtering in the daytime is preferred (night: permissible but makruh).',
      '── VALID ANIMALS & MINIMUM AGES ──',
      'Goat/Sheep: 1 year old (sheep >6 months if plump enough to look 1 year). Counts for 1 person only.',
      'Cow/Buffalo: 2 years old. Can be shared by up to 7 people (each share ≥ 1/7). All must intend worship.',
      'Camel: 5 years old. Same sharing rules as cow.',
      '── INVALID ANIMALS ──',
      'Blind (one or both eyes), severely lame (cannot walk to slaughter), no ear by birth, major portion of ear/tail cut, most teeth fallen, no marrow in bones (extremely lean), udder-tip cut off.',
      'Castrated and hornless (by birth) animals are permissible. Partial horn breakage is permissible unless it reaches the skull.',
    ],
  },
  {
    id: 'qurbani-distribution',
    chapter: 'Udhiyyah',
    title: 'Distribution of Qurbani Meat',
    rulingType: 'info',
    overview: 'The Sunnah method is to divide into three equal parts.',
    points: [
      '── PREFERRED DISTRIBUTION ──',
      '1/3 for the poor as charity',
      '1/3 for relatives and friends as gifts',
      '1/3 for himself and his family',
      'Giving away the entire animal is also permissible and preferable.',
      'Keeping the entire animal for family use is also permissible.',
      '── IMPORTANT RULES ──',
      'The meat of a vow-sacrifice must ALL be given to the poor — the person cannot eat any of it.',
      'The butcher CANNOT be paid from the sacrificial meat or skin — pay separately in cash.',
      'The skin may be used personally (bucket, shoes) or gifted to a wealthy person.',
      'If the skin is sold, the sale price MUST be given in charity.',
      'The sacrificer should be present at the time of slaughter. If he can slaughter himself, that is preferred.',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Funeral Rites (Janazah)
  // Source: Al Fiqh-ul Muyassar pp.113–124
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'janazah-bathing',
    chapter: 'Funeral',
    title: 'Ghusl of the Deceased — Rulings & Method',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Bathing the deceased is fard kifayah. It must be performed by the same gender, though spouses may wash each other.',
    points: [
      '── WHO WASHES WHOM ──',
      'A man should be washed by men. A woman by women. A husband may wash his wife. A wife may wash her husband. A child under the age of discernment may be washed by either gender.',
      '── METHOD ──',
      '1. Place the body on an elevated surface. Cover the awrah with a cloth.',
      '2. Perform istinja (cleansing of private areas) without looking — use a gloved/cloth-covered hand.',
      '3. Make wudu for the deceased (as in regular wudu — wash face, arms, wipe head, wash feet).',
      '4. Wash the head and beard with soap/sidr (lotus leaves) if available.',
      '5. Pour water over the right side (3 times), then the left side (3 times).',
      '6. Then wash the entire body a final time. Add camphor to the last wash.',
      '7. Women\'s hair: washed and braided into 3 plaits, placed behind the back.',
      '8. Gently press the stomach to expel any remaining contents. Wash again if needed.',
      '── WHO IS NOT WASHED ──',
      'Martyrs (shaheed — killed by disbelievers in battle): NOT washed. Buried in their clothes with their blood. No shroud, no funeral Salah is required (though it may be performed). Their blood is a witness for them.',
    ],
  },
  {
    id: 'janazah-kafan',
    chapter: 'Funeral',
    title: 'Kafan (Shroud) — Man & Woman',
    rulingType: 'fard',
    overview: 'The shroud is from the deceased\'s own wealth. If poor, it is a communal responsibility.',
    points: [
      '── MAN\'S SHROUD (3 pieces) ──',
      '1. Izaar (lower wrap): from head to below the feet',
      '2. Lifafah (outer wrap): larger than the Izaar, covers from above head to below feet',
      '3. Qamees (shirt): from neck to feet — no collar, no sleeves',
      '── WOMAN\'S SHROUD (5 pieces) ──',
      '1. Izaar (lower wrap)',
      '2. Lifafah (outer wrap)',
      '3. Qamees (shirt)',
      '4. Khimaar (head cover)',
      '5. Piece to tie around the chest',
      '── RULINGS ──',
      'White cloth is Sunnah. Any clean cloth is permissible.',
      'Perfume (musk/camphor) applied to the forehead, nose, hands, knees, and feet (prostration points).',
      'The shroud should cover the entire body — nothing exposed.',
      'Silk shroud is permissible for women but not for men (as in life).',
    ],
  },
  {
    id: 'janazah-salah',
    chapter: 'Funeral',
    title: 'Janazah Salah — The 4 Takbirs',
    rulingType: 'fard',
    sistersRelevant: true,
    overview: 'Funeral prayer is fard kifayah — a communal obligation. It consists of 4 takbirs with no ruku, no sujud.',
    points: [
      '── METHOD (4 Takbirs) ──',
      '1st Takbir: Say "Allahu Akbar" and recite Thana (Subhanakallahunma wa bihamdika...)',
      '2nd Takbir: Recite Durood Ibrahim (as in Tashahhud)',
      '3rd Takbir: Recite the Janazah dua — "Allahummaghfir lihayyina wa mayyitina, wa shahidina wa gha\'ibina, wa sagheerina wa kabeerina, wa dhakarina wa unthana. Allahumma man ahyaytahu minna fa ahyihi \'alal Islam, wa man tawaffaytahu minna fa tawaffahu \'alal Iman."',
      '4th Takbir: Tasleem — salaam to the right (and left per some scholars)',
      '── FOR A CHILD WHO DIED BEFORE PUBERTY ──',
      'Instead of the standard dua after the 3rd takbir, say: "Allahumma-j\'alhu lana faratan, waj\'alhu lana ajran wa dhukhran, waj\'alhu lana shafi\'an wa mushaffa\'an."',
      '── RULINGS ──',
      'Fard kifayah — if some perform it, the obligation is lifted from the community.',
      'No adhan or iqamah for Janazah Salah.',
      'Performed standing — no sitting or lying prayer accepted.',
      'Valid with minimum 1 Imam + 1 follower. Best: large gathering.',
      'A late-joiner who misses a takbir: says his missed takbirs at the end before the body is lifted.',
    ],
  },
  {
    id: 'janazah-burial',
    chapter: 'Funeral',
    title: 'Burial — Rulings & Etiquettes',
    rulingType: 'fard',
    overview: 'Burial should be done quickly and with dignity.',
    points: [
      'Burial should be done without delay — hastening is from the Sunnah.',
      'Muslims MUST be buried in Muslim cemeteries. Cremation is absolutely haram.',
      'The body is laid on its right side facing the Qibla in the grave.',
      'The grave should be deep enough to contain smell and protect from animals.',
      'Two types of graves: Lahd (niche cut into the side wall — preferred) and Shaq (trench in the centre).',
      'Burying at night is permissible but daytime is preferred.',
      '── GRAVE ETIQUETTES ──',
      'A simple raised mound (height of a hand-span) is sunnah. Elaborate monuments, tombstone inscriptions, and plastering are disliked.',
      'Sitting or walking on graves is strongly disliked.',
      'Recite Quran at the graveside (recommended): Surah Yaseen, the opening and closing verses of Surah Baqarah.',
      '── VISITING GRAVES ──',
      'Visiting graves is recommended. Say "Assalamu alaykum ya ahlal quboor..." (Peace be upon you, O inhabitants of the graves...).',
      'Taziyah (condolence) to the family is sunnah for 3 days. It is makruh to sit for condolence after 3 days unless the person was absent.',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Nikah (Marriage)
  // (Retained from existing content — not in the PDF)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'nikah-conditions',
    chapter: 'Nikah',
    title: 'Conditions for a Valid Nikah',
    rulingType: 'fard',
    sistersRelevant: true,
    points: [
      'Offer (Ijab) and Acceptance (Qabool) — in one sitting, in the same or near-same words',
      'Two adult Muslim male witnesses of good character (Hanafi allows female witnesses; Shafi\'i requires 2 male witnesses)',
      'Wali (guardian) — Shafi\'i/Hanbali/Maliki: wali is a pillar; without him nikah is invalid. Hanafi: an adult sane woman of free status may contract her own nikah but a wali is still strongly recommended.',
      'Mahr (dowry) — must be specified; even a small amount is valid. Must be paid to the bride — not her family.',
      'Free and genuine consent of both parties — forced marriage is haram and invalid in all madhabs',
    ],
    note: 'Islamic nikah without civil registration has no legal standing in Guyana. Register with the Registrar-General\'s Department.',
  },
  {
    id: 'nikah-mahr',
    chapter: 'Nikah',
    title: 'Mahr (Dowry)',
    rulingType: 'fard',
    sistersRelevant: true,
    points: [
      'Mahr is the wife\'s right — not a payment to the family',
      'Must be specified in the nikah contract; if omitted, mahr al-mithl (standard equivalent dowry) is assigned',
      'Minimum mahr (Hanafi): 10 Dirhams (silver) equivalent in value',
      'Prompt mahr (mu\'ajjal): paid at time of nikah. Deferred mahr (mu\'ajjal): paid on demand or upon divorce/death.',
      'A wife may waive her mahr of her own free will — but this must be genuine, not coerced',
      'Mahr is hers alone — her husband has no right to it without her consent',
    ],
  },
  {
    id: 'nikah-rights',
    chapter: 'Nikah',
    title: 'Rights and Duties in Marriage',
    rulingType: 'fard',
    sistersRelevant: true,
    points: [
      'Husband\'s duties: financial provision (nafaqah) — food, clothing, shelter according to his means; kindness, justice',
      'Wife\'s rights: mahr, provision, respectful treatment, fair sharing of time if polygamous',
      'Wife\'s duties: maintaining the home (with reasonable assistance), caring for children, allowing husband intimate access, seeking permission to leave home (Hanafi: required; other madhabs: more flexible)',
      'Neither spouse may harm the other physically, emotionally, or financially',
      'Polygamy: maximum 4 wives simultaneously, with absolute financial and time-sharing equality — if unable to be just, Quran says marry only one (Quran 4:3, 4:129)',
    ],
  },
  {
    id: 'nikah-prohibited',
    chapter: 'Nikah',
    title: 'Prohibited Marriages',
    rulingType: 'haram',
    sistersRelevant: true,
    points: [
      'Permanently prohibited (mahram relatives): mother, grandmother, daughter, granddaughter, sister, aunt, niece; foster mother and foster sister; wife\'s mother; son\'s wife; father\'s wife',
      'Temporarily prohibited: being simultaneously married to two sisters or to a woman and her aunt/niece',
      'A Muslim woman may NOT marry a non-Muslim man — consensus of all madhabs',
      'A Muslim man may marry a chaste Jewish or Christian woman — but NOT a polytheist, atheist, or woman of other religions',
      'A divorcee or widow must complete her iddah before remarrying',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Divorce
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'talaq-types',
    chapter: 'Divorce',
    title: 'Types of Talaq',
    rulingType: 'info',
    sistersRelevant: true,
    points: [
      'Talaq Raj\'i (Revocable Divorce) — 1st or 2nd divorce. Husband may revoke during iddah without a new nikah. After iddah expires without revocation, becomes irrevocable.',
      'Talaq Ba\'in Sughra (Minor Irrevocable) — divorce where iddah has passed, or divorce by khul\', or conditional divorce. Remarriage requires a new nikah contract with new mahr.',
      'Talaq Ba\'in Kubra / Mughallazah (Triple Divorce) — 3rd divorce. Marriage is permanently dissolved until the wife genuinely marries another man, that marriage is consummated, and that husband genuinely divorces her (tahleel). Arranged tahleel (halala) is haram and the nikah involved is invalid.',
      'Talaq al-Bidah (innovated — 3 in one sitting): Hanafi position: counts as final irrevocable divorce (though the act itself is sinful). This is the strictest position and most relevant to Guyana community.',
    ],
    note: 'Pronouncing talaq 3 times in one sitting is sinful and was not the practice of the Prophet ﷺ. It carries the maximum consequence. Consult a scholar before acting.',
  },
  {
    id: 'iddah',
    chapter: 'Divorce',
    title: 'Iddah (Waiting Period)',
    rulingType: 'fard',
    sistersRelevant: true,
    points: [
      'After talaq or death of husband — wife must observe iddah before remarrying',
      'Divorced woman who menstruates: 3 complete menstrual cycles (Quru\')',
      'Divorced woman who does not menstruate (post-menopausal or young): 3 calendar months',
      'Divorced pregnant woman: until she gives birth — regardless of how long this takes',
      'Widow: 4 months and 10 days (unless pregnant — then until birth)',
      'During iddah (divorced): wife remains in the marital home; husband must provide maintenance',
      'During iddah (widowed): wife must observe ihdad (mourning) — no perfume, adornment, or going out unnecessarily; may leave for necessity',
      'Iddah starts from the moment of divorce/death — not when she is informed',
    ],
    note: 'A woman in iddah may not leave the marital home except for genuine necessity (Hanafi).',
  },
  {
    id: 'khul',
    chapter: 'Divorce',
    title: 'Khul\' (Wife-Initiated Dissolution)',
    rulingType: 'info',
    sistersRelevant: true,
    points: [
      'A wife may seek dissolution of marriage by returning the mahr to her husband',
      'Valid without husband\'s willingness if taken through an Islamic court or Qadi',
      'If husband agrees: khul\' is effected immediately as one ba\'in (irrevocable) divorce',
      'Husband may not refuse khul\' if there is genuine harm or incompatibility — the Prophet ﷺ granted khul\' to the wife of Thabit ibn Qays',
      'After khul\': she observes iddah of one menstrual cycle (Hanafi) — not 3 cycles',
      'A wife cannot be pressured into returning mahr unless the khul\' is her own choice',
    ],
  },
  {
    id: 'faskh',
    chapter: 'Divorce',
    title: 'Faskh (Annulment by Court)',
    rulingType: 'info',
    sistersRelevant: true,
    points: [
      'Faskh is annulment granted by an Islamic judge (qadi) or scholarly panel',
      'Valid grounds: husband\'s impotence, husband\'s failure to provide maintenance, husband\'s prolonged unknown absence, harm or cruelty from the husband, husband\'s apostasy',
      'In Guyana: seek resolution through CIOG or GII scholars',
      'Faskh counts as one irrevocable divorce — she may remarry (including the same man with new nikah)',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Inheritance
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'inheritance-shares',
    chapter: 'Inheritance',
    title: 'Fixed Shares (Ashab al-Faraid)',
    rulingType: 'fard',
    sistersRelevant: true,
    points: [
      'Wife: 1/4 if no children; 1/8 if there are children',
      'Husband: 1/2 if no children; 1/4 if there are children',
      'Daughter: 1/2 if only daughter with no son; 2/3 if two+ daughters with no son; reduced with sons present (takes half of son\'s share — Quran 4:11)',
      'Mother: 1/3 if no children or siblings; 1/6 if children present; 1/3 of residue if husband/wife inherits',
      'Father: 1/6 if son is present; takes residue if only daughters; excluded by father\'s father only',
      'Uterine siblings (different father): 1/6 each or 1/3 shared if multiple',
      'Granddaughter: inherits as daughter if no son/daughter present; may inherit 1/6 to complete the 2/3',
    ],
    note: 'Muslim inheritance law applies to Muslims. Non-Muslims cannot inherit from a Muslim and vice versa in Islamic law. Consult a scholar or registered Islamic body for estate matters.',
  },
  {
    id: 'inheritance-blockers',
    chapter: 'Inheritance',
    title: 'What Prevents Inheritance',
    rulingType: 'info',
    sistersRelevant: true,
    points: [
      'Murder — a person who kills the deceased (intentionally) cannot inherit from them',
      'Difference of religion — a non-Muslim cannot inherit from a Muslim; a Muslim cannot inherit from a non-Muslim (under Islamic law)',
      'Slavery (not applicable today)',
      '\'Aul (proportional reduction): if the sum of all shares exceeds the estate, all shares are reduced proportionally',
      'Radd (return): if total shares are less than the estate, the excess is redistributed to heirs in proportion — excluding husband/wife (Hanafi: husband and wife excluded from radd)',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Muamalaat (Transactions & Business)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'muamalaat-trade',
    chapter: 'Muamalaat',
    title: 'Conditions for a Valid Sale',
    rulingType: 'info',
    points: [
      'Offer and acceptance (Ijab and Qabool) — verbal, written, or by clear mutual conduct',
      'The item sold must: exist, be owned by the seller, be deliverable, have a specified price',
      'The price must be known at time of sale — deferred payment is valid if amount is fixed',
      'Bay\' al-Gharar (excessive uncertainty) is invalid — do not sell "the fish still in the sea" or "the fruit not yet grown"',
      'Bay\' al-Salam (forward sale): permissible if full price paid upfront and item fully specified',
      'Both parties must transact by mutual consent — no coercion',
    ],
  },
  {
    id: 'riba',
    chapter: 'Muamalaat',
    title: 'Riba (Interest) — Strictly Prohibited',
    rulingType: 'haram',
    points: [
      'Riba is absolutely prohibited — "Allah has permitted trade and forbidden riba." (Quran 2:275)',
      'Riba al-Nasi\'ah (delay riba): charging extra for deferred payment on a loan. Bank interest, credit card interest — all fall here.',
      'Riba al-Fadl (excess riba): exchanging the same commodity in unequal amounts (e.g., 1kg gold for 1.2kg gold). Must exchange gold-for-gold hand to hand in equal amounts.',
      'A loan must be repaid in exactly the same amount — any increase stipulated is riba',
      'Conventional mortgages with interest: haram. Islamic alternatives (Murabaha, Ijara) are available from Islamic finance providers.',
      'Penalty for riba: one of the gravest major sins in Islam. "Whoever consumes riba — it is as if he has made war against Allah and His Messenger." (Quran 2:279)',
    ],
    note: 'Taking out an interest-bearing loan for genuine necessity (no Islamic alternative available, life necessity) is debated. Some scholars permit under duress. Consult a Mufti for your specific situation.',
  },
  {
    id: 'halal-business',
    chapter: 'Muamalaat',
    title: 'Halal Business Practices',
    rulingType: 'info',
    points: [
      'Honesty in weights and measures — giving short measure is a major sin (Quran 83:1–3)',
      'Prohibition of price manipulation, hoarding (ihtikaar) of necessities to drive up prices',
      'Prohibition of bribery, fraud, deception, misrepresentation of goods',
      'Prohibition of monopolistic control over necessities',
      'Bay\' al-Najash (fake bidding to inflate price) is haram',
      'Contracts must be honoured — breaking agreements without valid reason is haram',
      'Business dealings with non-Muslims are valid and permissible',
    ],
  },
  {
    id: 'qard',
    chapter: 'Muamalaat',
    title: 'Loans (Qard) and Debt',
    rulingType: 'info',
    points: [
      'Lending money without interest (Qard Hasan) is a highly recommended act of charity',
      'The borrower must repay the exact amount — any increase stipulated is riba',
      'Voluntary extra payment by the borrower (without prior agreement) is permissible and praiseworthy',
      'Document loans in writing — Quran 2:282 commands writing debts',
      'Dying with unpaid debt is a serious matter — the Prophet ﷺ refused to lead janazah for the indebted until debt was settled by others',
      'The debtor must prioritise repayment; the lender should give grace to those in difficulty (Quran 2:280)',
    ],
  },
  {
    id: 'employment',
    chapter: 'Muamalaat',
    title: 'Employment Rights in Islam',
    rulingType: 'info',
    points: [
      'Worker\'s wage must be agreed before the work begins — "Pay the worker his wages before his sweat dries." (Ibn Majah)',
      'An employee must perform the agreed work faithfully — theft and shirking from work is haram',
      'An employer must not overwork an employee beyond their capacity',
      'Taking a wage for haram work (interest banking, selling alcohol) is not permissible',
      'Business partnerships (Musharakah) are valid — profit shared by agreed ratio; loss shared by capital ratio',
    ],
  },
  {
    id: 'waqf',
    chapter: 'Muamalaat',
    title: 'Waqf (Endowment)',
    rulingType: 'info',
    points: [
      'Waqf: dedicating an asset perpetually for charitable/Islamic purposes — it cannot be sold, inherited, or given away',
      'Examples: masjid land, Islamic school buildings, wells, medical facilities',
      'The founder specifies the purpose and conditions — must be a permissible Islamic purpose',
      'Income from the waqf property is used for the specified purpose',
      'Sadaqah Jariyah — continuous charity whose reward continues after death (Waqf is a classic form)',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Halal & Haram
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'halal-food',
    chapter: 'Halal & Haram',
    title: 'Halal and Haram Food',
    rulingType: 'haram',
    points: [
      'Animals that are halal to eat: cattle (cow, buffalo), sheep, goat, camel, chicken, turkey, duck, deer, rabbit, fish (all types per Shafi\'i/Hanbali; only scaled fish per Hanafi)',
      'Seafood: Hanafi — only fish (with scales) are halal; other sea creatures (shrimp, lobster, crab, oysters) are makruh or haram. Shafi\'i/Maliki — all seafood is halal.',
      'Haram animals: pig (all its by-products), blood, carrion (dead without proper slaughter), donkey, mule, every beast of prey with fangs (lion, wolf, dog, cat), every bird of prey with talons (eagle, vulture), rats, insects (except locusts — halal)',
      'Alcohol is haram to consume, trade, or handle with the intention of selling for drinking',
    ],
  },
  {
    id: 'slaughter',
    chapter: 'Halal & Haram',
    title: 'Islamic Slaughter (Dhabh)',
    rulingType: 'fard',
    points: [
      'Conditions for halal slaughter: Muslim (or Jewish/Christian) slaughterer, Bismillah said at time of slaughter, cut the jugular vein/windpipe/oesophagus in one swift motion, animal must be alive at time of slaughter, blood must flow out',
      'Machine slaughter: halal if a Muslim says Bismillah continuously, the blade is sharp, and each animal is individually slaughtered (debate exists for large-scale poultry lines)',
      'Stunning before slaughter: permissible only if stunning does not kill the animal before slaughter (Hanafi/Maliki consensus)',
      'Meat from non-Muslim countries: check for proper halal certification from a recognised authority',
      'In Guyana: GHA, CIOG, and D.E.H.C. are recognised halal certifying bodies',
    ],
  },
  {
    id: 'haram-ingredients',
    chapter: 'Halal & Haram',
    title: 'Hidden Haram Ingredients',
    rulingType: 'haram',
    points: [
      'Gelatin: haram if from pig or non-halal animal; halal if from fish or halal-slaughtered animal. Avoid if source unspecified.',
      'Lard and shortening: from pork fat — check labels on baked goods',
      'Carmine / cochineal (E120): red colouring from beetles — haram (Hanafi); some scholars permit',
      'Rennet: halal if microbial/plant-based; potentially haram if from pig stomach lining',
      'Alcohol in flavourings and vanilla extract: Hanafi — small trace amounts in food (not intoxicating) are tolerated by some scholars; stricter position: avoid. Shafi\'i: stricter.',
      'L-Cysteine (E920): often derived from human hair or pig bristle — in commercial bread; check source',
      'Mono and diglycerides (E471): can be pork-derived — animal source must be specified as halal',
    ],
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Women's Fiqh
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'hayd',
    chapter: "Women's Fiqh",
    title: 'Hayd (Menstruation) — Rules',
    rulingType: 'fard',
    sistersRelevant: true,
    points: [
      'Minimum duration: 3 days (Hanafi); 1 day + 1 night (Shafi\'i)',
      'Maximum duration: 10 days (Hanafi); 15 days (Shafi\'i)',
      'Colours of hayd blood: black, red, brown, yellow, green — all count as hayd during the hayd days',
      'Clean (tuhr) period between two cycles: minimum 15 days per all madhabs',
      'FORBIDDEN during hayd: Salah (do not make qada — obligation lifted), fasting Ramadan (MUST make qada), sexual intercourse (haram — kaffarah if done deliberately), Tawaf, entering the masjid (Hanafi: forbidden; Shafi\'i: passing through briefly permitted), reciting Quran from memory (Hanafi: forbidden; Shafi\'i: permitted without touching mushaf), touching the physical mushaf',
      'PERMITTED during hayd: all dhikr, dua, listening to Quran, reading Quranic translations/tafseer, Islamic books, charity, istighfar, teaching, learning',
      'When hayd ends: make ghusl immediately and resume prayers. Do not delay.',
    ],
    note: 'If blood continues beyond the maximum (10 days Hanafi), it becomes istihadah — irregular bleeding. Resume salah on day 11.',
  },
  {
    id: 'nifas',
    chapter: "Women's Fiqh",
    title: 'Nifas (Post-Natal Bleeding)',
    rulingType: 'fard',
    sistersRelevant: true,
    points: [
      'Nifas is bleeding after childbirth',
      'Maximum duration: 40 days (Hanafi/Hanbali); 60 days (Shafi\'i/Maliki)',
      'Minimum: no minimum — some women stop in days. When it stops, make ghusl and resume ibadah.',
      'Rulings: same as hayd — no Salah, no fasting, no intercourse until ghusl is made',
      'Missed Ramadan fasts during nifas: must be made up',
      'Missed Salah during nifas: NOT made up',
      'If bleeding stops before 40 days: make ghusl and resume immediately. Do not wait for 40 days.',
    ],
  },
  {
    id: 'istihadah',
    chapter: "Women's Fiqh",
    title: 'Istihadah (Irregular/Abnormal Bleeding)',
    rulingType: 'info',
    sistersRelevant: true,
    points: [
      'Istihadah is bleeding outside the hayd or nifas period — it is NOT hayd. It is treated as an ongoing impurity (like a nosebleed).',
      'A woman in istihadah: MUST continue Salah and fasting. She is not exempt from any ibadah.',
      'She makes a fresh wudu for each fard Salah — the bleeding invalidates wudu but not more.',
      'She washes and uses a pad/cloth to prevent spreading of impurity, makes wudu, and prays.',
      'How to identify hayd vs istihadah: use her established pattern (habit/\'adah). If bleeding exceeds her normal cycle length or exceeds 10 days (Hanafi), the extra is istihadah.',
      'A new Muslim woman or young girl without established pattern: if blood continues beyond 10 days (Hanafi), the excess is istihadah.',
    ],
    note: 'Istihadah is one of the more complex areas of women\'s fiqh. Consult a female scholar or Mufti if you are unsure whether your situation is hayd or istihadah.',
  },
  {
    id: 'women-ghusl',
    chapter: "Women's Fiqh",
    title: 'Ghusl After Hayd/Nifas — Step by Step',
    rulingType: 'fard',
    sistersRelevant: true,
    points: [
      'Make intention (niyyah) for ghusl from hayd/nifas',
      'Remove any barrier from the skin: nail polish, acrylic nails, wax, dried paint, thick cream',
      'Wash both hands first',
      'Wash away any impurity (blood) from the body',
      'Perform full wudu (rinse mouth, sniff water into nose, wash face, arms, wipe head, wash feet)',
      'Pour water over entire body 3 times — start with right side, then left',
      'Ensure every part of the body is wet — hairline, behind ears, under arms, between fingers and toes, navel, backs of knees',
      'For women with thick or braided hair: Hanafi — water must reach the roots of the hair, but unbraiding is NOT required if water can reach roots. If in doubt, unbraid.',
      'After ghusl: put on clean clothes and resume Salah',
    ],
  },
  {
    id: 'women-quran',
    chapter: "Women's Fiqh",
    title: 'Women and the Quran During Hayd',
    rulingType: 'info',
    sistersRelevant: true,
    points: [
      'Touching the physical Mushaf (Quran): FORBIDDEN during hayd — by consensus of all 4 madhabs',
      'Reciting Quran from memory (without a purpose other than recitation): Hanafi — forbidden; Shafi\'i/Maliki — permitted without touching mushaf',
      'Reading Quran from phone/screen: Hanafi scholars differ — many permit since a phone is not a mushaf; check with a local scholar',
      'Reciting for the purpose of dua (e.g., Ayat al-Kursi for protection, Surah Fatiha as dua): Hanafi — permitted if intended as dua, not recitation',
      'Listening to Quran recitation: FULLY PERMITTED — all madhabs',
      'Reading translation/tafseer: PERMITTED — all madhabs',
    ],
    note: 'The safest position (Hanafi): refrain from reciting Quran from memory during hayd. Use the time for dhikr, dua, and listening.',
  },

  // ════════════════════════════════════════════════════════════════════════════
  // CHAPTER: Common Questions (Q&A)
  // ════════════════════════════════════════════════════════════════════════════
  {
    id: 'faq-prayer-english',
    chapter: 'Q&A',
    title: 'Can I pray in English?',
    rulingType: 'info',
    points: [
      'The fard recitation of al-Fatihah and all dhikr within Salah must be in Arabic — consensus of all madhabs',
      'If a new Muslim genuinely cannot learn Arabic yet (Hanafi): may recite the meaning temporarily, but must learn Arabic as soon as possible',
      'Personal dua (supplication) in sujud and after Salah: any language is valid',
      'Niyyah (intention) is a matter of the heart — may be in any language',
    ],
  },
  {
    id: 'faq-sitting',
    chapter: 'Q&A',
    title: 'Can I pray sitting if I cannot stand?',
    rulingType: 'info',
    points: [
      'Yes — standing is waived if it causes genuine harm or is impossible',
      'Pray as much of the salah correctly as possible; indicate ruku and sujud with head movements if unable (sujud deeper than ruku)',
      'If unable to sit: pray lying on the right side facing Qibla',
      'Full reward applies — Allah does not burden a soul beyond its capacity',
      '"Pray standing; if unable, sitting; if unable, on your side." (Bukhari)',
    ],
  },
  {
    id: 'faq-combining',
    chapter: 'Q&A',
    title: 'Can I combine prayers?',
    rulingType: 'info',
    points: [
      'Combining prayers (Jam\'): Hanafi — NOT generally permitted except during Hajj (Arafah and Muzdalifah only)',
      'Shafi\'i/Maliki/Hanbali: permitted during travel, rain, illness (specific conditions apply)',
      'Qasr (shortening 4-rakat prayers to 2): permitted during travel of 77+ km by all madhabs',
      'Hanafi position on combining is the stricter position followed in Guyana',
    ],
  },
  {
    id: 'faq-makeup-years',
    chapter: 'Q&A',
    title: 'I have years of missed prayers — what do I do?',
    rulingType: 'fard',
    points: [
      'All missed fard prayers are a debt to Allah — they must be made up',
      'Begin immediately — do not delay. Even praying 1 extra qada per day is a start.',
      'The most practical method: after every fard salah, pray the same fard salah as qada for the oldest debt',
      'You do NOT need to know the exact number — estimate generously and continue making it up',
      'Allah is the Most Merciful — sincere repentance + consistent effort is the path',
      'Dying with missed prayers is a serious concern — make it a priority before death',
    ],
  },
  {
    id: 'faq-witr-optional',
    chapter: 'Q&A',
    title: 'Is Witr optional?',
    rulingType: 'wajib',
    points: [
      'Hanafi: Witr is Wajib — between Fard and Sunnah in level of obligation. Never call it optional.',
      'Shafi\'i/Maliki/Hanbali: Sunnah Mu\'akkadah — highly emphasised, almost obligatory in practice',
      'The Prophet ﷺ never once left Witr — travelling or at home. This alone tells you its importance.',
      '"Make Witr the last of your night prayers." (Bukhari, Muslim)',
    ],
  },
  {
    id: 'faq-beard',
    chapter: 'Q&A',
    title: 'Ruling on growing the beard',
    rulingType: 'wajib',
    points: [
      'Growing the beard: Wajib (Hanafi/Maliki/Hanbali); Sunnah Mu\'akkadah (Shafi\'i)',
      'Minimum length: one fist-length — shaving or trimming below this is haram (Hanafi)',
      'Trimming to exactly one fist-length is permitted; keeping it longer is mustahabb',
      '"Trim the moustache and let the beard grow, be different from the polytheists." (Bukhari, Muslim)',
    ],
  },
]
