export interface NawawiHadith {
  number: number
  title: string
  category: 'faith' | 'intention' | 'halal-haram' | 'character' | 'community' | 'worship'
  arabic: string
  transliteration: string
  translation: string
  commentary: string
  source: string
}

export const NAWAWI_HADITH: NawawiHadith[] = [
  {
    number: 1,
    title: 'Actions Are By Intentions',
    category: 'intention',
    arabic: 'إِنَّمَا الأَعْمَالُ بِالنِّيَّاتِ وَإِنَّمَا لِكُلِّ امْرِئٍ مَا نَوَى فَمَنْ كَانَتْ هِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ فَهِجْرَتُهُ إِلَى اللَّهِ وَرَسُولِهِ وَمَنْ كَانَتْ هِجْرَتُهُ لِدُنْيَا يُصِيبُهَا أَوْ امْرَأَةٍ يَنْكِحُهَا فَهِجْرَتُهُ إِلَى مَا هَاجَرَ إِلَيْهِ',
    transliteration: "Innamal a'malu bin-niyyat, wa innama likulli imri'in ma nawa. Faman kanat hijratuhu ilallahi wa rasulihi, fahijratuhu ilallahi wa rasulih. Wa man kanat hijratuhu li-dunya yuseebuha aw imra'atin yankihuha, fahijratuhu ila ma hajara ilayh.",
    translation: 'Actions are judged by intentions, and every person will have only what they intended. So whoever emigrated for the sake of Allah and His Messenger, then his emigration was for Allah and His Messenger. And whoever emigrated for worldly gain or to marry a woman, then his emigration was for whatever he emigrated for.',
    commentary: 'This is one of the most fundamental principles in Islam. Every act of worship, from prayer to business dealings, is weighed by the intention behind it. Imam Shafi\'i said this hadith constitutes one-third of all knowledge.',
    source: 'Bukhari 1, Muslim 1907',
  },
  {
    number: 2,
    title: "Islam, Iman, Ihsan — Jibreel's Hadith",
    category: 'faith',
    arabic: 'أَخْبِرْنِي عَنِ الإِسْلامِ قَالَ الإِسْلامُ أَنْ تَشْهَدَ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ وَتُقِيمَ الصَّلاةَ وَتُؤْتِيَ الزَّكَاةَ وَتَصُومَ رَمَضَانَ وَتَحُجَّ الْبَيْتَ إِنِ اسْتَطَعْتَ إِلَيْهِ سَبِيلًا',
    transliteration: "Akhbirni 'anil-Islam. Qala: Al-Islamu an tashhada an la ilaha illallahu wa anna Muhammadan rasulullah, wa tuqimas-salah, wa tu'tiyaz-zakah, wa tasuma Ramadan, wa tahujjal-bayta inistata'ta ilayhi sabila.",
    translation: 'Tell me about Islam. He said: Islam is to testify that there is no god but Allah and that Muhammad is the Messenger of Allah, to establish prayer, pay zakat, fast Ramadan, and make pilgrimage to the House if you are able.',
    commentary: 'This hadith defines the three levels of the religion: submission (Islam), faith (Iman), and excellence (Ihsan). Jibreel appeared as a man to ask the Prophet these questions in front of the Companions to teach them the foundations of the religion.',
    source: 'Muslim 8',
  },
  {
    number: 3,
    title: 'The Five Pillars of Islam',
    category: 'faith',
    arabic: 'بُنِيَ الإِسْلامُ عَلَى خَمْسٍ شَهَادَةِ أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ وَإِقَامِ الصَّلاةِ وَإِيتَاءِ الزَّكَاةِ وَحَجِّ الْبَيْتِ وَصَوْمِ رَمَضَانَ',
    transliteration: "Buniyul-Islamu 'ala khams: shahadati an la ilaha illallahu wa anna Muhammadan rasulullah, wa iqamis-salah, wa ita'iz-zakah, wa hajjil-bayt, wa sawmi Ramadan.",
    translation: 'Islam is built upon five: testifying that there is no god but Allah and that Muhammad is the Messenger of Allah, establishing prayer, paying zakat, pilgrimage to the House, and fasting Ramadan.',
    commentary: 'These five pillars are the foundation of a Muslim\'s practice. Without them, the structure of one\'s faith is incomplete. Every Muslim is obligated to fulfill these to the best of their ability.',
    source: 'Bukhari 8, Muslim 16',
  },
  {
    number: 4,
    title: 'Stages of Creation',
    category: 'faith',
    arabic: 'إِنَّ أَحَدَكُمْ يُجْمَعُ خَلْقُهُ فِي بَطْنِ أُمِّهِ أَرْبَعِينَ يَوْمًا نُطْفَةً ثُمَّ يَكُونُ عَلَقَةً مِثْلَ ذَلِكَ ثُمَّ يَكُونُ مُضْغَةً مِثْلَ ذَلِكَ ثُمَّ يُرْسَلُ إِلَيْهِ الْمَلَكُ فَيَنْفُخُ فِيهِ الرُّوحَ',
    transliteration: "Inna ahadakum yujma'u khalquhu fi batni ummihi arba'eena yawman nutfatan, thumma yakunu 'alaqatan mithla dhalik, thumma yakunu mudghatan mithla dhalik, thumma yursalu ilayhil-malaku fa-yanfukhu fihir-ruh.",
    translation: 'Each one of you is constituted in the womb of the mother for forty days as a drop, then it becomes a clot for a similar period, then it becomes a morsel for a similar period, then the angel is sent and he breathes the soul into it.',
    commentary: 'This hadith teaches us about divine decree (qadar). The angel writes four things: provision, lifespan, deeds, and whether the person will be blessed or wretched. Yet this does not negate free will — we must still strive.',
    source: 'Bukhari 3208, Muslim 2643',
  },
  {
    number: 5,
    title: 'Rejection of Innovation',
    category: 'faith',
    arabic: 'مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ مِنْهُ فَهُوَ رَدٌّ',
    transliteration: "Man ahdatha fi amrina hadha ma laysa minhu fahuwa radd.",
    translation: 'Whoever introduces into this affair of ours something that does not belong to it, it is rejected.',
    commentary: 'This is a foundational principle for the preservation of Islamic practice. Innovations in worship (bid\'ah) that have no basis in the Quran or Sunnah are rejected. This applies to matters of worship, not worldly inventions.',
    source: 'Bukhari 2697, Muslim 1718',
  },
  {
    number: 6,
    title: 'The Halal and Haram Are Clear',
    category: 'halal-haram',
    arabic: 'إِنَّ الْحَلالَ بَيِّنٌ وَإِنَّ الْحَرَامَ بَيِّنٌ وَبَيْنَهُمَا أُمُورٌ مُشْتَبِهَاتٌ لَا يَعْلَمُهُنَّ كَثِيرٌ مِنَ النَّاسِ فَمَنِ اتَّقَى الشُّبُهَاتِ فَقَدِ اسْتَبْرَأَ لِدِينِهِ وَعِرْضِهِ',
    transliteration: "Innal-halala bayyinun wa innal-harama bayyinun wa baynahuma umurun mushtabihatun la ya'lamuhunna katheerun minan-nas. Famanittaqash-shubuhat faqadistabra'a li-deenihi wa 'irdihi.",
    translation: 'The halal is clear and the haram is clear, and between them are doubtful matters that many people do not know. Whoever avoids the doubtful matters has safeguarded his religion and his honour.',
    commentary: 'This hadith establishes the principle of being cautious about doubtful matters. Like a shepherd who grazes near a boundary risks his flock entering it, a Muslim should keep a safe distance from the haram.',
    source: 'Bukhari 52, Muslim 1599',
  },
  {
    number: 7,
    title: 'Sincerity in Religion',
    category: 'community',
    arabic: 'الدِّينُ النَّصِيحَةُ قُلْنَا لِمَنْ قَالَ لِلَّهِ وَلِكِتَابِهِ وَلِرَسُولِهِ وَلأَئِمَّةِ الْمُسْلِمِينَ وَعَامَّتِهِمْ',
    transliteration: "Ad-deenu an-naseeha. Qulna: liman? Qala: lillahi wa likitabihi wa lirasoolihi wa li-a'immatil-muslimeena wa 'ammatihim.",
    translation: 'The religion is sincere counsel. We said: To whom? He said: To Allah, His Book, His Messenger, the leaders of the Muslims, and their common folk.',
    commentary: 'Nasihah (sincere counsel) is the foundation of community. It means being sincere in worship to Allah, following the Quran, emulating the Prophet, supporting just leaders, and advising fellow Muslims with kindness.',
    source: 'Muslim 55',
  },
  {
    number: 8,
    title: 'Sanctity of a Muslim',
    category: 'community',
    arabic: 'أُمِرْتُ أَنْ أُقَاتِلَ النَّاسَ حَتَّى يَشْهَدُوا أَنْ لَا إِلَهَ إِلَّا اللَّهُ وَأَنَّ مُحَمَّدًا رَسُولُ اللَّهِ وَيُقِيمُوا الصَّلاةَ وَيُؤْتُوا الزَّكَاةَ فَإِذَا فَعَلُوا ذَلِكَ عَصَمُوا مِنِّي دِمَاءَهُمْ وَأَمْوَالَهُمْ إِلَّا بِحَقِّ الإِسْلامِ وَحِسَابُهُمْ عَلَى اللَّهِ تَعَالَى',
    transliteration: "Umirtu an uqatilan-nasa hatta yashhadu an la ilaha illallah wa anna Muhammadan rasulullah, wa yuqeemus-salah, wa yu'tuz-zakah. Fa idha fa'alu dhalika 'asamu minni dima'ahum wa amwalahum illa bihaqil-Islam, wa hisabuhum 'alallahi ta'ala.",
    translation: 'I have been commanded to fight people until they testify that there is no god but Allah and that Muhammad is the Messenger of Allah, establish prayer, and pay zakat. If they do that, their blood and wealth are protected from me, except by right of Islam, and their account is with Allah.',
    commentary: 'This hadith establishes the inviolability of a Muslim\'s life, property, and honour. Once a person enters Islam, they are protected. Their inner sincerity is between them and Allah — we judge only by what is apparent.',
    source: 'Bukhari 25, Muslim 22',
  },
  {
    number: 9,
    title: 'Avoid What Is Beyond You',
    category: 'worship',
    arabic: 'مَا نَهَيْتُكُمْ عَنْهُ فَاجْتَنِبُوهُ وَمَا أَمَرْتُكُمْ بِهِ فَأْتُوا مِنْهُ مَا اسْتَطَعْتُمْ فَإِنَّمَا أَهْلَكَ الَّذِينَ مِنْ قَبْلِكُمْ كَثْرَةُ مَسَائِلِهِمْ وَاخْتِلافُهُمْ عَلَى أَنْبِيَائِهِمْ',
    transliteration: "Ma nahaytukum 'anhu fajtanibuhu wa ma amartukum bihi fa'tu minhu mastata'tum. Fa-innama ahlaka alladheena min qablikum kathratu masa'ilihim wakhilafuhum 'ala anbiya'ihim.",
    translation: 'What I have forbidden you from, avoid it. And what I have commanded you to do, do as much of it as you can. For those before you were destroyed by their excessive questioning and their disagreement with their prophets.',
    commentary: 'Islam is practical — prohibitions must be avoided entirely, but obligations are according to one\'s capacity. This hadith also warns against asking unnecessary questions about religion that lead to division.',
    source: 'Bukhari 7288, Muslim 1337',
  },
  {
    number: 10,
    title: 'Allah Accepts Only the Pure',
    category: 'halal-haram',
    arabic: 'إِنَّ اللَّهَ طَيِّبٌ لَا يَقْبَلُ إِلَّا طَيِّبًا وَإِنَّ اللَّهَ أَمَرَ الْمُؤْمِنِينَ بِمَا أَمَرَ بِهِ الْمُرْسَلِينَ',
    transliteration: "Innallaha tayyibun la yaqbalu illa tayyiban, wa innallaha amaral-mu'mineena bima amara bihil-mursaleen.",
    translation: 'Indeed Allah is pure and accepts only what is pure. And Allah has commanded the believers with what He commanded the messengers.',
    commentary: 'Eating halal and pure food is essential for one\'s dua to be accepted. The Prophet described a man who eats haram, drinks haram, and wears haram — how can his dua be answered? This emphasizes that halal income is a condition for accepted worship.',
    source: 'Muslim 1015',
  },
  {
    number: 11,
    title: 'Leave What Makes You Doubt',
    category: 'halal-haram',
    arabic: 'دَعْ مَا يَرِيبُكَ إِلَى مَا لَا يَرِيبُكَ',
    transliteration: "Da' ma yareebuka ila ma la yareebuk.",
    translation: 'Leave what makes you doubt for what does not make you doubt.',
    commentary: 'When you are unsure whether something is halal or haram, choose the safer option. This is a practical application of taqwa (God-consciousness) in daily life. A pure heart recognizes what is wholesome.',
    source: 'Tirmidhi 2518, Nasa\'i 5711',
  },
  {
    number: 12,
    title: 'Leave What Does Not Concern You',
    category: 'character',
    arabic: 'مِنْ حُسْنِ إِسْلامِ الْمَرْءِ تَرْكُهُ مَا لَا يَعْنِيهِ',
    transliteration: "Min husni islamil-mar'i tarkuhu ma la ya'neeh.",
    translation: 'Part of the perfection of a person\'s Islam is leaving that which does not concern him.',
    commentary: 'This hadith is a comprehensive guide to minding one\'s own affairs. It includes speech, actions, and even thoughts. A Muslim who focuses on what benefits them in their deen and dunya will find peace.',
    source: 'Tirmidhi 2317',
  },
  {
    number: 13,
    title: 'Love for Your Brother',
    category: 'community',
    arabic: 'لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ',
    transliteration: "La yu'minu ahadukum hatta yuhibba li-akheehi ma yuhibbu linafsihi.",
    translation: 'None of you truly believes until he loves for his brother what he loves for himself.',
    commentary: 'True faith is demonstrated through care for others. This applies to both worldly and religious matters — wanting guidance, provision, and well-being for others as you want it for yourself.',
    source: 'Bukhari 13, Muslim 45',
  },
  {
    number: 14,
    title: 'When Blood Is Lawful',
    category: 'halal-haram',
    arabic: 'لَا يَحِلُّ دَمُ امْرِئٍ مُسْلِمٍ إِلَّا بِإِحْدَى ثَلاثٍ الثَّيِّبُ الزَّانِي وَالنَّفْسُ بِالنَّفْسِ وَالتَّارِكُ لِدِينِهِ الْمُفَارِقُ لِلْجَمَاعَةِ',
    transliteration: "La yahillu damu imri'in Muslimin illa bi-ihda thalath: ath-thayyibuz-zani, wan-nafsu bin-nafsi, wat-tariku li-deenihil-mufariqu lil-jama'ah.",
    translation: 'The blood of a Muslim is not lawful except in three cases: the married adulterer, a life for a life, and one who forsakes his religion and separates from the community.',
    commentary: 'This hadith establishes the sanctity of Muslim life and the very limited circumstances under which capital punishment may be applied — and only by a legitimate Islamic authority, never by individuals.',
    source: 'Bukhari 6878, Muslim 1676',
  },
  {
    number: 15,
    title: 'Good Speech and Hospitality',
    category: 'character',
    arabic: 'مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ جَارَهُ وَمَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الآخِرِ فَلْيُكْرِمْ ضَيْفَهُ',
    transliteration: "Man kana yu'minu billahi wal-yawmil-akhiri falyaqul khayran aw liyasmut. Wa man kana yu'minu billahi wal-yawmil-akhiri falyukrim jarahu. Wa man kana yu'minu billahi wal-yawmil-akhiri falyukrim dayfah.",
    translation: 'Whoever believes in Allah and the Last Day, let him speak good or remain silent. Whoever believes in Allah and the Last Day, let him honour his neighbour. Whoever believes in Allah and the Last Day, let him honour his guest.',
    commentary: 'Three practical principles of faith: guard your tongue, be good to your neighbours, and be generous to your guests. In Guyana, hospitality is deeply valued — this hadith affirms that as an act of faith.',
    source: 'Bukhari 6018, Muslim 47',
  },
  {
    number: 16,
    title: 'Do Not Get Angry',
    category: 'character',
    arabic: 'لَا تَغْضَبْ فَرَدَّدَ مِرَارًا قَالَ لَا تَغْضَبْ',
    transliteration: "La taghdhab. Fa-raddada miraran, qala: la taghdhab.",
    translation: 'Do not get angry. He repeated it several times, saying: Do not get angry.',
    commentary: 'A man asked the Prophet for concise advice, and this was the repeated answer. Anger leads to many sins — harsh words, broken relationships, unjust actions. Controlling anger is a mark of true strength.',
    source: 'Bukhari 6116',
  },
  {
    number: 17,
    title: 'Excellence in All Things',
    category: 'character',
    arabic: 'إِنَّ اللَّهَ كَتَبَ الإِحْسَانَ عَلَى كُلِّ شَيْءٍ فَإِذَا قَتَلْتُمْ فَأَحْسِنُوا الْقِتْلَةَ وَإِذَا ذَبَحْتُمْ فَأَحْسِنُوا الذِّبْحَةَ وَلْيُحِدَّ أَحَدُكُمْ شَفْرَتَهُ وَلْيُرِحْ ذَبِيحَتَهُ',
    transliteration: "Innallaha katabal-ihsana 'ala kulli shay'. Fa-idha qataltum fa-ahsinul-qitla, wa idha dhabahtum fa-ahsinudh-dhibha. Walyuhidda ahadukum shafratihi walyurih dhabeehatah.",
    translation: 'Allah has prescribed excellence in all things. When you kill, kill well; and when you slaughter, slaughter well. Let one of you sharpen his blade and spare his animal suffering.',
    commentary: 'Ihsan (excellence) applies to everything — not just worship, but even in how we treat animals. Islam demands mercy and proficiency in every action. This is the basis of halal slaughter (dhabihah).',
    source: 'Muslim 1955',
  },
  {
    number: 18,
    title: 'Fear Allah Wherever You Are',
    category: 'character',
    arabic: 'اتَّقِ اللَّهِ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا وَخَالِقِ النَّاسَ بِخُلُقٍ حَسَنٍ',
    transliteration: "Ittaqillaha haythuma kunta, wa atbi'is-sayyi'atal-hasanata tamhuha, wa khaliqin-nasa bi-khuluqin hasan.",
    translation: 'Fear Allah wherever you are, follow a bad deed with a good one and it will erase it, and behave well towards people.',
    commentary: 'Three comprehensive pieces of advice: maintain God-consciousness everywhere (not just in the mosque), seek redemption through good deeds, and treat people with excellent character. This is the complete lifestyle of a Muslim.',
    source: 'Tirmidhi 1987',
  },
  {
    number: 19,
    title: 'Be Mindful of Allah',
    category: 'faith',
    arabic: 'احْفَظِ اللَّهَ يَحْفَظْكَ احْفَظِ اللَّهَ تَجِدْهُ تُجَاهَكَ إِذَا سَأَلْتَ فَاسْأَلِ اللَّهَ وَإِذَا اسْتَعَنْتَ فَاسْتَعِنْ بِاللَّهِ',
    transliteration: "Ihfadhillaha yahfadhk. Ihfadhillaha tajidhu tujahak. Idha sa'alta fas'alillah, wa idha ista'anta fasta'in billah.",
    translation: 'Be mindful of Allah and He will protect you. Be mindful of Allah and you will find Him before you. If you ask, ask Allah. If you seek help, seek help from Allah.',
    commentary: 'This is the Prophet\'s advice to the young Ibn Abbas. It teaches complete reliance on Allah (tawakkul). Even if the whole world united to benefit or harm you, they could not do so except by Allah\'s will.',
    source: 'Tirmidhi 2516',
  },
  {
    number: 20,
    title: 'Modesty',
    category: 'character',
    arabic: 'إِنَّ مِمَّا أَدْرَكَ النَّاسُ مِنْ كَلامِ النُّبُوَّةِ الأُولَى إِذَا لَمْ تَسْتَحْيِ فَاصْنَعْ مَا شِئْتَ',
    transliteration: "Inna mimma adrakun-nasu min kalamun-nubuwwatil-ula: idha lam tastahi fasna' ma shi't.",
    translation: 'Among what people have preserved from the words of the early prophets is: If you have no shame, then do as you wish.',
    commentary: 'Haya (modesty/shame) is a branch of faith. It is the internal compass that prevents a person from committing sins. When a person loses haya, there is no barrier between them and wrongdoing.',
    source: 'Bukhari 3483',
  },
  {
    number: 21,
    title: 'Say "I Believe in Allah" and Be Steadfast',
    category: 'faith',
    arabic: 'قُلْ آمَنْتُ بِاللَّهِ ثُمَّ اسْتَقِمْ',
    transliteration: "Qul amantu billahi thumma-staqim.",
    translation: 'Say "I believe in Allah" and then be steadfast.',
    commentary: 'Istiqamah (steadfastness) is the essence of Islam after belief. It means consistently following the straight path — in good times and bad, in public and private. The Prophet said this is the most comprehensive advice.',
    source: 'Muslim 38',
  },
  {
    number: 22,
    title: 'Do What Is Obligatory to Enter Paradise',
    category: 'worship',
    arabic: 'أَرَأَيْتَ إِذَا صَلَّيْتُ الْمَكْتُوبَاتِ وَصُمْتُ رَمَضَانَ وَأَحْلَلْتُ الْحَلالَ وَحَرَّمْتُ الْحَرَامَ وَلَمْ أَزِدْ عَلَى ذَلِكَ شَيْئًا أَأَدْخُلُ الْجَنَّةَ قَالَ نَعَمْ',
    transliteration: "Ara'ayta idha sallaytul-maktubat wa sumtu Ramadan wa ahlaltul-halal wa harramtul-haram wa lam azid 'ala dhalika shay'an a-adkhulul-janna? Qala: na'am.",
    translation: 'Do you think if I pray the obligatory prayers, fast Ramadan, treat the halal as lawful and the haram as forbidden, and do nothing more than that — will I enter Paradise? He said: Yes.',
    commentary: 'Islam does not demand the impossible. Fulfilling the obligations and avoiding the prohibited is sufficient for Paradise. Additional voluntary acts increase one\'s rank but are not required.',
    source: 'Muslim 15',
  },
  {
    number: 23,
    title: 'Purity Is Half of Faith',
    category: 'worship',
    arabic: 'الطُّهُورُ شَطْرُ الإِيمَانِ وَالْحَمْدُ لِلَّهِ تَمْلأُ الْمِيزَانَ وَسُبْحَانَ اللَّهِ وَالْحَمْدُ لِلَّهِ تَمْلآنِ أَوْ تَمْلأُ مَا بَيْنَ السَّمَاوَاتِ وَالأَرْضِ',
    transliteration: "At-tuhuru shatrul-iman, walhamdu lillahi tamla'ul-mizan, wa subhanallahi walhamdu lillahi tamla'ani aw tamla'u ma baynas-samawati wal-ard.",
    translation: 'Purity is half of faith. Alhamdulillah fills the scales. SubhanAllah and Alhamdulillah fill — or fill up — what is between the heavens and the earth.',
    commentary: 'Physical and spiritual purity go hand in hand. Wudu and ghusl are not just rituals but a means of spiritual elevation. The simple words of dhikr carry immense weight on the Day of Judgement.',
    source: 'Muslim 223',
  },
  {
    number: 24,
    title: 'Allah Has Forbidden Oppression',
    category: 'character',
    arabic: 'يَا عِبَادِي إِنِّي حَرَّمْتُ الظُّلْمَ عَلَى نَفْسِي وَجَعَلْتُهُ بَيْنَكُمْ مُحَرَّمًا فَلَا تَظَالَمُوا',
    transliteration: "Ya 'ibadi inni harramtudh-dhulma 'ala nafsi wa ja'altuhu baynakum muharraman fala tadhalamu.",
    translation: 'O My servants, I have forbidden oppression for Myself and have made it forbidden among you, so do not oppress one another.',
    commentary: 'This is a Hadith Qudsi (sacred hadith where Allah speaks). It covers all aspects of the relationship between Allah and His servants — guidance, forgiveness, provision. The core message: never wrong others, and always turn to Allah.',
    source: 'Muslim 2577',
  },
  {
    number: 25,
    title: 'Charity on Every Joint',
    category: 'community',
    arabic: 'كُلُّ سُلامَى مِنَ النَّاسِ عَلَيْهِ صَدَقَةٌ كُلَّ يَوْمٍ تَطْلُعُ فِيهِ الشَّمْسُ تَعْدِلُ بَيْنَ اثْنَيْنِ صَدَقَةٌ',
    transliteration: "Kullu sulama minan-nasi 'alayhi sadaqatun kulla yawmin tatlu'u fihish-shams. Ta'dilu baynath-nayni sadaqah.",
    translation: 'Every joint of a person has a charity due on it every day the sun rises. Judging fairly between two people is a charity.',
    commentary: 'Charity is not only money — a smile, removing harm from the road, helping someone carry their goods, saying a good word, and even walking to prayer are all forms of sadaqah. Islam makes goodness accessible to everyone.',
    source: 'Bukhari 2989, Muslim 1009',
  },
  {
    number: 26,
    title: 'Every Good Deed Is Charity',
    category: 'community',
    arabic: 'كُلُّ مَعْرُوفٍ صَدَقَةٌ',
    transliteration: "Kullu ma'rufin sadaqah.",
    translation: 'Every good deed is a charity.',
    commentary: 'This concise hadith widens the scope of charity to include every good act — a kind word, a smile, removing an obstacle from the path, giving directions, or even meeting your brother with a cheerful face.',
    source: 'Bukhari 6021, Muslim 1005',
  },
  {
    number: 27,
    title: 'Righteousness and Sin',
    category: 'character',
    arabic: 'الْبِرُّ حُسْنُ الْخُلُقِ وَالإِثْمُ مَا حَاكَ فِي نَفْسِكَ وَكَرِهْتَ أَنْ يَطَّلِعَ عَلَيْهِ النَّاسُ',
    transliteration: "Al-birru husnul-khuluqi, wal-ithmu ma haka fi nafsika wa karihta an yattali'a 'alayhin-nas.",
    translation: 'Righteousness is good character, and sin is what wavers in your heart and which you dislike people finding out about.',
    commentary: 'Your conscience is a guide — when something makes you uncomfortable and you would be ashamed if others knew, that is a sign it may be sinful. Good character is the essence of righteousness in Islam.',
    source: 'Muslim 2553',
  },
  {
    number: 28,
    title: 'Obey the Ruler in Good',
    category: 'community',
    arabic: 'عَلَيْكُمْ بِالسَّمْعِ وَالطَّاعَةِ وَإِنْ تَأَمَّرَ عَلَيْكُمْ عَبْدٌ حَبَشِيٌّ',
    transliteration: "'Alaykum bis-sam'i wat-ta'ati wa in ta'ammara 'alaykum 'abdun habashiyy.",
    translation: 'I advise you to hear and obey, even if an Abyssinian slave were to be appointed over you.',
    commentary: 'This hadith emphasises obedience to legitimate authority to maintain social order, regardless of the leader\'s social status or ethnicity. However, obedience is only in what is good — there is no obedience to a creation in disobedience to the Creator.',
    source: 'Tirmidhi 1706',
  },
  {
    number: 29,
    title: 'Doors to Goodness',
    category: 'worship',
    arabic: 'أَلا أَدُلُّكَ عَلَى أَبْوَابِ الْخَيْرِ الصَّوْمُ جُنَّةٌ وَالصَّدَقَةُ تُطْفِئُ الْخَطِيئَةَ كَمَا يُطْفِئُ الْمَاءُ النَّارَ وَصَلاةُ الرَّجُلِ مِنْ جَوْفِ اللَّيْلِ',
    transliteration: "Ala adulluka 'ala abwabil-khayr? As-sawmu junnah, was-sadaqatu tutfi'ul-khatee'ata kama yutfi'ul-ma'un-nar, wa salatur-rajuli min jawfil-layl.",
    translation: 'Shall I not tell you of the gates of goodness? Fasting is a shield, charity extinguishes sin as water extinguishes fire, and the prayer of a person in the middle of the night.',
    commentary: 'Three powerful acts of worship: fasting protects from sin, charity erases past sins, and tahajjud (night prayer) is among the most beloved voluntary acts to Allah. The hadith also mentions that the head of the matter is Islam, its pillar is prayer, and its peak is jihad (striving).',
    source: 'Tirmidhi 2616',
  },
  {
    number: 30,
    title: 'Limits Set by Allah',
    category: 'halal-haram',
    arabic: 'إِنَّ اللَّهَ فَرَضَ فَرَائِضَ فَلا تُضَيِّعُوهَا وَحَدَّ حُدُودًا فَلا تَعْتَدُوهَا وَحَرَّمَ أَشْيَاءَ فَلا تَنْتَهِكُوهَا وَسَكَتَ عَنْ أَشْيَاءَ رَحْمَةً لَكُمْ غَيْرَ نِسْيَانٍ فَلا تَبْحَثُوا عَنْهَا',
    transliteration: "Innallaha farada fara'ida fala tudayyi'uha, wa hadda hududan fala ta'taduha, wa harrama ashya'a fala tantahikuha, wa sakata 'an ashya'a rahmatan lakum ghayra nisyanin fala tabhathu 'anha.",
    translation: 'Allah has set obligations, so do not neglect them. He has set limits, so do not transgress them. He has forbidden things, so do not violate them. And He has remained silent about things as a mercy to you, not out of forgetfulness, so do not seek them out.',
    commentary: 'This hadith outlines four categories: obligations to fulfil, limits to respect, prohibitions to avoid, and matters left unlegislated as a mercy. What Allah has not spoken about is permissible — do not make religion harder than it is.',
    source: 'Daraqutni, graded hasan',
  },
  {
    number: 31,
    title: 'True Asceticism',
    category: 'character',
    arabic: 'ازْهَدْ فِي الدُّنْيَا يُحِبَّكَ اللَّهُ وَازْهَدْ فِيمَا عِنْدَ النَّاسِ يُحِبَّكَ النَّاسُ',
    transliteration: "Izhad fid-dunya yuhibbakallah, wazhad feema 'indan-nasi yuhibbakan-nas.",
    translation: 'Be detached from the worldly life and Allah will love you. Be detached from what people possess and people will love you.',
    commentary: 'Zuhd (detachment) does not mean poverty — it means not being enslaved by material desires. When you are content with what Allah gives you and do not covet what others have, you gain both divine love and the love of people.',
    source: 'Ibn Majah 4102',
  },
  {
    number: 32,
    title: 'No Harm and No Reciprocal Harm',
    category: 'community',
    arabic: 'لَا ضَرَرَ وَلَا ضِرَارَ',
    transliteration: "La darara wa la dirar.",
    translation: 'There should be no harm and no reciprocal harm.',
    commentary: 'This is one of the five major maxims of Islamic jurisprudence (al-qawa\'id al-fiqhiyyah). Harm must not be initiated, and one harm must not be removed by another. This principle governs countless rulings in fiqh — from property disputes to environmental protection.',
    source: 'Ibn Majah 2340, Ahmad',
  },
  {
    number: 33,
    title: 'The Burden of Proof',
    category: 'community',
    arabic: 'لَوْ يُعْطَى النَّاسُ بِدَعْوَاهُمْ لَادَّعَى رِجَالٌ أَمْوَالَ قَوْمٍ وَدِمَاءَهُمْ لَكِنِ الْبَيِّنَةُ عَلَى الْمُدَّعِي وَالْيَمِينُ عَلَى مَنْ أَنْكَرَ',
    transliteration: "Law yu'tan-nasu bida'wahum la-idda'a rijalun amwala qawmin wa dima'ahum, lakinil-bayyinatu 'alal-mudda'i wal-yameenu 'ala man ankar.",
    translation: 'If people were given what they claimed, some men would claim the wealth and blood of others. But the burden of proof is on the claimant, and the oath is on the one who denies.',
    commentary: 'This hadith establishes a fundamental principle of Islamic justice that predates modern legal systems: the accuser must provide evidence, and the accused takes an oath of innocence. Justice cannot be based on mere claims.',
    source: 'Bukhari 4552, Muslim 1711',
  },
  {
    number: 34,
    title: 'Changing Wrong with Hand, Tongue, or Heart',
    category: 'community',
    arabic: 'مَنْ رَأَى مِنْكُمْ مُنْكَرًا فَلْيُغَيِّرْهُ بِيَدِهِ فَإِنْ لَمْ يَسْتَطِعْ فَبِلِسَانِهِ فَإِنْ لَمْ يَسْتَطِعْ فَبِقَلْبِهِ وَذَلِكَ أَضْعَفُ الإِيمَانِ',
    transliteration: "Man ra'a minkum munkaran falyughayyirhu biyadihi, fa-in lam yastati' fabilisanihi, fa-in lam yastati' fabiqalbihi, wa dhalika ad'aful-iman.",
    translation: 'Whoever among you sees an evil, let him change it with his hand; if he cannot, then with his tongue; if he cannot, then with his heart — and that is the weakest of faith.',
    commentary: 'This hadith establishes a graduated duty to enjoin good and forbid evil. Authority figures change by action, scholars by speech, and the general public by at least rejecting evil in their hearts. No one is exempt from some level of responsibility.',
    source: 'Muslim 49',
  },
  {
    number: 35,
    title: 'Brotherhood in Islam',
    category: 'community',
    arabic: 'لَا تَحَاسَدُوا وَلَا تَنَاجَشُوا وَلَا تَبَاغَضُوا وَلَا تَدَابَرُوا وَلَا يَبِعْ بَعْضُكُمْ عَلَى بَيْعِ بَعْضٍ وَكُونُوا عِبَادَ اللَّهِ إِخْوَانًا',
    transliteration: "La tahasadu wa la tanajashu wa la tabaghadhu wa la tadabaru wa la yabi' ba'dukum 'ala bay'i ba'din wa kunu 'ibadallahi ikhwana.",
    translation: 'Do not envy one another, do not inflate prices against one another, do not hate one another, do not turn away from one another, do not undercut one another in trade — be servants of Allah, brothers.',
    commentary: 'The Prophet defines the ethics of Muslim brotherhood: no envy, no market manipulation, no hatred, no shunning, and no underhanded dealings. Every Muslim is a brother to every other Muslim — their blood, wealth, and honour are sacred.',
    source: 'Muslim 2564',
  },
  {
    number: 36,
    title: 'Relieving a Believer\'s Hardship',
    category: 'community',
    arabic: 'مَنْ نَفَّسَ عَنْ مُؤْمِنٍ كُرْبَةً مِنْ كُرَبِ الدُّنْيَا نَفَّسَ اللَّهُ عَنْهُ كُرْبَةً مِنْ كُرَبِ يَوْمِ الْقِيَامَةِ',
    transliteration: "Man naffasa 'an mu'minin kurbatan min kurabid-dunya naffasallahu 'anhu kurbatan min kurabi yawmil-qiyamah.",
    translation: 'Whoever relieves a believer of a hardship of this world, Allah will relieve him of a hardship on the Day of Judgement.',
    commentary: 'Helping others is an investment in the Hereafter. This hadith motivates Muslims to help those in difficulty — whether financially, emotionally, or with knowledge. Allah will ease the path of one who makes things easy for others.',
    source: 'Muslim 2699',
  },
  {
    number: 37,
    title: 'Allah Records Good and Bad Deeds',
    category: 'faith',
    arabic: 'إِنَّ اللَّهَ كَتَبَ الْحَسَنَاتِ وَالسَّيِّئَاتِ ثُمَّ بَيَّنَ ذَلِكَ فَمَنْ هَمَّ بِحَسَنَةٍ فَلَمْ يَعْمَلْهَا كَتَبَهَا اللَّهُ عِنْدَهُ حَسَنَةً كَامِلَةً',
    transliteration: "Innallaha katabal-hasanati was-sayyi'at thumma bayyana dhalik. Faman hamma bihasanatin falam ya'malha katabahallahu 'indahu hasanatan kamilah.",
    translation: 'Allah has written down the good deeds and the bad deeds, then made that clear. Whoever intends a good deed but does not do it, Allah writes it as a complete good deed.',
    commentary: 'Allah\'s mercy is vast — intending good is rewarded even without action. Doing good is multiplied up to 700 times. Intending a sin but not doing it is written as a good deed. Actually committing a sin is written as only one sin. This shows Allah\'s immense mercy.',
    source: 'Bukhari 6491, Muslim 131',
  },
  {
    number: 38,
    title: 'Nearness to Allah Through Good Deeds',
    category: 'worship',
    arabic: 'مَنْ عَادَى لِي وَلِيًّا فَقَدْ آذَنْتُهُ بِالْحَرْبِ وَمَا تَقَرَّبَ إِلَيَّ عَبْدِي بِشَيْءٍ أَحَبَّ إِلَيَّ مِمَّا افْتَرَضْتُ عَلَيْهِ',
    transliteration: "Man 'ada li waliyyan faqad adhantahu bil-harb. Wa ma taqarraba ilayya 'abdi bishay'in ahabba ilayya mimmaf-taradtu 'alayh.",
    translation: 'Whoever shows enmity to a friend of Mine, I have declared war on him. My servant does not draw near to Me with anything more beloved to Me than what I have made obligatory upon him.',
    commentary: 'This Hadith Qudsi reveals how to become close to Allah: first through obligatory acts (fard), then through voluntary acts (nawafil). When Allah loves a servant, He becomes the hearing, sight, and hand of that servant — meaning Allah guides and protects all their faculties.',
    source: 'Bukhari 6502',
  },
  {
    number: 39,
    title: 'Forgiveness for Honest Mistakes',
    category: 'faith',
    arabic: 'إِنَّ اللَّهَ تَجَاوَزَ لِي عَنْ أُمَّتِي الْخَطَأَ وَالنِّسْيَانَ وَمَا اسْتُكْرِهُوا عَلَيْهِ',
    transliteration: "Innallaha tajawaza li 'an ummatiyal-khata'a wan-nisyana wa mustukrihu 'alayh.",
    translation: 'Allah has forgiven my ummah for mistakes, forgetfulness, and what they are coerced to do.',
    commentary: 'Islam is a religion of mercy and ease. Genuine mistakes, forgetfulness, and actions done under coercion are forgiven. This applies to worship (like forgetting to fast) and daily life. However, deliberate carelessness is different from a genuine mistake.',
    source: 'Ibn Majah 2043',
  },
  {
    number: 40,
    title: 'Be in This World as a Stranger',
    category: 'character',
    arabic: 'كُنْ فِي الدُّنْيَا كَأَنَّكَ غَرِيبٌ أَوْ عَابِرُ سَبِيلٍ',
    transliteration: "Kun fid-dunya ka-annaka ghareebun aw 'abiru sabeel.",
    translation: 'Be in this world as if you were a stranger or a traveller.',
    commentary: 'This world is temporary — we are passing through on our way to the Hereafter. A traveller does not invest in building permanent structures at a rest stop. Ibn Umar used to say: "When evening comes, do not expect to see the morning, and when morning comes, do not expect to see the evening."',
    source: 'Bukhari 6416',
  },
]

export const HADITH_CATEGORIES = [
  { key: 'all', label: 'All' },
  { key: 'faith', label: 'Faith & Intention' },
  { key: 'halal-haram', label: 'Halal & Haram' },
  { key: 'character', label: 'Character & Conduct' },
  { key: 'community', label: 'Community' },
  { key: 'worship', label: 'Worship' },
] as const
