export const HADITH_OF_DAY = [
  {
    arabic: "إِنَّمَا الْأَعْمَالُ بِالنِّيَّاتِ",
    transliteration: "Innamā al-a'mālu bin-niyyāt",
    english: "Actions are judged only by intentions.",
    source: "Bukhari & Muslim",
    narrator: "Umar ibn al-Khattab (رضي الله عنه)",
  },
  {
    arabic: "الدِّينُ النَّصِيحَةُ",
    transliteration: "Ad-dīnu an-nasīḥah",
    english: "The religion is sincere advice.",
    source: "Muslim",
    narrator: "Tamim al-Dari (رضي الله عنه)",
  },
  {
    arabic: "مَنْ كَانَ يُؤْمِنُ بِاللَّهِ وَالْيَوْمِ الْآخِرِ فَلْيَقُلْ خَيْرًا أَوْ لِيَصْمُتْ",
    transliteration: "Man kāna yu'minu billāhi wal-yawmil-ākhiri falyaqul khayran aw liyaṣmut",
    english: "Whoever believes in Allah and the Last Day should speak good or remain silent.",
    source: "Bukhari & Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ",
    transliteration: "Lā yu'minu aḥadukum ḥattā yuḥibba li-akhīhi mā yuḥibbu li-nafsih",
    english: "None of you truly believes until he loves for his brother what he loves for himself.",
    source: "Bukhari & Muslim",
    narrator: "Anas ibn Malik (رضي الله عنه)",
  },
  {
    arabic: "اتَّقِ اللَّهَ حَيْثُمَا كُنْتَ وَأَتْبِعِ السَّيِّئَةَ الْحَسَنَةَ تَمْحُهَا",
    transliteration: "Ittaqillāha ḥaythumā kunta, wa-atbi' as-sayyi'ata al-ḥasanata tamḥuhā",
    english: "Fear Allah wherever you are. Follow a bad deed with a good one to erase it, and treat people with good character.",
    source: "Tirmidhi",
    narrator: "Abu Dharr al-Ghifari (رضي الله عنه)",
  },
  {
    arabic: "الطَّهُورُ شَطْرُ الْإِيمَانِ",
    transliteration: "Aṭ-ṭahūru shaṭrul-īmān",
    english: "Purity is half of faith.",
    source: "Muslim",
    narrator: "Abu Malik al-Ashari (رضي الله عنه)",
  },
  {
    arabic: "خَيْرُكُمْ مَنْ تَعَلَّمَ الْقُرْآنَ وَعَلَّمَهُ",
    transliteration: "Khayrukum man ta'allamal-Qur'āna wa 'allamah",
    english: "The best of you are those who learn the Quran and teach it.",
    source: "Bukhari",
    narrator: "Uthman ibn Affan (رضي الله عنه)",
  },
  {
    arabic: "صَلِّ قَائِمًا، فَإِنْ لَمْ تَسْتَطِعْ فَقَاعِدًا، فَإِنْ لَمْ تَسْتَطِعْ فَعَلَى جَنْبٍ",
    transliteration: "Ṣalli qā'iman, fa-in lam tastaṭi' fa-qā'idan, fa-in lam tastaṭi' fa-'alā janb",
    english: "Pray standing; if you cannot, then sitting; if you cannot, then on your side.",
    source: "Bukhari",
    narrator: "Imran ibn Husain (رضي الله عنه)",
  },
  {
    arabic: "إِنَّ اللَّهَ لَا يَنْظُرُ إِلَى أَجْسَامِكُمْ وَلَا إِلَى صُوَرِكُمْ وَلَكِنْ يَنْظُرُ إِلَى قُلُوبِكُمْ",
    transliteration: "Innallāha lā yanẓuru ilā ajsāmikum wa lā ilā ṣuwarikum wa lākin yanẓuru ilā qulūbikum",
    english: "Allah does not look at your bodies or your faces, but He looks at your hearts.",
    source: "Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "مَا مِنْ أَيَّامٍ الْعَمَلُ الصَّالِحُ فِيهَا أَحَبُّ إِلَى اللَّهِ مِنْ هَذِهِ الْأَيَّامِ",
    transliteration: "Mā min ayyāmil 'amaluṣ-ṣāliḥu fīhā aḥabbu ilallāhi min hādhihil-ayyām",
    english: "There are no days on which righteous deeds are more beloved to Allah than the first ten days of Dhul-Hijjah.",
    source: "Bukhari",
    narrator: "Ibn Abbas (رضي الله عنهما)",
  },
  {
    arabic: "مَثَلُ الْمُؤْمِنِينَ فِي تَوَادِّهِمْ وَتَرَاحُمِهِمْ وَتَعَاطُفِهِمْ مَثَلُ الْجَسَدِ",
    transliteration: "Mathalul-mu'minīna fī tawāddihim wa tarāḥumihim wa ta'āṭufihim mathalul-jasad",
    english: "The believers in their mutual love, mercy, and compassion are like one body.",
    source: "Bukhari & Muslim",
    narrator: "Nu'man ibn Bashir (رضي الله عنه)",
  },
  {
    arabic: "إِنَّ مِنْ أَحَبِّكُمْ إِلَيَّ أَحْسَنَكُمْ أَخْلَاقًا",
    transliteration: "Inna min aḥabbikum ilayya aḥsanakum akhlāqā",
    english: "Indeed, the most beloved of you to me are those with the best character.",
    source: "Bukhari",
    narrator: "Abdullah ibn Amr (رضي الله عنه)",
  },
  {
    arabic: "إِذَا مَاتَ الْإِنْسَانُ انْقَطَعَ عَنْهُ عَمَلُهُ إِلَّا مِنْ ثَلَاثَةٍ",
    transliteration: "Idhā mātal-insānu inqaṭa'a 'anhu 'amaluhu illā min thalāthah",
    english: "When a person dies, all their deeds end except three: ongoing charity, beneficial knowledge, or a righteous child who prays for them.",
    source: "Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "أَحَبُّ الْأَعْمَالِ إِلَى اللَّهِ أَدْوَمُهَا وَإِنْ قَلَّ",
    transliteration: "Aḥabbul-a'māli ilallāhi adwamuhā wa in qall",
    english: "The most beloved deeds to Allah are the most consistent, even if they are few.",
    source: "Bukhari & Muslim",
    narrator: "Aisha (رضي الله عنها)",
  },
  {
    arabic: "مَنْ سَلَكَ طَرِيقًا يَلْتَمِسُ فِيهِ عِلْمًا سَهَّلَ اللَّهُ لَهُ طَرِيقًا إِلَى الْجَنَّةِ",
    transliteration: "Man salaka ṭarīqan yaltamisu fīhi 'ilman sahhallāhu lahu ṭarīqan ilal-jannah",
    english: "Whoever travels a path in search of knowledge, Allah will ease for them a path to Paradise.",
    source: "Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "الْمُسْلِمُ مَنْ سَلِمَ الْمُسْلِمُونَ مِنْ لِسَانِهِ وَيَدِهِ",
    transliteration: "Al-muslimu man salimal-muslimūna min lisānihi wa yadih",
    english: "A Muslim is one from whose tongue and hand other Muslims are safe.",
    source: "Bukhari",
    narrator: "Abdullah ibn Amr (رضي الله عنه)",
  },
  {
    arabic: "مَنْ لَا يَشْكُرُ النَّاسَ لَا يَشْكُرُ اللَّهَ",
    transliteration: "Man lā yashkurun-nāsa lā yashkurullāh",
    english: "Whoever does not thank people does not thank Allah.",
    source: "Abu Dawud & Tirmidhi",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "اسْتَعِينُوا بِالصَّبْرِ وَالصَّلَاةِ",
    transliteration: "Ista'īnū biṣ-ṣabri waṣ-ṣalāh",
    english: "Seek help through patience and prayer.",
    source: "Quran 2:45",
    narrator: "Allah, Most High",
  },
  {
    arabic: "إِنَّ مَعَ الْعُسْرِ يُسْرًا",
    transliteration: "Inna ma'al-'usri yusrā",
    english: "Indeed, with hardship comes ease.",
    source: "Quran 94:6",
    narrator: "Allah, Most High",
  },
  {
    arabic: "وَمَنْ يَتَّقِ اللَّهَ يَجْعَلْ لَهُ مَخْرَجًا",
    transliteration: "Wa man yattaqillāha yaj'al lahu makhraja",
    english: "Whoever fears Allah, He will make a way out for them.",
    source: "Quran 65:2",
    narrator: "Allah, Most High",
  },
  {
    arabic: "وَإِذَا سَأَلَكَ عِبَادِي عَنِّي فَإِنِّي قَرِيبٌ",
    transliteration: "Wa idhā sa'alaka 'ibādī 'annī fa-innī qarīb",
    english: "When My servants ask about Me — I am near. I respond to the call of the caller when they call on Me.",
    source: "Quran 2:186",
    narrator: "Allah, Most High",
  },
  {
    arabic: "إِنَّ الصَّلَاةَ تَنْهَى عَنِ الْفَحْشَاءِ وَالْمُنْكَرِ",
    transliteration: "Innaṣ-ṣalāta tanhā 'anil-faḥshā'i wal-munkar",
    english: "Indeed, prayer prohibits immorality and wrongdoing.",
    source: "Quran 29:45",
    narrator: "Allah, Most High",
  },
  {
    arabic: "تَبَسُّمُكَ فِي وَجْهِ أَخِيكَ صَدَقَةٌ",
    transliteration: "Tabassumukal fī wajhi akhīka ṣadaqah",
    english: "Your smile in the face of your brother is an act of charity.",
    source: "Tirmidhi",
    narrator: "Abu Dharr al-Ghifari (رضي الله عنه)",
  },
  {
    arabic: "إِنَّ اللَّهَ رَفِيقٌ يُحِبُّ الرِّفْقَ",
    transliteration: "Innallāha rafīqun yuḥibbur-rifq",
    english: "Allah is gentle and loves gentleness.",
    source: "Bukhari & Muslim",
    narrator: "Aisha (رضي الله عنها)",
  },
  {
    arabic: "الْمُؤْمِنُ الْقَوِيُّ خَيْرٌ وَأَحَبُّ إِلَى اللَّهِ مِنَ الْمُؤْمِنِ الضَّعِيفِ",
    transliteration: "Al-mu'minul-qawiyyu khayrun wa aḥabbu ilallāhi minal-mu'minid-ḍa'īf",
    english: "The strong believer is better and more beloved to Allah than the weak believer.",
    source: "Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "لَيْسَ الشَّدِيدُ بِالصُّرَعَةِ، إِنَّمَا الشَّدِيدُ الَّذِي يَمْلِكُ نَفْسَهُ عِنْدَ الْغَضَبِ",
    transliteration: "Laysa ash-shadīdu biṣ-ṣur'ah, innamaš-shadīdulladhī yamliku nafsahu 'indal-ghaḍab",
    english: "The strong person is not the one who wrestles others. The truly strong person controls themselves in anger.",
    source: "Bukhari & Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "إِنَّ اللَّهَ كَتَبَ الْإِحْسَانَ عَلَى كُلِّ شَيْءٍ",
    transliteration: "Innallāha kataba al-iḥsāna 'alā kulli shay'",
    english: "Allah has prescribed excellence in everything.",
    source: "Muslim",
    narrator: "Shaddad ibn Aws (رضي الله عنه)",
  },
  {
    arabic: "مَنْ أَصْبَحَ مِنْكُمْ آمِنًا فِي سِرْبِهِ مُعَافًى فِي جَسَدِهِ عِنْدَهُ قُوتُ يَوْمِهِ فَكَأَنَّمَا حِيزَتْ لَهُ الدُّنْيَا",
    transliteration: "Man aṣbaḥa minkum āminan fī sirbih, mu'āfan fī jasadih, 'indahu qūtu yawmih, fa-ka'annamā ḥīzat lahud-dunyā",
    english: "Whoever wakes up feeling safe, healthy in body, and has food for the day — it is as if the whole world has been granted to them.",
    source: "Tirmidhi",
    narrator: "Ubayda ibn al-Harith (رضي الله عنه)",
  },
  {
    arabic: "الدُّعَاءُ هُوَ الْعِبَادَةُ",
    transliteration: "Ad-du'ā'u huwal-'ibādah",
    english: "Dua (supplication) is worship.",
    source: "Tirmidhi",
    narrator: "Nu'man ibn Bashir (رضي الله عنه)",
  },
  {
    arabic: "مَا يُصِيبُ الْمُسْلِمَ مِنْ نَصَبٍ وَلَا وَصَبٍ وَلَا هَمٍّ وَلَا حُزْنٍ إِلَّا كَفَّرَ اللَّهُ بِهِ",
    transliteration: "Mā yuṣībul-muslima min naṣabin wa lā waṣabin wa lā hammin wa lā ḥuzn illā kaffar allāhu bih",
    english: "No fatigue, illness, worry, grief, harm, or sadness afflicts the Muslim, even a thorn prick, except that Allah expiates some of his sins by it.",
    source: "Bukhari",
    narrator: "Abu Said al-Khudri (رضي الله عنه)",
  },
  {
    arabic: "أَفْضَلُ الصِّيَامِ بَعْدَ رَمَضَانَ شَهْرُ اللَّهِ الْمُحَرَّمُ",
    transliteration: "Afḍaluṣ-ṣiyāmi ba'da Ramaḍāna shahru allāhil-Muḥarram",
    english: "The best fasting after Ramadan is the month of Allah — Muharram.",
    source: "Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "قَالَ اللَّهُ تَعَالَى: أَنَا عِنْدَ ظَنِّ عَبْدِي بِي",
    transliteration: "Qālallāhu ta'ālā: Anā 'inda ẓanni 'abdī bī",
    english: "Allah says: I am as My servant thinks of Me.",
    source: "Bukhari & Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "رَبِّ اغْفِرْ لِي وَتُبْ عَلَيَّ إِنَّكَ أَنْتَ التَّوَّابُ الرَّحِيمُ",
    transliteration: "Rabbighfir lī wa tub 'alayya innaka antat-tawwābur-raḥīm",
    english: "My Lord, forgive me and accept my repentance — You are the Ever-Relenting, the Merciful.",
    source: "Tirmidhi",
    narrator: "Ibn Umar (رضي الله عنه)",
  },
  {
    arabic: "حُبُّكَ الشَّيْءَ يُعْمِي وَيُصِمُّ",
    transliteration: "Ḥubbuka ash-shay'a yu'mī wa yuṣimm",
    english: "Your love of something can make you blind and deaf.",
    source: "Abu Dawud",
    narrator: "Abu Darda (رضي الله عنه)",
  },
  {
    arabic: "إِنَّ اللَّهَ جَمِيلٌ يُحِبُّ الْجَمَالَ",
    transliteration: "Innallāha jamīlun yuḥibbul-jamāl",
    english: "Allah is beautiful and loves beauty.",
    source: "Muslim",
    narrator: "Abdullah ibn Masud (رضي الله عنه)",
  },
  {
    arabic: "خَيْرُ الْقُرُونِ قَرْنِي ثُمَّ الَّذِينَ يَلُونَهُمْ ثُمَّ الَّذِينَ يَلُونَهُمْ",
    transliteration: "Khayrulqurūni qarnī thummal-ladhīna yalūnahum thummal-ladhīna yalūnahum",
    english: "The best of generations is my generation, then those after them, then those after them.",
    source: "Bukhari",
    narrator: "Abdullah ibn Masud (رضي الله عنه)",
  },
  {
    arabic: "مَنْ صَامَ رَمَضَانَ ثُمَّ أَتْبَعَهُ سِتًّا مِنْ شَوَّالٍ كَانَ كَصِيَامِ الدَّهْرِ",
    transliteration: "Man ṣāma Ramaḍāna thumma atba'ahu sittan min Shawwālin kāna kaṣiyāmid-dahr",
    english: "Whoever fasts Ramadan and follows it with six days from Shawwal, it is as if they fasted the entire year.",
    source: "Muslim",
    narrator: "Abu Ayyub al-Ansari (رضي الله عنه)",
  },
  {
    arabic: "بَلِّغُوا عَنِّي وَلَوْ آيَةً",
    transliteration: "Ballighu 'annī wa law āyah",
    english: "Convey from me, even if one verse.",
    source: "Bukhari",
    narrator: "Abdullah ibn Amr (رضي الله عنه)",
  },
  {
    arabic: "الصَّلَوَاتُ الْخَمْسُ وَالْجُمُعَةُ إِلَى الْجُمُعَةِ كَفَّارَةٌ لِمَا بَيْنَهُنَّ",
    transliteration: "Aṣ-ṣalawātul-khamsu wal-jumu'atu ilal-jumu'ati kaffāratun limā baynahunna",
    english: "The five daily prayers and Jumu'ah to the next Jumu'ah are expiation for what comes between them.",
    source: "Muslim",
    narrator: "Abu Hurairah (رضي الله عنه)",
  },
  {
    arabic: "كُلُّ بَنِي آدَمَ خَطَّاءٌ وَخَيْرُ الْخَطَّائِينَ التَّوَّابُونَ",
    transliteration: "Kullu banī Ādama khaṭṭā'un wa khayrulkhaṭṭā'īnat-tawwābūn",
    english: "Every son of Adam sins, and the best of those who sin are those who repent.",
    source: "Tirmidhi & Ibn Majah",
    narrator: "Anas ibn Malik (رضي الله عنه)",
  },
  {
    arabic: "مَنْ تَشَبَّهَ بِقَوْمٍ فَهُوَ مِنْهُمْ",
    transliteration: "Man tashabbaha biqawmin fa-huwa minhum",
    english: "Whoever imitates a people is one of them.",
    source: "Abu Dawud",
    narrator: "Abdullah ibn Umar (رضي الله عنه)",
  },
]

export function getTodayHadith() {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000)
  return HADITH_OF_DAY[dayOfYear % HADITH_OF_DAY.length]
}
