// ─── Islamic Glossary Data ───────────────────────────────────────────────────
// 80+ terms for new Muslims and anyone wanting to understand Islamic terminology

export type GlossaryCategory =
  | 'pillars'
  | 'prayer'
  | 'quran'
  | 'fiqh'
  | 'aqeedah'
  | 'character'
  | 'worship'
  | 'community'
  | 'greetings'

export interface GlossaryTerm {
  id: string
  term: string
  arabic: string
  plural?: string
  category: GlossaryCategory
  definition: string
  usage?: string
}

export const CATEGORY_LABELS: Record<GlossaryCategory, { label: string; color: string }> = {
  pillars:   { label: 'Pillars',    color: 'bg-emerald-500/15 text-emerald-400' },
  prayer:    { label: 'Prayer',     color: 'bg-blue-500/15 text-blue-400' },
  quran:     { label: 'Quran',      color: 'bg-purple-500/15 text-purple-400' },
  fiqh:      { label: 'Fiqh',       color: 'bg-amber-500/15 text-amber-400' },
  aqeedah:   { label: 'Beliefs',    color: 'bg-rose-500/15 text-rose-400' },
  character: { label: 'Character',  color: 'bg-teal-500/15 text-teal-400' },
  worship:   { label: 'Worship',    color: 'bg-indigo-500/15 text-indigo-400' },
  community: { label: 'Community',  color: 'bg-orange-500/15 text-orange-400' },
  greetings: { label: 'Phrases',    color: 'bg-pink-500/15 text-pink-400' },
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // ── Pillars & Core ──────────────────────────────────────────────────────
  { id: 'islam', term: 'Islam', arabic: 'إِسْلَام', category: 'pillars', definition: 'Submission and obedience to the will of Allah. Islam is the religion of all the Prophets, from Adam to Muhammad ﷺ. It is built upon five pillars: the Shahadah, Salah, Zakat, Sawm, and Hajj.', usage: '"Islam means peace through submission to God."' },
  { id: 'iman', term: 'Iman', arabic: 'إِيمَان', category: 'pillars', definition: 'Faith or belief. Iman has six pillars: belief in Allah, His angels, His books, His messengers, the Day of Judgement, and divine decree (Qadar). Iman increases with obedience and decreases with sin.', usage: '"Iman is what settles in the heart and is proven by actions."' },
  { id: 'ihsan', term: 'Ihsan', arabic: 'إِحْسَان', category: 'pillars', definition: 'Excellence in worship. To worship Allah as if you can see Him, for although you cannot see Him, He sees you. Ihsan is the highest level of faith.', usage: '"The Prophet ﷺ described Ihsan as the highest level of religion."' },
  { id: 'shahadah', term: 'Shahadah', arabic: 'شَهَادَة', category: 'pillars', definition: 'The declaration of faith: "I bear witness that there is no god but Allah, and Muhammad is the Messenger of Allah." It is the first pillar of Islam and the gateway to becoming Muslim.', usage: '"To accept Islam, one sincerely recites the Shahadah."' },
  { id: 'salah', term: 'Salah', arabic: 'صَلَاة', plural: 'Salawat', category: 'pillars', definition: 'The five daily obligatory prayers performed at specific times: Fajr (dawn), Dhuhr (noon), Asr (afternoon), Maghrib (sunset), and Isha (night). Salah is the second pillar of Islam and the first thing a person will be asked about on the Day of Judgement.', usage: '"Have you prayed your Salah today?"' },
  { id: 'zakat', term: 'Zakat', arabic: 'زَكَاة', category: 'pillars', definition: 'Obligatory charity. Muslims who possess wealth above a minimum threshold (nisab) must give 2.5% annually to those in need. It purifies wealth and is the third pillar of Islam.', usage: '"Zakat is due once a year on savings above the nisab."' },
  { id: 'sawm', term: 'Sawm', arabic: 'صَوْم', category: 'pillars', definition: 'Fasting, especially during the month of Ramadan. From dawn (Fajr) to sunset (Maghrib), Muslims abstain from food, drink, and intimate relations. It is the fourth pillar of Islam.', usage: '"Sawm teaches patience, self-discipline, and empathy for the hungry."' },
  { id: 'hajj', term: 'Hajj', arabic: 'حَجّ', category: 'pillars', definition: 'The annual pilgrimage to Makkah that every able-bodied Muslim who can afford it must perform at least once in their lifetime. It takes place in the month of Dhul Hijjah. It is the fifth pillar of Islam.', usage: '"He saved for years to perform Hajj."' },
  { id: 'umrah', term: 'Umrah', arabic: 'عُمْرَة', category: 'pillars', definition: 'A voluntary pilgrimage to Makkah that can be performed at any time of the year. It includes Tawaf (circling the Kaaba) and Sa\'i (walking between Safa and Marwa). Unlike Hajj, it is not obligatory.', usage: '"They went for Umrah during Ramadan."' },

  // ── Prayer ──────────────────────────────────────────────────────────────
  { id: 'wudu', term: 'Wudu', arabic: 'وُضُوء', category: 'prayer', definition: 'Ritual ablution (washing) before prayer. It involves washing the hands, mouth, nose, face, arms to the elbows, wiping the head, and washing the feet. Wudu is required for Salah to be valid.', usage: '"Make sure you have wudu before you pray."' },
  { id: 'ghusl', term: 'Ghusl', arabic: 'غُسْل', category: 'prayer', definition: 'Full-body ritual washing required after major impurity (e.g., after marital relations, menstruation, or post-natal bleeding). It is also Sunnah before Jumu\'ah and Eid prayers.', usage: '"Ghusl is required before praying after janabah."' },
  { id: 'tayammum', term: 'Tayammum', arabic: 'تَيَمُّم', category: 'prayer', definition: 'Dry ablution using clean earth or sand when water is unavailable or harmful to use. The face and hands are wiped with dust. It substitutes for both wudu and ghusl.', usage: '"When travelling in the desert without water, one may perform tayammum."' },
  { id: 'adhan', term: 'Adhan', arabic: 'أَذَان', category: 'prayer', definition: 'The call to prayer announced from the masjid before each of the five daily prayers. The mu\'adhin (caller) proclaims the greatness of Allah and invites Muslims to come to prayer.', usage: '"The adhan for Fajr woke him before dawn."' },
  { id: 'iqamah', term: 'Iqamah', arabic: 'إِقَامَة', category: 'prayer', definition: 'The second call to prayer given immediately before the congregation begins. It is shorter than the adhan and signals that the prayer is about to start.', usage: '"Stand up — the iqamah has been called."' },
  { id: 'imam', term: 'Imam', arabic: 'إِمَام', plural: 'A\'immah', category: 'prayer', definition: 'The person who leads the congregational prayer. More broadly, it can refer to a leader or scholar of the Muslim community. The Imam stands in front and the congregation follows their movements.', usage: '"The Imam recited Surah Al-Mulk in Isha prayer tonight."' },
  { id: 'rakat', term: 'Rak\'ah', arabic: 'رَكْعَة', plural: 'Raka\'at', category: 'prayer', definition: 'One unit (cycle) of prayer. Each rak\'ah consists of standing (Qiyam), bowing (Ruku), standing again, prostrating (Sujud) twice, and sitting briefly. Fajr has 2 raka\'at, Dhuhr 4, Asr 4, Maghrib 3, and Isha 4.', usage: '"Fajr prayer consists of 2 raka\'at."' },
  { id: 'fard', term: 'Fard', arabic: 'فَرْض', category: 'prayer', definition: 'An obligatory act in Islam. Something that is fard must be performed; neglecting it is sinful. The five daily prayers, fasting in Ramadan, and Hajj are all fard.', usage: '"The five daily prayers are fard upon every adult Muslim."' },
  { id: 'wajib', term: 'Wajib', arabic: 'وَاجِب', category: 'prayer', definition: 'Necessary or required. In the Hanafi school, wajib is a level between fard and Sunnah. Witr prayer, for example, is wajib according to Hanafi scholars. Neglecting a wajib act without valid excuse is sinful.', usage: '"Witr prayer is wajib in the Hanafi school."' },
  { id: 'sunnah', term: 'Sunnah', arabic: 'سُنَّة', plural: 'Sunan', category: 'prayer', definition: 'A practice of the Prophet Muhammad ﷺ. In prayer context, Sunnah prayers are voluntary but highly recommended acts that the Prophet regularly performed. Following the Sunnah brings reward; omitting it is not sinful.', usage: '"She prays 2 raka\'at Sunnah before Fajr every day."' },
  { id: 'nafl', term: 'Nafl', arabic: 'نَفْل', plural: 'Nawafil', category: 'prayer', definition: 'Voluntary or supererogatory acts of worship. Nafl prayers are optional but bring extra reward and closeness to Allah. Examples include Tahajjud (night prayer) and Duha (forenoon prayer).', usage: '"He prays extra nafl prayers after Isha."' },
  { id: 'qada', term: 'Qada', arabic: 'قَضَاء', category: 'prayer', definition: 'Making up a missed obligatory act of worship. If a fard prayer is missed, it must be made up (qada) as soon as possible. Similarly, missed fasts in Ramadan must be made up before the next Ramadan.', usage: '"She has qada fasts from last Ramadan to complete."' },
  { id: 'khushu', term: 'Khushu\'', arabic: 'خُشُوع', category: 'prayer', definition: 'Humility, concentration, and devotion in prayer. Khushu\' means being fully present and mindful during Salah, with the heart focused on Allah. It is the soul of the prayer.', usage: '"Pray with khushu\' — as if it is your last prayer."' },
  { id: 'qibla', term: 'Qibla', arabic: 'قِبْلَة', category: 'prayer', definition: 'The direction of the Ka\'bah in Makkah, which Muslims face during prayer. All Muslims around the world pray facing the Qibla as a sign of unity.', usage: '"Use a compass to find the Qibla direction from your location."' },

  // ── Quran ───────────────────────────────────────────────────────────────
  { id: 'quran', term: 'Quran', arabic: 'قُرْآن', category: 'quran', definition: 'The holy book of Islam, revealed by Allah to Prophet Muhammad ﷺ through the angel Jibreel over 23 years. It contains 114 surahs and is the primary source of guidance for Muslims.', usage: '"He reads a portion of the Quran every day after Fajr."' },
  { id: 'surah', term: 'Surah', arabic: 'سُورَة', plural: 'Suwar', category: 'quran', definition: 'A chapter of the Quran. There are 114 surahs, ranging from the shortest (Al-Kawthar, 3 verses) to the longest (Al-Baqarah, 286 verses).', usage: '"We studied Surah Al-Mulk in the madrasa today."' },
  { id: 'ayah', term: 'Ayah', arabic: 'آيَة', plural: 'Ayat', category: 'quran', definition: 'A verse of the Quran. The word literally means "sign" or "miracle." The Quran contains over 6,236 ayat.', usage: '"This ayah was revealed during the battle of Badr."' },
  { id: 'juz', term: 'Juz\'', arabic: 'جُزْء', plural: 'Ajza\'', category: 'quran', definition: 'One of the 30 equal parts the Quran is divided into for ease of reading. Many Muslims aim to read one juz per day during Ramadan to complete the entire Quran.', usage: '"I\'m on juz 15 of my Ramadan reading."' },
  { id: 'hafiz', term: 'Hafiz', arabic: 'حَافِظ', plural: 'Huffaz', category: 'quran', definition: 'A person who has memorised the entire Quran by heart. This is a highly respected achievement in the Muslim community. The plural is huffaz.', usage: '"The young hafiz led Taraweeh prayer from memory."' },
  { id: 'tajweed', term: 'Tajweed', arabic: 'تَجْوِيد', category: 'quran', definition: 'The set of rules for the correct pronunciation and recitation of the Quran. It covers letter articulation points, elongation, nasal sounds, and pausing rules. Learning tajweed is essential for proper recitation.', usage: '"She enrolled in a tajweed class to improve her recitation."' },
  { id: 'tafsir', term: 'Tafsir', arabic: 'تَفْسِير', category: 'quran', definition: 'Explanation and interpretation of the Quran. Scholars of tafsir study the historical context, linguistic meaning, and legal implications of Quranic verses. Famous tafsir works include Ibn Kathir and Al-Tabari.', usage: '"Reading tafsir deepens your understanding of the Quran."' },
  { id: 'tilawah', term: 'Tilawah', arabic: 'تِلَاوَة', category: 'quran', definition: 'Recitation of the Quran. Tilawah implies careful, melodious, and respectful reading of the Quran with proper tajweed.', usage: '"Her tilawah of Surah Ar-Rahman was beautiful."' },
  { id: 'mushaf', term: 'Mushaf', arabic: 'مُصْحَف', plural: 'Masahif', category: 'quran', definition: 'A physical or digital copy of the Quran text. The mushaf is treated with great respect and should be handled in a state of wudu.', usage: '"He kept a mushaf on his bedside table."' },

  // ── Fiqh ────────────────────────────────────────────────────────────────
  { id: 'fiqh', term: 'Fiqh', arabic: 'فِقْه', category: 'fiqh', definition: 'Islamic jurisprudence. The understanding of Islamic law derived from the Quran, Sunnah, consensus (ijma), and analogy (qiyas). It covers acts of worship, transactions, family law, and more.', usage: '"She studied fiqh to understand the rulings of purification."' },
  { id: 'madhab', term: 'Madhab', arabic: 'مَذْهَب', plural: 'Madhahib', category: 'fiqh', definition: 'A school of Islamic legal thought. The four main Sunni madhahib are Hanafi, Maliki, Shafi\'i, and Hanbali. Each was founded by a major scholar and represents a methodology for deriving Islamic rulings.', usage: '"Most Muslims in Guyana follow the Hanafi madhab."' },
  { id: 'halal', term: 'Halal', arabic: 'حَلَال', category: 'fiqh', definition: 'Permissible according to Islamic law. It applies to food, drink, actions, and transactions. For meat to be halal, the animal must be slaughtered in the name of Allah following specific guidelines.', usage: '"Is this restaurant halal-certified?"' },
  { id: 'haram', term: 'Haram', arabic: 'حَرَام', category: 'fiqh', definition: 'Forbidden or prohibited in Islam. Actions such as consuming alcohol, eating pork, gambling, and dealing in interest (riba) are haram. Committing haram acts is sinful.', usage: '"Backbiting is haram in Islam."' },
  { id: 'makruh', term: 'Makruh', arabic: 'مَكْرُوه', category: 'fiqh', definition: 'Disliked or discouraged. An act that is not sinful to do but is better to avoid. Avoiding makruh acts is rewarded but doing them is not punished.', usage: '"Eating raw garlic before going to the masjid is makruh."' },
  { id: 'mustahab', term: 'Mustahab', arabic: 'مُسْتَحَبّ', category: 'fiqh', definition: 'Recommended or preferred. An act that is rewarded if performed but not sinful if omitted. Using miswak (tooth-stick) before prayer is mustahab.', usage: '"Fasting on Mondays and Thursdays is mustahab."' },
  { id: 'fatwa', term: 'Fatwa', arabic: 'فَتْوَى', plural: 'Fatawa', category: 'fiqh', definition: 'A formal Islamic legal opinion given by a qualified scholar (mufti) in response to a question. A fatwa is not binding law but serves as scholarly guidance for Muslims.', usage: '"He consulted the mufti for a fatwa on his business question."' },
  { id: 'hadith', term: 'Hadith', arabic: 'حَدِيث', plural: 'Ahadith', category: 'fiqh', definition: 'A recorded saying, action, or approval of Prophet Muhammad ﷺ. Hadith literature is the second most important source of Islamic law after the Quran. Major collections include Bukhari, Muslim, Abu Dawud, and Tirmidhi.', usage: '"This hadith is narrated in Sahih Bukhari."' },
  { id: 'sunnah-source', term: 'Sunnah (Prophetic)', arabic: 'سُنَّة', category: 'fiqh', definition: 'The way of life and teachings of Prophet Muhammad ﷺ, including his sayings, actions, habits, and silent approvals. The Sunnah is the second source of Islamic legislation after the Quran.', usage: '"The Sunnah teaches us how to apply the Quran in daily life."' },
  { id: 'ijma', term: 'Ijma\'', arabic: 'إِجْمَاع', category: 'fiqh', definition: 'Scholarly consensus. When the qualified scholars of a generation unanimously agree on a ruling, it becomes a binding source of Islamic law. It is the third source of fiqh after the Quran and Sunnah.', usage: '"There is ijma that the five daily prayers are obligatory."' },

  // ── Aqeedah (Beliefs) ───────────────────────────────────────────────────
  { id: 'tawheed', term: 'Tawheed', arabic: 'تَوْحِيد', category: 'aqeedah', definition: 'The oneness of Allah. The fundamental belief that Allah is One, without partner, equal, or rival. Tawheed is the foundation of Islam and the essence of the Shahadah.', usage: '"Tawheed is the most important concept in Islam."' },
  { id: 'shirk', term: 'Shirk', arabic: 'شِرْك', category: 'aqeedah', definition: 'Associating partners with Allah. Shirk is the gravest sin in Islam, whether it involves worshipping other deities, attributing divine qualities to creation, or performing acts of worship for other than Allah.', usage: '"Shirk is the one sin that Allah has said He will not forgive if one dies upon it."' },
  { id: 'tawbah', term: 'Tawbah', arabic: 'تَوْبَة', category: 'aqeedah', definition: 'Repentance. Sincere repentance involves feeling genuine remorse, stopping the sin, and resolving never to return to it. Allah loves those who turn to Him in repentance.', usage: '"The door of tawbah is always open."' },
  { id: 'tawakkul', term: 'Tawakkul', arabic: 'تَوَكُّل', category: 'aqeedah', definition: 'Reliance upon Allah. Trusting Allah\'s plan while still making effort. Tawakkul means doing your part and then leaving the outcome to Allah.', usage: '"Tie your camel and have tawakkul."' },
  { id: 'akhirah', term: 'Akhirah', arabic: 'آخِرَة', category: 'aqeedah', definition: 'The Hereafter or afterlife. Muslims believe in life after death, including the Day of Judgement, Paradise (Jannah), and Hellfire (Jahannam).', usage: '"We work in this dunya for the akhirah."' },
  { id: 'jannah', term: 'Jannah', arabic: 'جَنَّة', category: 'aqeedah', definition: 'Paradise. The eternal abode of bliss promised to the righteous believers. It has multiple levels, with Firdaus being the highest.', usage: '"May Allah grant us all Jannah."' },
  { id: 'qadar', term: 'Qadar', arabic: 'قَدَر', category: 'aqeedah', definition: 'Divine decree or predestination. The belief that everything that happens is by the will and knowledge of Allah. Belief in Qadar is one of the six articles of faith.', usage: '"Whatever happens is by the qadar of Allah."' },
  { id: 'dunya', term: 'Dunya', arabic: 'دُنْيَا', category: 'aqeedah', definition: 'The worldly life. Islam teaches that this life is temporary and a test, and that the akhirah (afterlife) is the permanent, true life.', usage: '"Do not let the dunya distract you from preparing for the akhirah."' },

  // ── Character ───────────────────────────────────────────────────────────
  { id: 'sabr', term: 'Sabr', arabic: 'صَبْر', category: 'character', definition: 'Patience and perseverance. One of the most praised qualities in Islam. Sabr includes patience during hardship, patience in avoiding sin, and patience in maintaining obedience to Allah.', usage: '"Allah is with those who have sabr."' },
  { id: 'shukr', term: 'Shukr', arabic: 'شُكْر', category: 'character', definition: 'Gratitude and thankfulness to Allah. Shukr is expressed through the heart, tongue, and actions. Being grateful increases blessings.', usage: '"If you show shukr, I will increase you." (Quran 14:7)' },
  { id: 'taqwa', term: 'Taqwa', arabic: 'تَقْوَى', category: 'character', definition: 'God-consciousness. Being aware of Allah in every action and striving to obey Him and avoid what He has forbidden. Taqwa is the most honoured quality a Muslim can have.', usage: '"The most honoured of you with Allah is the one with the most taqwa."' },
  { id: 'ikhlas', term: 'Ikhlas', arabic: 'إِخْلَاص', category: 'character', definition: 'Sincerity. Performing acts of worship purely for the sake of Allah, without showing off or seeking praise from people. Ikhlas is a condition for any deed to be accepted by Allah.', usage: '"Without ikhlas, even good deeds lose their reward."' },
  { id: 'adab', term: 'Adab', arabic: 'أَدَب', plural: 'Aadab', category: 'character', definition: 'Manners, etiquette, and proper conduct. Islam places great emphasis on good manners in all situations, from how you greet people to how you eat, speak, and treat your parents.', usage: '"The Prophet ﷺ was the best example of adab."' },
  { id: 'amanah', term: 'Amanah', arabic: 'أَمَانَة', category: 'character', definition: 'Trustworthiness and fulfilling trusts. It covers everything from keeping secrets to returning borrowed items to being honest in business.', usage: '"A believer must fulfil their amanah."' },
  { id: 'sidq', term: 'Sidq', arabic: 'صِدْق', category: 'character', definition: 'Truthfulness and honesty. Being truthful in speech, actions, and intentions. The Prophet ﷺ said truthfulness leads to righteousness, and righteousness leads to Jannah.', usage: '"Sidq is the foundation of good character."' },

  // ── Worship ─────────────────────────────────────────────────────────────
  { id: 'dhikr', term: 'Dhikr', arabic: 'ذِكْر', category: 'worship', definition: 'Remembrance of Allah. This includes saying phrases like SubhanAllah, Alhamdulillah, and AllahuAkbar, as well as reciting Quran and making dua. Dhikr brings tranquillity to the heart.', usage: '"In the remembrance of Allah do hearts find rest."' },
  { id: 'dua', term: 'Du\'a', arabic: 'دُعَاء', plural: 'Ad\'iyah', category: 'worship', definition: 'Supplication or personal prayer to Allah. Unlike Salah which has a fixed format, dua can be made at any time in any language. It is described as "the weapon of the believer."', usage: '"Make dua with certainty that Allah will answer."' },
  { id: 'tasbih', term: 'Tasbih', arabic: 'تَسْبِيح', category: 'worship', definition: 'Saying "SubhanAllah" (Glory be to Allah). Also refers to the prayer beads used to count dhikr. Saying SubhanAllah 33 times after each prayer is a Sunnah.', usage: '"She uses her tasbih to count her dhikr after Salah."' },
  { id: 'istighfar', term: 'Istighfar', arabic: 'اِسْتِغْفَار', category: 'worship', definition: 'Seeking forgiveness from Allah by saying "Astaghfirullah." The Prophet ﷺ used to make istighfar more than 70 times daily. It erases sins and brings relief from hardship.', usage: '"Make istighfar frequently — it opens doors you didn\'t know existed."' },
  { id: 'sadaqah', term: 'Sadaqah', arabic: 'صَدَقَة', category: 'worship', definition: 'Voluntary charity given for the sake of Allah. Unlike Zakat (which is obligatory), sadaqah can be any amount and can take many forms, including a kind word or even a smile.', usage: '"Even removing a harmful thing from the road is sadaqah."' },
  { id: 'tahajjud', term: 'Tahajjud', arabic: 'تَهَجُّد', category: 'worship', definition: 'Voluntary night prayer performed after sleeping and before Fajr. It is one of the most beloved voluntary prayers and a time when dua is especially accepted.', usage: '"The last third of the night is the best time for tahajjud."' },
  { id: 'witr', term: 'Witr', arabic: 'وِتْر', category: 'worship', definition: 'An odd-numbered prayer performed after Isha, typically 1 or 3 raka\'at. In the Hanafi school, Witr is wajib (necessary). In other schools, it is a confirmed Sunnah. It includes Dua al-Qunoot.', usage: '"Don\'t forget to pray your Witr before sleeping."' },
  { id: 'itikaf', term: 'I\'tikaf', arabic: 'اعْتِكَاف', category: 'worship', definition: 'Spiritual retreat in the masjid, especially during the last 10 days of Ramadan. The person stays in the masjid for worship, Quran reading, and dhikr, seeking Laylatul Qadr.', usage: '"He spent the last 10 nights of Ramadan in i\'tikaf."' },
  { id: 'salawat', term: 'Salawat', arabic: 'صَلَوَات', category: 'worship', definition: 'Sending blessings upon the Prophet Muhammad ﷺ by saying "Allahumma salli \'ala Muhammad." Also called Durood. It is highly rewarded and recommended, especially on Fridays.', usage: '"Increase your salawat on Fridays."' },

  // ── Community ───────────────────────────────────────────────────────────
  { id: 'masjid', term: 'Masjid', arabic: 'مَسْجِد', plural: 'Masajid', category: 'community', definition: 'A place of worship for Muslims (mosque). The word literally means "place of prostration." The masjid is the centre of the Muslim community for prayer, learning, and gatherings.', usage: '"The masjid was filled for Jumu\'ah prayer."' },
  { id: 'mihrab', term: 'Mihrab', arabic: 'مِحْرَاب', category: 'community', definition: 'The niche or alcove in the wall of a masjid that indicates the direction of the Qibla (towards Makkah). The Imam stands in or near the mihrab to lead prayer.', usage: '"The mihrab of this masjid is beautifully decorated."' },
  { id: 'minbar', term: 'Minbar', arabic: 'مِنْبَر', category: 'community', definition: 'The pulpit in a masjid from which the Imam delivers the Jumu\'ah (Friday) sermon (khutbah). It is typically a raised platform with steps.', usage: '"The Imam ascended the minbar to deliver the khutbah."' },
  { id: 'khutbah', term: 'Khutbah', arabic: 'خُطْبَة', category: 'community', definition: 'A sermon or speech, especially the Friday (Jumu\'ah) sermon delivered before the congregational prayer. The khutbah typically addresses current issues, Quranic reminders, and moral guidance.', usage: '"The khutbah was about the importance of honesty."' },
  { id: 'jumuah', term: 'Jumu\'ah', arabic: 'جُمُعَة', category: 'community', definition: 'The Friday congregational prayer. It replaces Dhuhr on Fridays and is obligatory for adult Muslim men. It includes a khutbah (sermon) followed by 2 raka\'at of prayer.', usage: '"Jumu\'ah prayer is at 1:15 PM this week."' },
  { id: 'ummah', term: 'Ummah', arabic: 'أُمَّة', category: 'community', definition: 'The global Muslim community. All Muslims, regardless of nationality, race, or language, belong to one Ummah united by faith.', usage: '"We are one Ummah — when one part hurts, we all feel it."' },
  { id: 'shura', term: 'Shura', arabic: 'شُورَى', category: 'community', definition: 'Consultation and mutual deliberation. Islam encourages leaders to consult with their community before making decisions. It is a principle of Islamic governance.', usage: '"The committee held a shura to decide on the new masjid project."' },

  // ── Greetings & Phrases ─────────────────────────────────────────────────
  { id: 'assalamu-alaikum', term: 'Assalamu Alaikum', arabic: 'السَّلَامُ عَلَيْكُمْ', category: 'greetings', definition: 'Peace be upon you. The standard Islamic greeting. The full form is "Assalamu Alaikum wa Rahmatullahi wa Barakatuhu" (Peace, mercy, and blessings of Allah be upon you). It is Sunnah to greet first.', usage: 'Used whenever meeting or greeting another Muslim.' },
  { id: 'bismillah', term: 'Bismillah', arabic: 'بِسْمِ اللّٰهِ', category: 'greetings', definition: 'In the name of Allah. Said before beginning any action, such as eating, drinking, starting work, or entering a vehicle. The full phrase is "Bismillahir-Rahmanir-Rahim."', usage: '"Always say Bismillah before you eat."' },
  { id: 'alhamdulillah-phrase', term: 'Alhamdulillah', arabic: 'الْحَمْدُ لِلّٰهِ', category: 'greetings', definition: 'All praise is due to Allah. Said to express gratitude in all circumstances, whether after eating, sneezing, receiving good news, or even during hardship (because the believer trusts Allah\'s plan).', usage: '"Alhamdulillah, the surgery went well."' },
  { id: 'subhanallah-phrase', term: 'SubhanAllah', arabic: 'سُبْحَانَ اللّٰهِ', category: 'greetings', definition: 'Glory be to Allah. An expression of praise and amazement at Allah\'s creation and perfection. Said when seeing something beautiful, hearing something remarkable, or in dhikr.', usage: '"SubhanAllah — look at that sunset."' },
  { id: 'allahu-akbar-phrase', term: 'AllahuAkbar', arabic: 'اللّٰهُ أَكْبَرُ', category: 'greetings', definition: 'Allah is the Greatest. Used in the adhan, during prayer, and as a general expression of faith. It reminds Muslims that Allah is greater than any worldly matter or difficulty.', usage: '"The mu\'adhin calls AllahuAkbar four times to begin the adhan."' },
  { id: 'inshallah', term: 'Insha\'Allah', arabic: 'إِنْ شَاءَ اللّٰهُ', category: 'greetings', definition: 'If Allah wills. Said when speaking about future plans or intentions. The Quran instructs Muslims to say this when discussing anything they intend to do in the future.', usage: '"I will visit you tomorrow, Insha\'Allah."' },
  { id: 'mashallah', term: 'Masha\'Allah', arabic: 'مَا شَاءَ اللّٰهُ', category: 'greetings', definition: 'What Allah has willed. An expression of appreciation, joy, and praise. Said when admiring something to acknowledge that all good comes from Allah and to protect against the evil eye.', usage: '"Masha\'Allah, your children are so well-behaved."' },
  { id: 'jazakallah', term: 'Jazakallahu Khairan', arabic: 'جَزَاكَ اللّٰهُ خَيْرًا', category: 'greetings', definition: 'May Allah reward you with goodness. The Islamic way of saying "thank you." It asks Allah to reward the person for their kindness.', usage: '"Jazakallahu khairan for your help today."' },
  { id: 'barakallah', term: 'Barakallahu Feek', arabic: 'بَارَكَ اللّٰهُ فِيكَ', category: 'greetings', definition: 'May Allah bless you. A supplication asking for Allah\'s blessings to be bestowed upon someone. Often said in response to good news or a kind gesture.', usage: '"Barakallahu feek — may Allah bless your family."' },
  { id: 'ameen', term: 'Ameen', arabic: 'آمِين', category: 'greetings', definition: 'O Allah, accept (our prayer). Said after making dua and after the recitation of Surah Al-Fatihah in Salah. It means "O Allah, answer this prayer."', usage: '"May Allah grant us Jannah. Ameen."' },
  { id: 'inna-lillahi', term: 'Inna lillahi wa inna ilayhi raji\'un', arabic: 'إِنَّا لِلّٰهِ وَإِنَّا إِلَيْهِ رَاجِعُونَ', category: 'greetings', definition: 'To Allah we belong and to Him we shall return. Said upon hearing of someone\'s death or any calamity. It is from Surah Al-Baqarah (2:156) and expresses acceptance of Allah\'s decree.', usage: '"Inna lillahi wa inna ilayhi raji\'un — may Allah have mercy on him."' },
  { id: 'la-hawla-phrase', term: 'La hawla wa la quwwata illa billah', arabic: 'لَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللّٰهِ', category: 'greetings', definition: 'There is no power and no strength except with Allah. A powerful phrase of dhikr. The Prophet ﷺ called it a treasure from the treasures of Jannah. Said when facing difficulty or witnessing a wrong.', usage: '"La hawla wa la quwwata illa billah — only Allah can change this situation."' },
  { id: 'astaghfirullah-phrase', term: 'Astaghfirullah', arabic: 'أَسْتَغْفِرُ اللّٰهَ', category: 'greetings', definition: 'I seek forgiveness from Allah. Said when making a mistake, committing a sin (even unintentionally), or as part of regular dhikr. The Prophet ﷺ sought forgiveness more than 70 times a day.', usage: '"Astaghfirullah — I shouldn\'t have said that."' },
]
