export interface IslamicName {
  name: string
  arabic: string
  meaning: string
  origin: 'Arabic' | 'Persian' | 'Turkish' | 'Urdu' | 'Quranic'
  gender: 'Male' | 'Female' | 'Unisex'
  root?: string
}

export const ISLAMIC_NAMES: IslamicName[] = [
  // ── Male Names ──
  { name: 'Muhammad', arabic: 'مُحَمَّد', meaning: 'Praised, praiseworthy', origin: 'Arabic', gender: 'Male', root: 'ح-م-د' },
  { name: 'Ahmad', arabic: 'أَحْمَد', meaning: 'Most praiseworthy, most commendable', origin: 'Arabic', gender: 'Male', root: 'ح-م-د' },
  { name: 'Ibrahim', arabic: 'إِبْرَاهِيم', meaning: 'Father of nations', origin: 'Quranic', gender: 'Male' },
  { name: 'Ismail', arabic: 'إِسْمَاعِيل', meaning: 'God will hear', origin: 'Quranic', gender: 'Male' },
  { name: 'Yusuf', arabic: 'يُوسُف', meaning: 'God increases, beautiful', origin: 'Quranic', gender: 'Male' },
  { name: 'Musa', arabic: 'مُوسَى', meaning: 'Drawn from the water', origin: 'Quranic', gender: 'Male' },
  { name: 'Isa', arabic: 'عِيسَى', meaning: 'God is salvation', origin: 'Quranic', gender: 'Male' },
  { name: 'Adam', arabic: 'آدَم', meaning: 'Made from earth, first man', origin: 'Quranic', gender: 'Male' },
  { name: 'Idris', arabic: 'إِدْرِيس', meaning: 'Studious, interpreter', origin: 'Quranic', gender: 'Male' },
  { name: 'Nuh', arabic: 'نُوح', meaning: 'Rest, comfort', origin: 'Quranic', gender: 'Male' },
  { name: 'Dawud', arabic: 'دَاوُود', meaning: 'Beloved', origin: 'Quranic', gender: 'Male' },
  { name: 'Sulayman', arabic: 'سُلَيْمَان', meaning: 'Man of peace', origin: 'Quranic', gender: 'Male' },
  { name: 'Yahya', arabic: 'يَحْيَى', meaning: 'God gives life', origin: 'Quranic', gender: 'Male' },
  { name: 'Zakariyya', arabic: 'زَكَرِيَّا', meaning: 'God remembers', origin: 'Quranic', gender: 'Male' },
  { name: 'Harun', arabic: 'هَارُون', meaning: 'Exalted, high mountain', origin: 'Quranic', gender: 'Male' },
  { name: 'Saleh', arabic: 'صَالِح', meaning: 'Righteous, pious', origin: 'Quranic', gender: 'Male', root: 'ص-ل-ح' },
  { name: 'Hud', arabic: 'هُود', meaning: 'Guidance', origin: 'Quranic', gender: 'Male' },
  { name: 'Luqman', arabic: 'لُقْمَان', meaning: 'Wise man', origin: 'Quranic', gender: 'Male' },
  { name: 'Ali', arabic: 'عَلِيّ', meaning: 'Exalted, noble, high', origin: 'Arabic', gender: 'Male', root: 'ع-ل-و' },
  { name: 'Umar', arabic: 'عُمَر', meaning: 'Life, flourishing, long-lived', origin: 'Arabic', gender: 'Male', root: 'ع-م-ر' },
  { name: 'Uthman', arabic: 'عُثْمَان', meaning: 'Baby bustard (a bird), wise', origin: 'Arabic', gender: 'Male' },
  { name: 'Bakr', arabic: 'بَكْر', meaning: 'Young camel, firstborn', origin: 'Arabic', gender: 'Male' },
  { name: 'Bilal', arabic: 'بِلَال', meaning: 'Moisture, freshness', origin: 'Arabic', gender: 'Male' },
  { name: 'Khalid', arabic: 'خَالِد', meaning: 'Eternal, immortal', origin: 'Arabic', gender: 'Male', root: 'خ-ل-د' },
  { name: 'Tariq', arabic: 'طَارِق', meaning: 'Morning star, night visitor', origin: 'Arabic', gender: 'Male', root: 'ط-ر-ق' },
  { name: 'Usamah', arabic: 'أُسَامَة', meaning: 'Lion', origin: 'Arabic', gender: 'Male' },
  { name: 'Hassan', arabic: 'حَسَن', meaning: 'Good, handsome, beautiful', origin: 'Arabic', gender: 'Male', root: 'ح-س-ن' },
  { name: 'Husain', arabic: 'حُسَيْن', meaning: 'Good, handsome (diminutive)', origin: 'Arabic', gender: 'Male', root: 'ح-س-ن' },
  { name: 'Abdullah', arabic: 'عَبْدُ اللَّه', meaning: 'Servant of Allah', origin: 'Arabic', gender: 'Male', root: 'ع-ب-د' },
  { name: 'Abdul Rahman', arabic: 'عَبْدُ الرَّحْمَن', meaning: 'Servant of the Most Merciful', origin: 'Arabic', gender: 'Male', root: 'ر-ح-م' },
  { name: 'Zaid', arabic: 'زَيْد', meaning: 'Growth, abundance', origin: 'Arabic', gender: 'Male', root: 'ز-ي-د' },
  { name: 'Amr', arabic: 'عَمْرو', meaning: 'Life, lively', origin: 'Arabic', gender: 'Male' },
  { name: 'Hamza', arabic: 'حَمْزَة', meaning: 'Strong, steadfast, lion', origin: 'Arabic', gender: 'Male' },
  { name: 'Jibril', arabic: 'جِبْرِيل', meaning: 'Strength of God (Angel Gabriel)', origin: 'Quranic', gender: 'Male' },
  { name: 'Mikail', arabic: 'مِيكَائِيل', meaning: 'Who is like God (Angel Michael)', origin: 'Quranic', gender: 'Male' },
  { name: 'Israfil', arabic: 'إِسْرَافِيل', meaning: 'The burning one (Angel of the trumpet)', origin: 'Arabic', gender: 'Male' },
  { name: 'Malik', arabic: 'مَالِك', meaning: 'King, owner, master', origin: 'Arabic', gender: 'Male', root: 'م-ل-ك' },
  { name: 'Sufyan', arabic: 'سُفْيَان', meaning: 'Fast-moving, devoted', origin: 'Arabic', gender: 'Male' },
  { name: 'Faris', arabic: 'فَارِس', meaning: 'Knight, horseman', origin: 'Arabic', gender: 'Male' },
  { name: 'Rayyan', arabic: 'رَيَّان', meaning: 'Gate of Paradise for those who fast', origin: 'Arabic', gender: 'Male' },
  { name: 'Ziyad', arabic: 'زِيَاد', meaning: 'Growth, increase, abundance', origin: 'Arabic', gender: 'Male', root: 'ز-ي-د' },
  { name: 'Suhail', arabic: 'سُهَيْل', meaning: 'Gentle, easy; a bright star (Canopus)', origin: 'Arabic', gender: 'Male' },
  { name: 'Qasim', arabic: 'قَاسِم', meaning: 'One who distributes, divider', origin: 'Arabic', gender: 'Male', root: 'ق-س-م' },
  { name: 'Walid', arabic: 'وَلِيد', meaning: 'Newborn, son', origin: 'Arabic', gender: 'Male', root: 'و-ل-د' },

  // ── Female Names ──
  { name: 'Fatimah', arabic: 'فَاطِمَة', meaning: 'One who abstains, captivating', origin: 'Arabic', gender: 'Female', root: 'ف-ط-م' },
  { name: 'Aisha', arabic: 'عَائِشَة', meaning: 'Living, alive, prosperous', origin: 'Arabic', gender: 'Female', root: 'ع-ي-ش' },
  { name: 'Khadijah', arabic: 'خَدِيجَة', meaning: 'Premature child, trustworthy', origin: 'Arabic', gender: 'Female' },
  { name: 'Maryam', arabic: 'مَرْيَم', meaning: 'Beloved, pious worshipper', origin: 'Quranic', gender: 'Female' },
  { name: 'Asiya', arabic: 'آسِيَة', meaning: 'One who heals, comforts', origin: 'Arabic', gender: 'Female' },
  { name: 'Hajar', arabic: 'هَاجَر', meaning: 'To emigrate, flight', origin: 'Arabic', gender: 'Female' },
  { name: 'Ruqayyah', arabic: 'رُقَيَّة', meaning: 'Rise, ascent, charm', origin: 'Arabic', gender: 'Female' },
  { name: 'Zainab', arabic: 'زَيْنَب', meaning: "Father's precious jewel", origin: 'Arabic', gender: 'Female' },
  { name: 'Hafsa', arabic: 'حَفْصَة', meaning: 'Young lioness, gatherer', origin: 'Arabic', gender: 'Female' },
  { name: 'Safiyyah', arabic: 'صَفِيَّة', meaning: 'Pure, sincere friend', origin: 'Arabic', gender: 'Female', root: 'ص-ف-و' },
  { name: 'Umm Kulthum', arabic: 'أُمّ كُلْثُوم', meaning: 'One with full cheeks, plump', origin: 'Arabic', gender: 'Female' },
  { name: 'Sumayya', arabic: 'سُمَيَّة', meaning: 'High, exalted, sky', origin: 'Arabic', gender: 'Female' },
  { name: 'Bilqis', arabic: 'بِلْقِيس', meaning: 'Queen of Sheba', origin: 'Arabic', gender: 'Female' },
  { name: 'Lubnah', arabic: 'لُبْنَى', meaning: 'Tree with sweet sap, honey', origin: 'Arabic', gender: 'Female' },
  { name: 'Nour', arabic: 'نُور', meaning: 'Light, radiance', origin: 'Quranic', gender: 'Unisex', root: 'ن-و-ر' },
  { name: 'Sara', arabic: 'سَارَة', meaning: 'Princess, pure, joyful', origin: 'Arabic', gender: 'Female' },
  { name: 'Rahmah', arabic: 'رَحْمَة', meaning: 'Mercy, compassion', origin: 'Quranic', gender: 'Female', root: 'ر-ح-م' },
  { name: 'Saba', arabic: 'سَبَأ', meaning: 'Morning breeze; an ancient kingdom', origin: 'Quranic', gender: 'Female' },
  { name: 'Mariam', arabic: 'مَرِيَم', meaning: 'Beloved, pious (variant of Maryam)', origin: 'Quranic', gender: 'Female' },
  { name: 'Amira', arabic: 'أَمِيرَة', meaning: 'Princess, leader', origin: 'Arabic', gender: 'Female', root: 'أ-م-ر' },
  { name: 'Layla', arabic: 'لَيْلَى', meaning: 'Night, dark beauty', origin: 'Arabic', gender: 'Female' },
  { name: 'Hana', arabic: 'هَنَاء', meaning: 'Happiness, bliss', origin: 'Arabic', gender: 'Female' },
  { name: 'Yasmin', arabic: 'يَاسَمِين', meaning: 'Jasmine flower', origin: 'Persian', gender: 'Female' },
  { name: 'Rania', arabic: 'رَانِيَا', meaning: 'Gazing, queenly', origin: 'Arabic', gender: 'Female' },
  { name: 'Nadia', arabic: 'نَادِيَة', meaning: 'Caller, moist, tender', origin: 'Arabic', gender: 'Female', root: 'ن-د-و' },
  { name: 'Dina', arabic: 'دِينَا', meaning: 'Faith, religion, obedience', origin: 'Arabic', gender: 'Female' },
  { name: 'Salma', arabic: 'سَلْمَى', meaning: 'Safe, peaceful', origin: 'Arabic', gender: 'Female', root: 'س-ل-م' },
  { name: 'Imaan', arabic: 'إِيمَان', meaning: 'Faith, belief', origin: 'Quranic', gender: 'Female', root: 'أ-م-ن' },
  { name: 'Amal', arabic: 'أَمَل', meaning: 'Hope, aspiration', origin: 'Arabic', gender: 'Female' },
  { name: 'Jannah', arabic: 'جَنَّة', meaning: 'Garden, paradise', origin: 'Quranic', gender: 'Female' },
  { name: 'Rayan', arabic: 'رَيَّان', meaning: 'Lush, luxuriant; gate of Paradise', origin: 'Arabic', gender: 'Unisex' },
  { name: 'Huda', arabic: 'هُدَى', meaning: 'Guidance, right path', origin: 'Quranic', gender: 'Female', root: 'ه-د-ي' },
  { name: 'Sakina', arabic: 'سَكِينَة', meaning: 'Tranquility, peace of mind', origin: 'Quranic', gender: 'Female', root: 'س-ك-ن' },
  { name: 'Zahra', arabic: 'زَهْرَاء', meaning: 'Radiant, luminous, flower', origin: 'Arabic', gender: 'Female', root: 'ز-ه-ر' },
  { name: 'Asma', arabic: 'أَسْمَاء', meaning: 'Supreme, exalted, names', origin: 'Arabic', gender: 'Female' },
  { name: 'Baseera', arabic: 'بَصِيرَة', meaning: 'Insightful, perceptive', origin: 'Arabic', gender: 'Female', root: 'ب-ص-ر' },
  { name: 'Karima', arabic: 'كَرِيمَة', meaning: 'Generous, noble', origin: 'Arabic', gender: 'Female', root: 'ك-ر-م' },
]
