export interface Masjid {
  id: string
  name: string
  address: string
  type: string
  lat: number
  lng: number
  area: string
  facilities: string[]
  jumuah: boolean
  phone?: string
  hours?: string
  prayerTimes?: string
  prayerTimesDetail?: Record<string, string>   // { Fajr: '5:20 AM', ... }
  imam?: string                                 // Imam / Ameer name
  notes?: string                               // Community notes / description
  iftaarInfo?: string                          // Ramadan iftaar arrangements
  verified?: boolean
}

export const AREAS = ['All', 'Georgetown', 'East Coast Demerara', 'Berbice', 'Linden', 'West Demerara'] as const

export const MASJIDS: Masjid[] = [
  {
    id: '1',
    name: 'Queenstown Jama Masjid',
    address: 'Queenstown, Georgetown',
    type: 'Sunni',
    lat: 6.8100,
    lng: -58.1600,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes'],
    jumuah: true,
    hours: '5:00 AM - 9:00 PM',
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '2',
    name: 'Masjid Al-Noor',
    address: 'Alexander Village, Georgetown',
    type: 'Sunni',
    lat: 6.7950,
    lng: -58.1520,
    area: 'Georgetown',
    facilities: ['Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '3',
    name: 'Central Islamic Organisation Masjid',
    address: 'Woolford Ave, Georgetown',
    type: 'Sunni',
    lat: 6.8085,
    lng: -58.1555,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes', 'Library'],
    jumuah: true,
    phone: '592-226-0610',
    hours: '5:00 AM - 10:00 PM',
    prayerTimes: "All 5 daily prayers + Jumu'ah",
    verified: true,
  },
  {
    id: '4',
    name: 'Masjid-ur-Rahman',
    address: 'Kitty, Georgetown',
    type: 'Sunni',
    lat: 6.8150,
    lng: -58.1450,
    area: 'Georgetown',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '5',
    name: 'Albouystown Masjid',
    address: 'Albouystown, Georgetown',
    type: 'Sunni',
    lat: 6.7980,
    lng: -58.1620,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '6',
    name: 'Georgetown Ahmadiyya Mosque',
    address: 'Ogle, East Coast Demerara',
    type: 'Ahmadiyya',
    lat: 6.8080,
    lng: -58.1050,
    area: 'East Coast Demerara',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Library'],
    jumuah: true,
    verified: true,
  },
  {
    id: '7',
    name: 'Masjid At-Taqwa',
    address: 'Campbellville, Georgetown',
    type: 'Sunni',
    lat: 6.8060,
    lng: -58.1500,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '8',
    name: 'Turkeyen Islamic Centre',
    address: 'Turkeyen, Greater Georgetown',
    type: 'Sunni',
    lat: 6.8120,
    lng: -58.0920,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes', 'Library'],
    jumuah: true,
    hours: '5:00 AM - 9:30 PM',
    prayerTimes: "All 5 daily prayers + Jumu'ah",
    verified: true,
  },
  {
    id: '9',
    name: 'Annandale Jama Masjid',
    address: 'Annandale, East Coast Demerara',
    type: 'Sunni',
    lat: 6.7420,
    lng: -57.9880,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '10',
    name: 'Buxton Islamic Centre',
    address: 'Buxton, East Coast Demerara',
    type: 'Sunni',
    lat: 6.7550,
    lng: -57.9580,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '11',
    name: 'Mahaica Masjid',
    address: 'Mahaica, East Coast Demerara',
    type: 'Sunni',
    lat: 6.5870,
    lng: -57.8980,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    verified: false,
  },
  {
    id: '12',
    name: 'New Amsterdam Central Masjid',
    address: 'New Amsterdam, Berbice',
    type: 'Sunni',
    lat: 6.2426,
    lng: -57.5189,
    area: 'Berbice',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes'],
    jumuah: true,
    phone: '592-333-2180',
    hours: '5:00 AM - 9:00 PM',
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '13',
    name: 'Rose Hall Town Masjid',
    address: 'Rose Hall, Berbice',
    type: 'Sunni',
    lat: 6.2670,
    lng: -57.3670,
    area: 'Berbice',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '14',
    name: 'Linden Islamic Centre',
    address: 'Mackenzie, Linden',
    type: 'Sunni',
    lat: 6.0050,
    lng: -58.2990,
    area: 'Linden',
    facilities: ['Parking', 'Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '15',
    name: 'Vreed-en-Hoop Jama Masjid',
    address: 'Vreed-en-Hoop, West Demerara',
    type: 'Sunni',
    lat: 6.8020,
    lng: -58.1920,
    area: 'West Demerara',
    facilities: ['Parking', 'Wudu Area', "Women's Section"],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '16',
    name: 'Leonora Masjid',
    address: 'Leonora, West Demerara',
    type: 'Sunni',
    lat: 6.6540,
    lng: -58.2500,
    area: 'West Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    verified: false,
  },
  {
    id: '17',
    name: 'Masjid-ul-Muttaqeen',
    address: 'Prashad Nagar, Georgetown',
    type: 'Sunni',
    lat: 6.8110,
    lng: -58.1530,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '18',
    name: 'Beterverwagting Masjid',
    address: 'Beterverwagting, East Coast Demerara',
    type: 'Sunni',
    lat: 6.7930,
    lng: -58.0750,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    verified: false,
  },
  {
    id: '19',
    name: 'Corentyne Jama Masjid',
    address: 'Corriverton, Berbice',
    type: 'Sunni',
    lat: 6.2320,
    lng: -57.1750,
    area: 'Berbice',
    facilities: ['Parking', 'Wudu Area', "Women's Section"],
    jumuah: true,
    phone: '592-339-2290',
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '20',
    name: 'Triumph Islamic Centre',
    address: 'Triumph, East Coast Demerara',
    type: 'Sunni',
    lat: 6.7640,
    lng: -58.0300,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area', 'Classes'],
    jumuah: true,
    verified: false,
  },
  {
    id: '21',
    name: 'Kitty Jamaat Masjid',
    address: '79 Sandy Babb Street, Kitty, Georgetown',
    type: 'Sunni',
    lat: 6.817111,
    lng: -58.140062,
    area: 'Georgetown',
    facilities: ['Parking', 'Wudu Area', "Women's Section"],
    jumuah: true,
    phone: '',
    prayerTimes: 'All 5 daily prayers',
    prayerTimesDetail: {
      Fajr: '5:20 AM', Zuhr: '12:40 PM', Asr: '5:00 PM',
      Maghrib: '6:05 PM', Isha: '7:30 PM', "Jumu'ah": '12:30 PM',
    },
    notes: 'Well-established masjid in the heart of Kitty. Active Ramadan programmes. Listed on GIT Lecture Tour 2026. Adhan times — Salah begins 10 minutes after.',
    verified: true,
  },
  {
    id: '22',
    name: 'Darul Uloom Mosque',
    address: '310 East Street, Alberttown, Georgetown',
    type: 'Sunni',
    lat: 6.8137,
    lng: -58.1563,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    phone: '+592 223 0579',
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '23',
    name: 'Masjid An-Najm & Social Centre',
    address: 'Albouystown, Georgetown (former Star Cinema)',
    type: 'Sunni',
    lat: 6.8003,
    lng: -58.1625,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    notes: 'GIT-affiliated masjid and social centre opened 2012. Runs community outreach programmes.',
    verified: true,
  },
  {
    id: '24',
    name: 'McDoom Masjid',
    address: 'McDoom, East Bank Demerara',
    type: 'Sunni',
    lat: 6.782563,
    lng: -58.169563,
    area: 'East Bank Demerara',
    facilities: ['Wudu Area'],
    jumuah: true,
    phone: '+592 227 1546',
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '25',
    name: 'Masjid An-Nur (Westminster)',
    address: 'Westminster, West Bank Demerara',
    type: 'Sunni',
    lat: 6.774438,
    lng: -58.228313,
    area: 'West Demerara',
    facilities: ['Wudu Area'],
    jumuah: true,
    notes: 'Accessible via Demerara Harbour Bridge.',
    verified: true,
  },
]
