export interface Masjid {
  id: string
  name: string
  address: string
  type: string
  lat: number
  lng: number
  area: string
  facilities: string[]
  jumuah: boolean
  phone?: string
  hours?: string
  prayerTimes?: string
  prayerTimesDetail?: Record<string, string>   // { Fajr: '5:20 AM', ... }
  imam?: string                                 // Imam / Ameer name
  notes?: string                               // Community notes / description
  iftaarInfo?: string                          // Ramadan iftaar arrangements
  verified?: boolean
}

export const AREAS = ['All', 'Georgetown', 'East Coast Demerara', 'East Bank Demerara', 'Berbice', 'Linden', 'West Demerara'] as const

export const MASJIDS: Masjid[] = [
  {
    id: '1',
    name: 'Queenstown Jama Masjid',
    address: '295 Church Street, Queenstown, Georgetown',
    type: 'Sunni',
    lat: 6.810161,
    lng: -58.151108,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    notes: "Georgetown's principal masjid, founded 1895. Three-storey building with capacity for 1,000 worshippers. Two iconic octagonal minarets. Listed on GIT Lecture Tour 2026.",
    verified: true,
  },
  {
    id: '2',
    name: 'Masjid Al-Noor',
    address: 'Alexander Village, Georgetown',
    type: 'Sunni',
    lat: 6.7950,
    lng: -58.1520,
    area: 'Georgetown',
    facilities: ['Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '3',
    name: 'Woolford Avenue Mosque (MYO/CIOG)',
    address: 'Woolford Avenue, Thomas Lands, Georgetown',
    type: 'Sunni',
    lat: 6.818086,
    lng: -58.153222,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes', 'Library'],
    jumuah: true,
    phone: '592-225-6167',
    prayerTimes: 'All 5 daily prayers',
    notes: 'Home of the Muslim Youth Organisation (MYO) and CIOG headquarters. Hosts the National Ramadan Village on MYO lawns each Ramadan.',
    iftaarInfo: 'CIOG hosts the National Ramadan Village on MYO lawns — communal Iftaar open to all Muslims. Check CIOG announcements for this year\'s schedule.',
    verified: true,
  },
  {
    id: '4',
    name: 'Masjid-ur-Rahman',
    address: 'Kitty, Georgetown',
    type: 'Sunni',
    lat: 6.8150,
    lng: -58.1450,
    area: 'Georgetown',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '5',
    name: 'Albouystown Masjid',
    address: 'Albouystown, Georgetown',
    type: 'Sunni',
    lat: 6.7980,
    lng: -58.1620,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '6',
    name: 'Georgetown Ahmadiyya Mosque',
    address: 'Ogle, East Coast Demerara',
    type: 'Ahmadiyya',
    lat: 6.8080,
    lng: -58.1050,
    area: 'East Coast Demerara',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Library'],
    jumuah: true,
    verified: true,
  },
  {
    id: '7',
    name: 'Masjid At-Taqwa',
    address: 'Campbellville, Georgetown',
    type: 'Sunni',
    lat: 6.8060,
    lng: -58.1500,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: true,
  },
  {
    id: '8',
    name: 'Turkeyen Islamic Centre',
    address: 'Turkeyen, East Georgetown',
    type: 'Sunni',
    lat: 6.801188,
    lng: -58.118063,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes'],
    jumuah: true,
    phone: '+592 219 4286',
    prayerTimes: 'All 5 daily prayers',
    notes: 'Sunni mosque serving the Turkeyen and Sophia communities, associated with the Turkeyen Muslim Association.',
    verified: true,
  },
  {
    id: '9',
    name: 'Annandale Jama Masjid',
    address: 'Annandale, East Coast Demerara',
    type: 'Sunni',
    lat: 6.7420,
    lng: -57.9880,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '10',
    name: 'Buxton Islamic Centre',
    address: 'Buxton, East Coast Demerara',
    type: 'Sunni',
    lat: 6.7550,
    lng: -57.9580,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '11',
    name: 'Mahaica Masjid',
    address: 'Mahaica, East Coast Demerara',
    type: 'Sunni',
    lat: 6.5870,
    lng: -57.8980,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    verified: false,
  },
  {
    id: '12',
    name: 'New Amsterdam Central Masjid',
    address: 'New Amsterdam, Berbice',
    type: 'Sunni',
    lat: 6.2426,
    lng: -57.5189,
    area: 'Berbice',
    facilities: ['Parking', "Women's Section", 'Wudu Area', 'Classes'],
    jumuah: true,
    phone: '592-333-2180',
    hours: '5:00 AM - 9:00 PM',
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '13',
    name: 'Rose Hall Town Masjid',
    address: 'Rose Hall, Berbice',
    type: 'Sunni',
    lat: 6.2670,
    lng: -57.3670,
    area: 'Berbice',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '14',
    name: 'Linden Islamic Centre',
    address: 'Mackenzie, Linden',
    type: 'Sunni',
    lat: 6.0050,
    lng: -58.2990,
    area: 'Linden',
    facilities: ['Parking', 'Wudu Area', 'Classes'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '15',
    name: 'Vreed-en-Hoop Jama Masjid',
    address: 'Vreed-en-Hoop, West Demerara',
    type: 'Sunni',
    lat: 6.8020,
    lng: -58.1920,
    area: 'West Demerara',
    facilities: ['Parking', 'Wudu Area', "Women's Section"],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '16',
    name: 'Leonora Masjid',
    address: 'Leonora, West Demerara',
    type: 'Sunni',
    lat: 6.6540,
    lng: -58.2500,
    area: 'West Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    verified: false,
  },
  {
    id: '17',
    name: 'Masjid-ul-Muttaqeen',
    address: 'Prashad Nagar, Georgetown',
    type: 'Sunni',
    lat: 6.8110,
    lng: -58.1530,
    area: 'Georgetown',
    facilities: ['Parking', "Women's Section", 'Wudu Area'],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '18',
    name: 'Beterverwagting Masjid',
    address: 'Beterverwagting, East Coast Demerara',
    type: 'Sunni',
    lat: 6.7930,
    lng: -58.0750,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    verified: false,
  },
  {
    id: '19',
    name: 'Corentyne Jama Masjid',
    address: 'Corriverton, Berbice',
    type: 'Sunni',
    lat: 6.2320,
    lng: -57.1750,
    area: 'Berbice',
    facilities: ['Parking', 'Wudu Area', "Women's Section"],
    jumuah: true,
    phone: '592-339-2290',
    prayerTimes: 'All 5 daily prayers',
    verified: false,
  },
  {
    id: '20',
    name: 'Triumph Islamic Centre',
    address: 'Triumph, East Coast Demerara',
    type: 'Sunni',
    lat: 6.7640,
    lng: -58.0300,
    area: 'East Coast Demerara',
    facilities: ['Parking', 'Wudu Area', 'Classes'],
    jumuah: true,
    verified: false,
  },
  {
    id: '21',
    name: 'Kitty Jamaat Masjid',
    address: '79 Sandy Babb Street, Kitty, Georgetown',
    type: 'Sunni',
    lat: 6.817111,
    lng: -58.140062,
    area: 'Georgetown',
    facilities: ['Parking', 'Wudu Area', "Women's Section"],
    jumuah: true,
    prayerTimes: 'All 5 daily prayers',
    prayerTimesDetail: {
      Fajr: '5:20 AM', Zuhr: '12:40 PM', Asr: '5:00 PM',
      Maghrib: '6:05 PM', Isha: '7:30 PM', "Jumu'ah": '12:30 PM',
    },
    imam: 'Moulana Abdullah Khan',
    notes: 'Well-established masjid in the heart of Kitty. Active Ramadan programmes. Listed on GIT Lecture Tour 2026. Times shown are Salah/Iqamah times — Adhan is called 10 minutes before each prayer. President: Mufti Sajid Khan.',
    iftaarInfo: 'Active Iftaar and Taraweeh programmes during Ramadan. Taraweeh led by Mufti Sajid Khan (President) and Hafiz Anas. Tap to see community iftaar reports.',
    verified: true,
  },
  {
    id: '22',
    name: 'Darul Uloom Masjid (Islamic & Academic Institute)',
    address: '310 East Street, South Cummingsburg, Georgetown',
    type: 'Sunni',
    lat: 6.8137,
    lng: -58.1563,
    area: 'Georgetown',
    facilities: ['Parking', 'Wudu Area', "Women's Section", 'Classes', 'Library'],
    jumuah: true,
    phone: '+592 223-0579',
    prayerTimes: 'All 5 daily prayers',
    prayerTimesDetail: {
      Fajr: '4:58 AM', Zuhr: '12:11 PM', Asr: '4:25 PM',
      Maghrib: '6:08 PM', Isha: '7:15 PM', "Jumu'ah": '12:30 PM',
    },
    imam: 'Moulana Badrudeen Khan',
    notes: '"Education gives rise to a Nation." Head: Moulana Badrudeen Khan (623-2780). Contact: darululoomgt@gmail.com. Hosts D.E.H.C. (Halaal Committee) which certifies businesses including Church\'s Chicken. Islamic Store on premises: Mon-Fri 8:30AM-6PM, Sun 9AM-6PM (Tel: 223-0370).',
    iftaarInfo: 'Community Iftaar during Ramadan — $100,000 GYD per night (Saum Iftaar). Taraweeh led by Mufti Mohamed Irfan, Hafiz Khalid Lovell, and Hafiz Asif Ameer. All are invited. Sadaqatul Fitr 2026: $2,000 GYD per person.',
    verified: true,
  },
  {
    id: '23',
    name: 'Masjid An-Najm & Social Centre',
    address: 'Albouystown, Georgetown (former Star Cinema)',
    type: 'Sunni',
    lat: 6.8003,
    lng: -58.1625,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    notes: 'GIT-affiliated masjid and social centre opened 2012. Runs community outreach programmes.',
    verified: true,
  },
  {
    id: '24',
    name: 'McDoom Masjid',
    address: 'McDoom, East Bank Demerara',
    type: 'Sunni',
    lat: 6.782563,
    lng: -58.169563,
    area: 'East Bank Demerara',
    facilities: ['Wudu Area'],
    jumuah: true,
    phone: '+592 227 1546',
    prayerTimes: 'All 5 daily prayers',
    notes: 'Community masjid serving the McDoom area on the East Bank Demerara.',
    verified: true,
  },
  {
    id: '25',
    name: 'Masjid An-Nur (Westminster)',
    address: 'Westminster, West Bank Demerara',
    type: 'Sunni',
    lat: 6.774438,
    lng: -58.228313,
    area: 'West Demerara',
    facilities: ['Wudu Area'],
    jumuah: true,
    notes: 'Masjid serving the Westminster community on the West Bank Demerara (accessible via Demerara Harbour Bridge).',
    verified: true,
  },
  {
    id: '26',
    name: 'East Georgetown Sunnatul Jama Masjid',
    address: 'Prashad Nagar, East Georgetown',
    type: 'Sunni',
    lat: 6.812188,
    lng: -58.130063,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    phone: '+592 231 6575',
    notes: 'Sunni masjid in the Prashad Nagar / East Georgetown area.',
    verified: true,
  },
  {
    id: '27',
    name: "Ahmadiyya Anjuman Isha'at-I-Islam Lahore",
    address: '76 Brickdam & Winter Place, Stabroek, Georgetown',
    type: 'Lahore Ahmadiyya',
    lat: 6.806106,
    lng: -58.156321,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    notes: 'Lahore Ahmadiyya community mosque at the Brickdam headquarters, near Stabroek Market.',
    verified: true,
  },
  {
    id: '28',
    name: 'Baitul Noor Mosque',
    address: '198 Oronoque & Lance Gibbs Streets, Queenstown, Georgetown',
    type: 'Ahmadiyya',
    lat: 6.8131,
    lng: -58.1509,
    area: 'Georgetown',
    facilities: ["Women's Section", 'Wudu Area'],
    jumuah: true,
    phone: '+592 226-7634',
    notes: 'Ahmadiyya Muslim Community mosque. Note: The original building was demolished late 2025 to make way for a new 2-storey masjid complex — construction ongoing.',
    verified: true,
  },
  {
    id: '29',
    name: 'Old Mosque (South Georgetown)',
    address: 'South Georgetown',
    type: 'Sunni',
    lat: 6.794688,
    lng: -58.167188,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    phone: '+592 621 5331',
    notes: 'Historic mosque in southern Georgetown.',
    verified: true,
  },
  {
    id: '30',
    name: 'Providence Sunnatul Masjid',
    address: 'East Bank Public Road, Providence, East Bank Demerara',
    type: 'Sunni',
    lat: 6.755937,
    lng: -58.181063,
    area: 'East Bank Demerara',
    facilities: ['Parking', 'Wudu Area'],
    jumuah: true,
    notes: 'Masjid serving the Providence community on the East Bank Demerara.',
    verified: true,
  },
  {
    id: '31',
    name: 'Mandela Masjid',
    address: 'Mandela Avenue, Georgetown',
    type: 'Sunni',
    lat: 6.8050,
    lng: -58.1580,
    area: 'Georgetown',
    facilities: ['Wudu Area'],
    jumuah: true,
    notes: 'Masjid in the Mandela Avenue area of Georgetown.',
    verified: false,
  },
]
